### ISSUE TITLE
Colons in property values not properly handled in SMW 2.2.0

### ISSUE THREAD

**Issue by jaakristioja** [SemanticMediaWiki/SemanticMediaWiki#1048]
It seems that properties of type Text don't handle well values containing `::`, e.g. `[[Has IPv6::fc00:123:8000::/64]]` where `Property:Has_IPv6` `[[Has type:Text]]`. Any workaround for this?

**Comment by mwjames** [comment]
Interesting case but the regex to filter the `::` pattern hasn't changed (at least not since 1.8).

The current rule in [0] will split your example in 

```
array(3) {
  [0]=>
  string(32) "[[Has IPv6::fc00:123:8000::/64]]"
  [1]=>
  string(23) "Has IPv6::fc00:123:8000"
  [2]=>
  string(3) "/64"
}
```

and then split it further [1] to a property part
```
array(2) {
  [0]=>
  string(8) "Has IPv6"
  [1]=>
  string(13) "fc00:123:8000"
}
```
and a value part
```
string(3) "/64"
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L161

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L273

> Any workaround for this?

Not that I know of, @kghbln @JeroenDeDauw ?

**Comment by mwjames** [comment]
> Any workaround for this?

For the time being you could use `{{#set:Has IPv6=fc00:123:8000::/64}}`

**Comment by s7eph4n** [comment]
Although it is not very helpful in this case, it works as specified (see last row in the table at [1]), so using ``#set`` really is the way to go.

[1] http://semantic-mediawiki.org/wiki/Help:Properties_and_types#Turning_links_into_properties

**Comment by jaakristioja** [comment]
Interesting. Using `{{#set: }}` helps, thanks! But where is the `|template=` syntax for `{{#set: }}` documented? Or is `template` a special property?

**Comment by mwjames** [comment]
> |template= syntax for {{#set: }}

Only to be used if you want to display the value otherwise annotations are hidden by default using `#set`.

> But where is the |template= syntax for {{#set: }} documented?

- 
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.2.0.md#new-features
- https://semantic-mediawiki.org/wiki/Help:Setting_values#Template_parameter

**Comment by jaakristioja** [comment]
Thanks! I had no idea such help pages existed. All the information I had about `{{#set: }}` came from https://semantic-mediawiki.org/wiki/Help:Properties_and_types#Silent_annotations_using_.23set

**Comment by mwjames** [comment]
Example added to [0].

[0] https://semantic-mediawiki.org/w/index.php?title=Help:In-text_annotation&curid=8617&diff=39497&oldid=39494
