### ISSUE TITLE
Support single-value conjunctions in queries

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#1058]
Following up on #1043 here's an enhancement request for supporting conjunctions in query statements, most probably through extending our current query syntax. 

The syntax to be used - esp. what's most intuitive and unlikely to create new conflicts with data values -  probably still needs discussion. The suggestion by mkroetzsch is to use &&

Any takers?

**Comment by mwjames** [comment]
For anyone who wants to pick up the task, [0] needs to be extended so that `&&` can create an appropriate description tree.

PS: I think, if you build the description manually then the `SQLStore` / `SPARQLStore` should be able to resolve the query tree without further intervention.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_QueryParser.php

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
