### ISSUE TITLE
datatype date / error message duplicated

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1074]
If an improper value for this datatype is stored the error message gets duplicated. See [smw.o page on this datatype for an example.](https://semantic-mediawiki.org/wiki/Help:Type_Date)

**Comment by mwjames** [comment]
The problem is that the `_dat` type returns an error text in `getShortWikiText` [0] on the occasion of a not valid value and the  `InTextAnnotationParser` [1] explicitly ask for `$dataValue->getErrorText()` when encountered an error creating an odd situation where the error message is displayed twice.

PS: It is an old issue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_Time.php#L607-L613

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L307-L314

**Comment by mwjames** [comment]
Addressed with #1075

**Comment by kghbln** [comment]
> PS: It is an old issue.

Indeed and I always forgot to open an issue for this. :| My field test for the fix worked perfect. Thanks!
