### ISSUE TITLE
Concept misinterpreting query statement

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1096]
I may have stumbled on a bug with the use of 'concepts' (MW 1.24.2 + SMW 2.1.3). Today I created a concept containing the following query statement:

   `[[-Subject::<q>[[-Has subobject::Subject:Subject headings]]</q>]]`

or similarly,

   `[[-Subject.-Has subobject::Subject:Subject headings]]`

While an ask query produces results as expected, the concept comes up empty. The problem appears to be that whichever of the two queries above is used, it is internally understood as:

   `[[-Subject.Has subobject::Subject:Subject headings]]`

as is shown by the concept page. Note the absence of a inverse symbol before "Has subobject".

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue @D-Groenewegen!

@mkroetzsch does this ring any bells?

**Comment by mwjames** [comment]
While testing something else I came across this issue.

The problem has its roots in `SomeProperty::getQueryString` (returns a string representation) which is not used when resolving a `#ask` query but is used to store the query description as part of the concept representation.

`SomeProperty::getQueryString` omits the declaration for an inverse property. The fix is:

```
 		while ( ( $propertyname !== '' ) && ( $subDescription instanceof SomeProperty ) ) { // try to use property chain syntax
-			$propertyname = $subDescription->getProperty()->getLabel();
+			$propertyname = ( $subDescription->getProperty()->isInverse() ? '-' : '' ) . $subDescription->getProperty()->getLabel();
 
```
 
You were probably the first (and I was the second) to ever use this syntax in connection with a Concept and this why until now the issue was never uncovered.

This also fixes the query string display for `|format=debug` which was just incorrect for both `#ask` and `#concept` in cases of an inverse subquery condition.
