### ISSUE TITLE
composer update deletes only and not updates

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#1205]
When I run `composer update`, I get this:
```
  - Removing phpoffice/phpexcel (1.8.1)
Deleting extensions/SemanticForms/ - deleted
Deleting extensions/SemanticResultFormats/ - deleted
Deleting extensions/SemanticMediaWiki/ - deleted
Deleting extensions/Validator/ - deleted
  - Removing param-processor/param-processor (1.2.2)
  - Removing data-values/common (0.2.3)
  - Removing data-values/validators (0.1.2)
  - Removing data-values/data-values (1.0.0)
  - Removing data-values/interfaces (0.1.5)
  - Removing serialization/serialization (3.2.1)
  - Removing onoi/message-reporter (1.0.0)
  - Removing onoi/cache (1.2.0)
  - Removing onoi/event-dispatcher (1.0.0)
```
I expect SMW, SF, etc. to be updated, not deleted as, indeed, are non-semantic MediaWiki extensions.

The semantic extensions had been installed without limiting them to specific versions:
```
composer require --prefer-source mediawiki/semantic-media-wiki "*"
composer require --prefer-source mediawiki/semantic-result-formats "*"
composer require --prefer-source mediawiki/semantic-forms "*"
composer require --prefer-source phpoffice/phpexcel "*"
```

**Comment by JeroenDeDauw** [comment]
Which version of MediaWiki are you using? And did you upgrade since you installed those extensions?

Your list of extensions was presumably stored in MediaWikis `composer.json`, and got lost when you upgraded. Recent versions of MediaWiki have a `composer.local.json` file in which you can put extensions to install.

**Comment by JeroenDeDauw** [comment]
@kghbln @mwjames that also means we should not recommend using `composer require` when installing in MW, as this will put things into `composer.json`

**Comment by alex-mashin** [comment]
MW 1.25.2. I hadn't upgraded MW since I last installed SMW etc. because an upgrade (which includes running `composer update`) requires reinstalling SMW.

And what command should I use instead of `composer require`?

**Comment by kghbln** [comment]
@JeroenDeDauw Just to make sure: So there is now no way to install extensions via composer except for hand-crafting "composer.local.json".

**Comment by mwjames** [comment]
> And what command should I use instead of composer require?

Honestly, I lost track of what works and what doesn't with MW but I use `composer require` successfully with 1.25.2.

**Comment by JeroenDeDauw** [comment]
> @JeroenDeDauw Just to make sure: So there is now no way to install extensions via composer except for hand-crafting "composer.local.json".

If you install in the root of a recent MediaWiki, then I expect you need to modify that file yes. You can of course still use something like the ExtensionInstaller extension, though I rather see that go away.

Perhaps we can also port the code used by the [tarball building service](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1187) I recently created to finally have a UI for installing MW extensions. Me and @mwjames both started with creating something towards that end quite some time ago though never got far. I think a mistake we (or at least I) made there was trying to talk to Composer via PHP rather than its real public interface.

Though maybe this is not worth it if MW will provide something like this with the new extension registration stuff that is being worked on. Not sure that is going to get beyond being something half-assed that just causes work for little benefit though.

> Honestly, I lost track of what works and what doesn't with MW but I use composer require successfully with 1.25.2.

I sympathize, and also have lost track now there is this new extension registration stuff being worked on. However, I can say that with the latest MW, `composer require` will still work, its just that it'll put stuff in `composer.json`, which is a file now part of MW, so will be overridden when upgrading.

**Comment by mwjames** [comment]
I think there is no actionable task that can be attached to this issue and unless it is a documentation issue, I'm inclined to close this one.
