### ISSUE TITLE
https://semantic-mediawiki.org certificate expired

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#1263]
@kghbln in case you did not noticed yet. I think most people use www.semantic-mediawiki.org and not https://semantic-mediawiki.org but when you do this issue breaks the site. Regards.

**Comment by kghbln** [comment]
Yeah, I realised yesterday and already some e-mails were exchanged about this. I only control sandbox which is on a different server (my private one). Anyway, thanks for noticing since I only detected this by accident also!

@JeroenDeDauw FYI

**Comment by JeroenDeDauw** [comment]
Yeah, this is quite unfortunate... and still there at present.

**Comment by Matthias84** [comment]
I also mentioned, that the TLS setup needs some love https://semantic-mediawiki.org/wiki/Thread:Help_talk:Reporting_bugs/SSL_setup_broken

**Comment by kghbln** [comment]
We are now in good company:

![bildschirmfoto vom 2015-12-03 01 08 08](https://cloud.githubusercontent.com/assets/1104078/11548255/b26186ee-995a-11e5-8793-dcbbb7231bc5.png)

While our situation starts to be a bit embarrassing, I would not have expected something link this with sourceforge. I guess somebody looses his or her job tomorrow at their end.

**Comment by mwjames** [comment]
> Yeah, this is quite unfortunate... and still there at present.
> While our situation starts to be a bit embarrassing

@mkroetzsch @JeroenDeDauw @kghbln Okay (it is a ~month now), seriously what is this __ISSUE__ here, I thought we have the OSDA to deal what that sort of problem.

**Comment by kghbln** [comment]
Well OSDA is about re re-form(ate). However, I have slept over it and decided to take action myself if we can reach consensus on this, which in turn seems very likely. I will however act off this issue for the moment, so sit tight.

**Comment by JeroenDeDauw** [comment]
@kghbln the reason I asked for your IM details was to talk about this :)

@kghbln @mwjames as my request for access on the OSDA list was met with silence, I propose the following:

* I get a new VPS (which I'm happy to pay for) and give relevant people access
* Someone (kgh?) takes care of the task from hell (dealing with Apache) and setting up MW
* I transfer the contents of the current wiki to the new one
* Someone figures out how this SSL cert stuff actually works and makes everything fluffy again

How does that sound?

https://letsencrypt.org/ goes into public beta today, so presumably we can get a certificate from there.

**Comment by kghbln** [comment]
@JeroenDeDauw You could have told me. Would have just been a sentence difference, would't it? ;)

**Comment by Matthias84** [comment]
@JeroenDeDauw  sounds like a plan. LEC is a good alternative (compared to cacert, startssl,...) if we save costs. BTW does it make sense to donate to OSDA ?

**Comment by JeroenDeDauw** [comment]
@kghbln chat is still easier to hammer out details.

I'm going to go ahead and get me another Hetzner VPS. Can already set up a wiki and make SSL work for it without any agreement from OSDA. Such agreement is only needed for transferring actual content and changing the domain name pointer thing.

@Matthias84 I actually don't care if I pay for the VPS or not. What I do care about is that this gets done soon. Which is why I'm getting my own thing so we can start without further delays.

**Comment by mkroetzsch** [comment]
(I replied on email, but the thread here seems to overlap)

I would assume we can just add a server in our Hetzner account, if time is of the essence now and nobody wants to dare a dist-upgrade on the life system (I would risk it, after backing up the data -- it's Debian after all). Migrating DBs is not a nice taks (content is easy, but users require DB dumps). I suggest to try this simple route first (if you have a day to spend in case it all breaks and reinstall is required after all). A little risk, but then we are not Wikipedia regarding our availability targets ...

**Comment by kghbln** [comment]
@JeroenDeDauw I guess @mkroetzsch suggestion is ok provided that ... see my e-mail.

@Matthias84 Well donating is possible, but I would be even more happier if time on the wiki is donated, documenting stuff etc.

**Comment by JeroenDeDauw** [comment]
Update: we are currently trying to get a new VPS but are having some trouble with the hosting account credentials. Working on it...

**Comment by JeroenDeDauw** [comment]
I've acquired the credentials. Going to sleep now though. Will get the new VPS first thing tomorrow.

**Comment by kriegfrj** [comment]
Just to mention: Google prefers the https version of a page if it is available in both secure and non-secure. I noticed this every time I search for something SMW-related in Google and follow one of the links.

> * Someone figures out how this SSL cert stuff actually works and makes everything fluffy again

I've got a bit of experience in setting up SSL servers in production environments with Apache; I'm happy to give some pointers. See https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html for a good starter, and more detailed documentation here: https://httpd.apache.org/docs/2.4/mod/mod_ssl.html. Hosting a single website on a single VPS is probably the easiest imaginable scenario for an SSL setup so it shouldn't be too hard (gets a bit more complicated if there are multiple IPs or multiple virtual hosts involved).

The trickiest parts that I can forsee:

1. Getting the permissions correct on the key files. Private key should have permissions 600 or 400, and public key can be more permissive (eg, 644).

2. You have two domains - `semantic-mediawiki.org` and `www.semantic-mediawiki.org`. It is possible to get wildcard certificates (not sure if Let's Encrypt supports them), eg `*.semantic-mediawiki.org`, however this will only match domains that have that third subdomain specified and it won't match the bare `semantic-mediawiki.org`. As far as I know, it's not possible to get one keypair that will cover both domains - if you want to keep both domains up-and-running and SSL-compliant, you will need to get a keypair for each and configure two separate named-based-virtual-hosts (one for each domain), each with its own `SSLCertificateFile` and `SSLKeyFile` settings. Then it will probably be best if one is redirected to the other.

3. Because you have basically the same website on HTTP and on HTTPS, the easiest way to configure it is to put all of the configuration into an "include" config file - eg, `/etc/httpd/conf.d/semantic-mw.inc` - and then have a wrapper `/etc/httpd/conf.d/semantic-mw.conf` around it. Putting this together with 2, you'll end up with a file looking something like the one below.

4. The Let's Encrypt intermediate key's certificate will need to be included in the public key chain (ie, the file that is passed in using the `SSLCertificateFile` directive). I've not used https://letsencrypt.org before, so I'm not sure if the public key it issues will come with this cert file already attached - it should be obvious if it is because you will be able to see two "begin/end certificates" when you look at the PEM version of the public key in a text editor/viewer. If it is not already included, you will need to concatenate it manually (you can download it from here: https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem). (I think you can do the same with DER format, which is basically the same but binary-encoded instead of base-64 encoded, but I've never worked with DER format before.)

5. Testing: in addition to using your browser, openssl has some useful command line tools for verifying that you've correctly configured your server. In particular, use `openssl s_client -connect <ip or hostname>:443 -verify` to do an SSL equivalent of a `telnet` to port 443 (and also verify the certificate chain in the process) - it will show you if there were any certificate errors during the verification process.

````
# www.semantic-mediawiki.org, http
<VirtualHost *:80>
    ServerName www.semantic-mediawiki.org
    Include semantic-mw.conf
</VirtualHost>

# www.semantic-mediawiki.org, https
<VirtualHost *:443>
    ServerName www.semantic-mediawiki.org
    SSLEngine on
    SSLCertificateFile "/path/to/www.semantic-mediawiki.org.cert"
    SSLCertificateKeyFile "/path/to/www.semantic-mediawiki.org.key"

    Include semantic-mw.conf
</VirtualHost>

# semantic-mediawiki.org, http - redirect to www
<VirtualHost *:80>
    ServerName semantic-mediawiki.org
    RewriteEngine On
    RewriteRule (.*) http://www.semantic-mediawiki.org/$1 [R=permanent]
</VirtualHost>

# semantic-mediawiki.org, https - redirect to www
<VirtualHost *:443>
    ServerName www.semantic-mediawiki.org
    SSLEngine on
    SSLCertificateFile "/path/to/semantic-mediawiki.org.cert"
    SSLCertificateKeyFile "/path/to/semantic-mediawiki.org.key"
    RewriteEngine On
    RewriteRule (.*) https://www.semantic-mediawiki.org/$1 [R=permanent]
</VirtualHost>
````

Hope this helps! Look forward to having https://www.semanticmedia-wiki.org working properly again soon! I'm happy to help when I can if there are any questions.

**Comment by JeroenDeDauw** [comment]
Thanks a lot @kriegfrj! I was thinking of changing the old behaviour of the site and have http redirect to https.

We've just got our new VPS now. Bear with us a little longer.

**Comment by kriegfrj** [comment]
You're welcome @JeroenDeDauw, glad I could help.

Errata on my skeleton `semantic-mw.conf` file: the two `Include` directives should have been `Include semantic-mw.inc`, *not * `Include semantic-mw.conf` - otherwise you'd end up having the file include itself! :smile:

Redirecting the http site to https (as you suggested) is also a good idea (probably better than what I laid out above), and simpler to implement. No need for the `Include` approach in this scenario - just put all of the MW config directives into the main `<VirtualHost *:443>` section for the canonical https domain. In that case you could also merge the two plain-http `<VirtualHost *:80>` directives into a single directive as shown below. I think it's a good idea to force https because it will help protect users against man-in-the-middle attackers trying to steal user credentials.

All the best trying to get it up-and-running!

````
<VirtualHost *:80>
    ServerName www.semantic-mediawiki.org
    ServerAlias semantic-mediawiki.org
    RewriteEngine On
    RewriteRule ^(.*)$ https://www.semantic-mediawiki.org/$1 [R=permanent]
</VirtualHost>
````

You might also need to give some thought to what you do when someone passes an invalid host name. This normally gets caught be the default vhost - just check that the default vhost doesn't expose any files to the internet. You can test this using `telnet` and hand-crafting a HTTP request with a spoofed Host header, or else by spoofing a domain to the VPS's public IP address in your `/etc/hosts` file and using your browser.

**Comment by kghbln** [comment]
Thanks for all the comments and information! Much apprechiated! I have just set up the VituralHost for the new site and it tests with an A-Grade on SSLLabs. Can try to do an A+ later on. After the domain points to the new server I will close this one.

**Comment by kghbln** [comment]
Finally the wiki is on the new server. The [SSL Server test](https://www.semantic-mediawiki.org/w/images/b/b6/QualisSSL_server_test_www.semantic-mediawiki.org.pdf) now results in an A+ (forgot configuring HSTS before)

**Comment by Matthias84** [comment]
Thanks @all for fixing that ticket :-)

**Comment by JeroenDeDauw** [comment]
Thanks for much for the work @kghbln!

![fluff](https://cloud.githubusercontent.com/assets/146040/11915858/7470ccb6-a6b9-11e5-840d-c393d8324fd7.jpeg)

**Comment by jongfeli** [comment]
@kghbln, the new server (VPS) is "snappy", consulting the documentation is a joy... well it has always been but now it is faster. Thanks to all and have a nice Christmas and happy new year.
