### ISSUE TITLE
sorting of Text property content starting with 0

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1284]
see http://semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2015-11-25

```
{{#subobject:
|indexNo=001
}}
{{#subobject:
|indexNo=002
}}
{{#subobject:
|indexNo=003
}}
{{#subobject:
|indexNo=004
}}
{{#subobject:
|indexNo=005
}}
{{#ask:[[indexNo::+]]
|?indexNo
|order=indexNo
}}
```

the sorting should IMHO be 001,002,003,004,005 in fact the behaviour is strange. Initially the result seems to be unsorted but the sorted buttons in the table work as expected.

**Comment by Contrafibularity** [comment]
You made a slight mistake there: you appear to have confused the <tt>order</tt> parameter (ascending or descending) with <tt>sort</tt>. Change <tt>order</tt> to <tt>sort</tt> and you'll find that everything is in order.

**Comment by kghbln** [comment]
I guess we are cool here. Please use [sandbox](http://sandbox.semantic-mediawiki.org/wiki/Main_Page) in the future to make sure we are talking master. Thanks.

**Comment by WolfgangFahl** [comment]
I think this is much too confusing
SQL Syntax is:

SELECT name, birth FROM pet ORDER BY birth DESC;

so people going to SMW will get all confused - there should IMHO  be a warning if the ORDER parameter is not set correctly and a hint that SMW deliberately decided to have a confusing choice of the ORDER and SORT keywords.

**Comment by mwjames** [comment]
Why did we reopen this one? It is not an issue because the documentation is clear about how to use order/sort.

If it is a feature request (because the description reads otherwise) then a clear description of what is expected in comparison the current behaviour is required and also as to why it should be changed (the argument that because SQL handles it differently is a weak argument).

> I think this is much too confusing
SQL Syntax is:
SELECT name, birth FROM pet ORDER BY birth DESC;

SQL is SQL, #ask is #ask, not all users have a programming background which means SQL cannot be used as comparison device.

> so people going to SMW will get all confused - there should IMHO be a warning if the ORDER parameter is not set correctly and a hint that SMW deliberately decided to have a confusing choice of the ORDER and SORT keywords.

As far as the documentation goes, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1284#issuecomment-159720664 .

I don't know about "confusing choice of" but for the curious mind who would like to tackle this issue (it is not going to be me), a look at the `QueryProcessor` [0] can give some insights.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_QueryProcessor.php#L152-L219

**Comment by WolfgangFahl** [comment]
if there is an order but no sort this should IMHO be flagged as an invalid query.

**Comment by mwjames** [comment]
> if there is an order but no sort this should IMHO be flagged as an invalid query.

No, there is a standard behaviour specified for when the sort is empty (which is to use the entity, not the property).

>  It is not an issue because the documentation is clear about how to use order/sort.

Already explained.

**Comment by WolfgangFahl** [comment]
The example still should IMHO lead to an error message According to https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/Printout_sorting_order there are only three valid values:

1.  asc
2. desc
3. rand
 
So order=indexNo is syntactically incorrect and if an error would be displayed this would help against the confusion what was the reason for this issue in the first place.
