### ISSUE TITLE
rebuildData.php throws MWException from line 640 in SemanticData.php for "Data for a subobject of Test cannot be added ..."

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#1342]
MediaWiki 1.25.5
Semantic MediaWiki 2.2.3
PHP	5.4.40
MySQL	5.6.19-log

```
[87501c0b] [no req]   MWException from line 640 of /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/SemanticData.php: Data for a subobject of Test cannot be added to EADev_Ops:Test.
Backtrace:
#0 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/SemanticData.php(326): SMW\SemanticData->addSubSemanticData(SMWContainerSemanticData)
#1 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(215): SMW\SemanticData->addPropertyObjectValue(SMW\DIProperty, SMWDIContainer)
#2 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(195): SMW\AskParserFunction->createQueryProfile(SMWQuery, string, integer)
#3 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(133): SMW\AskParserFunction->doFetchResultsForRawParameters(array)
#4 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/parserhooks/ShowParserFunction.php(67): SMW\AskParserFunction->parse(array)
#5 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): SMW\ShowParserFunction->parse(array)
#6 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string)
#7 /app/mediawiki/mw/includes/parser/Parser.php(3771): call_user_func_array(Closure, array)
#8 /app/mediawiki/mw/includes/parser/Parser.php(3505): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#9 /app/mediawiki/mw/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#10 /app/mediawiki/mw/includes/parser/Parser.php(3422): PPFrame_DOM->expand(PPNode_DOM)
#11 /app/mediawiki/mw/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#12 /app/mediawiki/mw/includes/parser/Parser.php(3647): PPFrame_DOM->expand(PPNode_DOM)
#13 /app/mediawiki/mw/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPFrame_DOM)
#14 /app/mediawiki/mw/includes/parser/Parser.php(3322): PPFrame_DOM->expand(PPNode_DOM, integer)
#15 /app/mediawiki/mw/includes/parser/Parser.php(1231): Parser->replaceVariables(string)
#16 /app/mediawiki/mw/includes/parser/Parser.php(434): Parser->internalParse(string)
#17 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/ContentParser.php(202): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#18 /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/ContentParser.php(147): SMW\ContentParser->fetchFromParser()
#19 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(136): SMW\ContentParser->parse()
#20 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(119): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#21 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(88): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#22 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#23 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#24 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#25 /app/mediawiki/mw/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#26 /app/mediawiki/mw/extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#27 /app/mediawiki/mw/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#28 /app/mediawiki/mw/extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#29 {main}
```

**Comment by mwjames** [comment]
> [87501c0b] [no req] MWException from line 640 of /app/mediawiki/mw/extensions/SemanticMediaWiki/includes/SemanticData.php: Data for a subobject of Test cannot be added to EADev_Ops:Test.

I have an idea what is causing this (record in subobject or similar things) but above doesn't help much in analysing the issue because with no information about ` EADev_Ops:Test` it remains a conjecture.

If this is about record/subobject constellation then 2.4-master should be tested first (#1275, #1285) as some improvements are available for this use case.

**Comment by plegault3397** [comment]
I had a namespace incorrectly defined in my test environment EADev_Ops:Test. Test was somthing I was testing with it. I recreated the Database from my production system and the error is gone. rebuildData completes without the issue. I have a lot of pages using multiple subobject and they are not showing up now, 
This currently working on my production server running 
MediaWiki	1.25.3
Semantic MediaWiki	2.2.2
PHP	5.4.40 (apache2handler)
MySQL	5.6.19-log

**Comment by mwjames** [comment]
> I had a namespace incorrectly defined in my test environment EADev_Ops:Test. Test was somthing I was testing with it.

It would help if you could recreate your example on [0] in order to see what constellation caused the exception (currently I'm not sure I fully understand the circumstances) so we can provide a more meaningful message in future.

>  I have a lot of pages using multiple subobject and they are not showing up now, 

As long as I know that our tests pass (especially those in [1, 2]) my confidence is high that nothing is out-of sync with the SMW-core side and something else is missing in your setup (unless I'm proven wrong).

[0] http://sandbox.semantic-mediawiki.org/wiki/Main_Page
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/ByJsonScript

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#running-tests

**Comment by plegault3397** [comment]
Is there something wrong with my sparql query?
in smw release 2.2.2 this works
        PREFIX property:<http://example.com/index.php/Special:URIResolver/Property-3A>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
        SELECT ?name ?technology_name ?support_status ?start_date ?end_date ?sort_order
        WHERE
        {
            ?s property:Has_Name ?name .
            ?s property:Has_subobject-23aux ?subobject .
            ?subobject property:Technology_Name ?technology_name .
            ?subobject property:Has_Support_Status ?support_status .
            ?subobject property:Has_Start_Date ?start_date .
            OPTIONAL {
                ?subobject property:Has_End_Date ?end_date .
            }

        }

in SMW version 2.3 it is not working.

**Comment by mwjames** [comment]
> ?s property:Has_subobject-23aux ?subobject .

This is because of `aux`, I remember that I replied in Nov to the same problem on the mailing-list [0]. 

The `aux` parameter is no longer necessary for `Has_subobject` (and we only start to use `aux` where it is actual required) but if you are on 2.* and you don't want to break backwards compatibility, you can set `$GLOBALS['smwgExportBCAuxiliaryUse'] = true;` as noted in [1, 2].

[0] http://wikimedia.7.x6.nabble.com/Semantic-MediaWiki-2-3-tp5055324p5055343.html
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-2.3.0.md#highlight-improved-sparqlstore-support
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.settings.php#L903-L919

**Comment by plegault3397** [comment]
I remember this reply and could not find the link
I will update my code to remove the aux

**Comment by mwjames** [comment]
I'm still curious about "I had a namespace incorrectly defined in my test environment EADev_Ops:Test. Test was somthing I was testing with it." https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1342#issuecomment-168361431 to avoid a situation where in future we need to spent time just to figure out the cause.

**Comment by plegault3397** [comment]
I created a namespace like below and accidentally added an extra _

define("NS_EADev_Ops", 3000);
define("NS_EADev_Ops_TALK", 3001);

$wgExtraNamespaces[NS_EADev_Ops] = "EADev__Ops";
$wgExtraNamespaces[NS_EADev_Ops_TALK] = "EADev_Ops_TALK";   // underscore required

I moved a test page to that namespace before I realized the mistake, once I fixed the mistake I lost track of the page I moved there.
