### ISSUE TITLE
Provide support for extension.json?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1367]
I do not champion the use of `extension.json` [0] and I personally will not dedicate any time in supporting it. I'm not opposed to a PR as long as it does **not**
- interfere with our current development practice
- break our tests
- increase maintenance work for a developer
- increase the infrastructural maintenance burden (e.g. test setup, Travis etc.)

In case someone, intends to provide a patch to add  `extension.json` support the following elements are expected to be manage by PHP (and not by  `extension.json`) as those are individually tested.
-  Hooks
-  autoloading
-  SpecialPages, Actions, JobClasses, APIModules

PS: My position on this extends to each repository found in https://github.com/SemanticMediaWiki.

[0] https://www.semantic-mediawiki.org/wiki/Dependencies,_Composer,_and_more

**Comment by JeroenDeDauw** [comment]
I think it'd be great if someone volunteered to adding support for this thing, creating the relevant documentation for it on wiki, and maintain both. Such a contribution would be very welcome.

This is talking about autoloading via extension.json. Personally I think defining hooks in a custom on-PHP format is big fallacy (which was pointed out on the extension.json RFC and not replied to at all).

I can understand James complete lack of enthusiasm towards doing this though, and share it to a good extend.

**Comment by mwjames** [comment]
@s7eph4n did a nice job with the `extension.json` conversion in `SematicGlossary` (aka SG) where autoloading remains the domain of Composer via PSR-4, hooks are under the control of the extension, and tests do work as before without any changes. 

Yet, the problem lies behind that in how to manage its dependencies. SG relies on Lingo (it also relies on SMW but that's another story) and in order to ensure that nothing falls through the cracks, SG somehow has to ensure Lingo is available before SG is loaded (where Stephan came up with a neat hack).

```
	// must NOT use ExtensionRegistry::getInstance() to avoid recursion!
	$registry = new ExtensionRegistry();
	$registry->load( $GLOBALS[ 'wgExtensionDirectory' ] . '/Lingo/extension.json' );
```

Imaging that each SMW related extension has to add one or more of those lines before the invoker.

Of course, right now we check on `SMW_VERSION` in some of the extensions but this is just a constant which leaves knowledge about `extension.json` or a directory where some of its dependencies are placed (e.g. `$GLOBALS[ 'wgExtensionDirectory' ] . '/Lingo`) invisible and unnecessary for the requester to know about it.
 
In a hypothetical case where SMW would use `extension.json`, the above would have to be extended and added to all extensions that depend on it and hopefully doesn't create any conflicts such as recursions or race conditions.

This by itself is mimicking Composer in small by explicitly declaring what dependencies need to be loaded with the difference that it is not bound to any version check leaving this to fail when users are mixing versions or different installations.

```
	$registry = new ExtensionRegistry();
	$registry->load( $GLOBALS[ 'wgExtensionDirectory' ] . '/Lingo/extension.json' );
	$registry->load( $GLOBALS[ 'wgExtensionDirectory' ] . '/SemanticMediaWiki/extension.json' );
```

Now, what happens when extension A and extension B both require the same dependencies (as above) but are loaded at different times in LocalSettings? Would that load a required extension each time one of the `wfLoadExtension` is invoked?

```
	...
	wfLoadExtension( 'A' )
	...
	wfLoadExtension( 'B' )
	...
```

An argument that one should just add `wfLoadExtension( 'beingARequiredExtensionForAB' )` before any of the other extension are declared would be ludicrous. The reason to declare dependencies is the knowledge that certain requirements are in need to be fulfilled before a dependent software can do what is expected of it therefore one can not rely on conventions or goodwill of a user to take the role of a dependency manager (that's the job of the software).

After the SG conversion it is clear to me that `extension.json` does not lend itself to manage dependencies let alone ensures that those are loaded and queued correctly.

@cicalese My comments to https://phabricator.wikimedia.org/T88596.

@kghbln @JeroenDeDauw FYI

[0] https://github.com/SemanticMediaWiki/SemanticGlossary/blob/master/SemanticGlossary.php#L19-L20

**Comment by JeroenDeDauw** [comment]
Sounds reasonable. I agree that all of these are bad, esp the later:

* `$registry = new ExtensionRegistry()` - hack might work now, but who knows when some MW dev sees it and decides its bad and should be prevented
* Having extensions bind to the paths of their direct dependencies
* Having extensions need to specify indirect dependencies in any way

**Comment by s7eph4n** [comment]
The first might happen. The second is reality right now (the ExtensionRegistry works on paths, not extension names). The third thankfully not: Extensions only activate their direct dependencies, which activate their dependencies, which activate their dependencies...

Some thoughts, maybe not yet fully thought through...

The idea of using an extension.json to declare extension properties is a good one, in my opinion. It opens the way to finally having an on-wiki extension manager, that should enable on-wiki installation, activation, configuration, de-installation. (That this extension.json includes stuff like hooks is less fortunate. I do not buy the argument that this allows avoiding parsing of malicious PHP code or other crude arguments that have been brought up.)

As I see it, extension.json and composer do not at all exclude each other, on the contrary, I think they nicely complement each other.

In my ideal system Composer would be responsible for **installing** extensions, including resolution of version constraints.

The ExtensionRegistry would be responsible for **enabling** extensions. In this ideal world the ExtensionRegistry would not have to check versions at all, it would not even have to check the availability of the extensions, because Composer would have taken care of that. All it had to make sure was, that extensions were activated in the correct order, which should be an easy task.
Of course, as long as Composer is not used for every extension (i.e. forever) the ExtensionRegistry should probably do a sanity check on the versions and in case of failure bail out (and leave it to the admin to solve the mess they created by installing incompatible extensions). This check means duplicate storing of dependencies in composer.json and extension.json (e.g. by extending the `requires` field currently only used for the MediaWiki version), which is error prone, but may be made safer by employing a dedicated CI test that compares the two files.

In this perfect world extensions would also not have to check that all dependencies are there (no more `if ( ! defined( 'SMW_VERSION' ) ) {...}`). Ok, except to selectively use features. For these cases the respective version information should be asked from the ExtensionRegistry, not by taking some constant from the global scope (SMW_VERSION be gone :) ).

Unfortunately, as it is right now the ExtensionRegistry does not resolve dependencies at all and extensions are left to activate their dependencies on their own (as done by SG for Lingo). All that happens when `wfLoadExtension` is called is that the requested extension is registered in an array for loading and at some later point this array is processed. This is done in a rather knee-jerk way that is not re-entrance safe and does not allow adding something to the queue once the processing is running [1]. The only good thing about the implementation is, that the callback is called before the settings from extension.json are applied to the global context, i.e. any extension loaded by another from the callback will have its settings applied first, so the correct order is retained. Should more than one extension depend on the same dependency better be prepared for chaos.

[1] (What happens is that the array is processed in a `foreach` loop and at the end it is set to `[]`.
So, if you use `ExtensionRegistry::queue` while the queue is processed, the newly queued extension is first ignored in the loop and then just dropped when the array is flushed.
If you skip the queue and just call `ExtensionRegistry::load` that is no good either, because for some reason somebody thought it clever in this method to first process the queue before actually loading the requested extension. Remember that the queue is *first* processed and *then* flushed? Calling `ExtensionRegistry::load` while the queue is processed will start a new processing run of the original, not yet flushed queue. Yay recursion.)

I would really like to work on that. The sad state of things is unfortunately that as long as you are not a core dev you will be either stalled forever or simply ignored . (As I am experiencing right now again.)

**Comment by JanZerebecki** [comment]
> I would really like to work on that.

That would be welcome, as people working on this are lacking. A good starting point is probably https://phabricator.wikimedia.org/T88596 .

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/30 has a show case on a possible conversion and outlines requirements as to when I would be inclined to merge it.

Furthermore:

- Autoloading happens using PSR-4
- A new major version number (1.x.x -> 2.x.x) is required
- Active class references that are only allowed:

```
+	"callback": "SemanticFormsSelect::initExtension",
 +	"ExtensionFunctions": [
 +		"SemanticFormsSelect::onExtensionFunction"
 +	],
```

@s7eph4n @cicalese I cleaned most extensions in this repo to follow the same pattern (SignUp and SRF are missing). If you want to see  more widely support for `extension.json` then I expect those requirements to be solved first.

**Comment by cicalese** [comment]
MediaWiki extension registration will support PSR-4 autoloading in MediaWiki 1.31. This capability is now available in master. Documentation and an example are linked from https://phabricator.wikimedia.org/T99865. In addition, MediaWiki extension management will very likely be revisited in the near future to add additional capabilities (https://phabricator.wikimedia.org/T88596). I would still very much like to see Semantic MediaWiki and its siblings support standard MediaWiki extension registration. Are there any remaining roadblocks to this that could reasonably be addressed?

**Comment by mwjames** [comment]
> (https://phabricator.wikimedia.org/T88596). I would still very much like to
> see Semantic MediaWiki and its siblings support standard MediaWiki extension
> registration. Are there any remaining roadblocks to this that could
> reasonably be addressed?

Please find my comments on this topic in [0, 1, 2] (I hope you
understand that I will not repeat myself here).

> registration. Are there any remaining roadblocks to this that could
> reasonably be addressed?

See [3].

[0] https://phabricator.wikimedia.org/T61872#3681772
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2813#issuecomment-349003952
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1732
[3] https://phabricator.wikimedia.org/T152263

Cheers

**Comment by cicalese** [comment]
Thank you for the links. I had searched unsuccessfully for the most recent conversation on this topic.
