### ISSUE TITLE
ParamProcessor / Extension:Validator dependency?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1465]
`SMW_QueryProcessor.php` makes direct reference to `use ParamProcessor\Param` but I'm unable to find the dependency in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/composer.json. Where does it come from? 

On the topic of dependency:

https://www.mediawiki.org/wiki/Topic:T0lf8da8mf3tf398 asks:

> SMW 1.9 and later don't need Validator. Seemingly, SMW cannot work with the existence of a n explicit invocation of Validator.
What other dependencies stated here need review?

https://www.mediawiki.org/wiki/Topic:T0lfi97opcjqk64b asks:

> Recent versions of SMW have disposed of the dependency on Extension:Validator, and explicit declarations thereof will make SMW non-functional.
> Is there a way to solve this conflict when both Parser Fun and SMW are required to co-exist in a wiki?

@JeroenDeDauw ?

**Comment by JeroenDeDauw** [comment]
Right, SMWs `composer.json` should specify param-processor. Right now it is getting pulled in because parser-hooks depends on it.

Installing Validator, which also depends on param-processor, should not break anything. This is easy to test. I'm guessing the person asking stuff on mw.org messed up their install somehow, using incompatible versions of stuff. Parser Fun does not use Composer after all.
