### ISSUE TITLE
Resources fail to load with non-default extensions setup (e.g. symlinks)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1466]
Andreas Plank (talkcontribs) writes [0]:

> I configured a shared wiki setup with different extension features per wiki. In SMW 2.3.1 when debug=true in the URL some resources issue an error not to be loaded. With MW 1.25+ it is considered to set up a different extension directory (Manual:$wgExtensionDirectory) but it is not taken into account for SMW resources. I checked out and see why: SemanticMediaWiki/res/Resources.php assumes folder extensions to be there but allowing a different $wgExtensionDirectory this assumption is proven wrong. So if I add debug=true to the URL I get http://offene-naturfuehrer.de/w/extensions//usr/share/mediawiki26/extensions-rich-features/SemanticMediaWiki/res/smw/util/ext.smw.util.tooltip.js it becomes 404 and does not get loaded. Is there any fix I can do, LocalSettings or so? See also https://phabricator.wikimedia.org/T130520

https://www.mediawiki.org/wiki/Topic:T0lgzm1dg4i11h9w

**Comment by mwjames** [comment]
@kghbln @jaideraf @Contrafibularity Can someone try to sort out the issue?

**Comment by kghbln** [comment]
> I configured a shared wiki setup with different extension features per wiki.

As I read it the desired setup is as follows:

If "WIKI-A" then ``$wgExtensionDirectory = "/path/to/extensions/for/wiki-a/using/mw125"``
If "WIKI-B" then ``$wgExtensionDirectory = "/path/to/extensions/for/wiki-b/using/mw126"``

Is this what you read from the description, too?

**Comment by mwjames** [comment]
> Is this what you read from the description, too?

This not really my field of expertise when it comes to "a shared wiki setup with different extension features per wiki" and "considered to set up a different extension directory (Manual:$wgExtensionDirectory)" so I'm not sure what the issue is and/or what is expected of it.

**Comment by infinite-dao** [comment]
> As I read it the desired setup is as follows:
> 
> If "WIKI-A" then $wgExtensionDirectory = "/path/to/extensions/for/wiki-a/using/mw125";
> If "WIKI-B" then $wgExtensionDirectory = "/path/to/extensions/for/wiki-b/using/mw126";

The problem is that the shared wikis I have set up uses symlinks as  ./extensions links to `/usr/share/mediawiki26/extensions-rich-features`, the PHP `__DIR__` then resolves that to the real path which leads to troubles. I guess most programmers forget about the case of setting `$wgExtensionDirectory` or `$IP` differently. Setting  $wgExtensionDirectory helped so far for setting up the shared wikis, but it fails in case of SMW and it seems that I cannot reset the wrong resource path via LocalSettings. By modifying `$wgResourceModules` in LocalSettings.php I did not succeed.

**Comment by mwjames** [comment]
[0] is where the path is set and unless someone comes up with an indication as to what needs to be changed I'm rather unable to help here.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/Resources.php#L12-L18

**Comment by infinite-dao** [comment]
the remoteExtPath is not set up correctly in Resources.php https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/res/Resources.php#L16 and the cause is that https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/res/Resources.php#L12 assumes a folder "extensions". I think one possible solution can be like this:
`# __DIR__ always ends without trailing slash /`
`# $pathParts=explode(DIRECTORY_SEPARATOR, "/usr/share/mediawiki26/extensions-rich-features/SemanticMediaWiki/res"); `
`$pathParts=explode(DIRECTORY_SEPARATOR, __DIR__);`
`# extract and join only last 2 array elements to /SemanticMediaWiki/res/ or whatever is needed
echo "/" . join("/", array_slice($pathParts, -2)) . "/";`

**Comment by mwjames** [comment]
> the remoteExtPath is not set up correctly in Resources.php

Since we do not really care about the extension folder or `wgExtensionDirectory` and `remoteExtPath` contains a relative [0], would the following work?

```
// Make sure to work on both Win and Ux
$pathParts = explode( '/', str_replace( DIRECTORY_SEPARATOR, '/', __DIR__ ) );

$moduleTemplate = array(
	'localBasePath' => __DIR__,
	'remoteExtPath' => implode( '/', array_slice( $pathParts, -2 ) ),
	'group' => 'ext.smw'
);
```

This can __easily__ break the setup therefore it would need some extensive manually testing (nothing you can really test via Travis) as it has been shown in the past to be a pain stick.

[0] https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#Registering

**Comment by infinite-dao** [comment]
I made a preliminary patch for our Wikifarm based on your code and it works like a charm for me or us :-) 
http://biowikifarm.net/meta/File:Resources-php.SMW_2.3.1_remoteExtPath.patch

**Comment by mwjames** [comment]
Proposed change has been added with #1476.
