### ISSUE TITLE
Blog about malformed RDF output

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#1520]
Steve Baskauf recently tested SMW's RDF output, investigating the claim that "all data created within SMW can easily be published via the Semantic Web, allowing other systems to use this data seamlessly". He wrote about it on his blog here: 

http://baskauf.blogspot.nl/2016/03/semantic-mediawiki-and-termstdwgorg.html (6 March)

This may be of interest to you.

**Comment by JeroenDeDauw** [comment]
@mkroetzsch I suspect this is of interest to you

**Comment by mkroetzsch** [comment]
Disclaimer: I have not read the details, just skimmed it and read the summary.

* The RDF output is quite old and was never used for any application I know of. So it is likely that it could be improved. But I would not do this just for the sake of it. Maybe some other ontologies could also be used, but in general there are often too many rather than too few, so we won't support all of them either way. I think we also use many terms not supported by any other ontology.
* The property declarations need to be included for making the output valid OWL. This is not the same as including the whole ontology; we just include the declarations required by the standard.
* It seems odd to discuss the number of triples when they are below a few 100. I don't see a reason why people should care about such tiny numbers either way.

**Comment by mwjames** [comment]
> The RDF output is quite old and was never used for any application I know of. So it is likely that it could be improved.

Well, the triplestores are direct consumers of the RDF export which works sufficient enough but apart from that I have no knowledge of any other explicit consumers.

In the past some users have reported an attempt to use [Protégé](http://protege.stanford.edu/) with unsatisfactory results [0, 1] and it is not clear whether anyone has ever tried to use a reasoner \[2, 3] (but I'm guessing since Protégé has issues the reasoner would have them as well).

Unless there is some strong renewed (and serious) interest to make this work with external tools., I cannot find an argument that would warrant an investment in improving the situation especially in the light of everybody doing WD these days. 

[0] http://wikimedia.7.x6.nabble.com/RDF-export-issues-td577272.html
[1] http://wikimedia.7.x6.nabble.com/Newbie-question-How-to-refactoring-ontology-in-SMW-td5029846.html
[2] https://www.w3.org/2001/sw/wiki/OWL/Implementations
[3] http://owl.cs.manchester.ac.uk/tools/list-of-reasoners/

> The property declarations need to be included for making the output valid OWL. This is not the same as including the whole ontology; we just include the declarations required by the standard.

Exactly.

As far as I remember, if you do a RDF dump you'll get them only once but using the RDF output view (as a single subject perspective) those are included on each view to complete the statements.

> It seems odd to discuss the number of triples when they are below a few 100. I don't see a reason why people should care about such tiny numbers either way.

:+1:

**Comment by mwjames** [comment]
Thanks everybody for the discussion. I moved this to [0] and with no an apparent action assignable, I'm closing this in light of above comments.

Feel free, to extend this discussion.

[0] https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_and_RDF
