### ISSUE TITLE
load.php now enforces "no sessions" constraint

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#1555]
There is a yet another breakage from a MediaWiki core change.

### Setup and configuration

- SMW version: 2.3.1
- MW version: 	1.28.0-alpha

### Issue

Please see https://phabricator.wikimedia.org/T134562 and https://lists.wikimedia.org/pipermail/wikitech-l/2016-May/085520.html for details.

**Comment by kghbln** [comment]
Thanks for reporting and notifying.

**Comment by mwjames** [comment]
> Thanks for reporting and notifying.

Yes, thanks but with comments like "... we anticipate that this change won't cause any issues for Wikimedia wikis. ... Third-party wikis may have to update their extensions." [0] do you think that users or developers feel compelled to actually do something.

Just because WMF has resources (employees, hours, money, tests etc.) to introduce all sorts of breakages doesn't mean non-WMF developers are elastic like a rubber band to make a move whenever the overlord thinks it is time to stir up the crowd and have extension bees apply non-domain specific fixes.

9e76ce76ae8 provides a hack that hopefully fixes the log mess. Yet, I will not invest more time in finding a better solution since this issue has been caused by MW.

[0] https://lists.wikimedia.org/pipermail/wikitech-l/2016-May/085520.html

**Comment by Nikerabbit** [comment]
I commented along these lines in https://phabricator.wikimedia.org/T127233#2269563 – if it was done a bit differently there would have been more time to detect and fix this issue. On the other hand, as Tgr writes in https://phabricator.wikimedia.org/T134562#2269666 one could argue this was just unnoticed bug in SMW, but I don't see whether this actually affected any cached variables or not.

**Comment by kghbln** [comment]
> Thanks for reporting and notifying.

I believe we have to differentiate between the one who notifies about bad news and the ones who create the cause of bad news. I purposely did not comment further since there is no dissent to what you commented.

I also believe that Niklas has a fair bit of understanding for this and is not necessarily a friend of changes such as the one that has happened here to put it in mild words. As a matter of fact he is running a wiki on MW master together with third party software. That is what I consider brave.

`<rant>`
The underlying issue is, at least this is my impression, that there are people at WMF who deny the existence of third party software to MW and/or the possibility of third party wikis as such because knowledge sharing can only validly happen on wikis run by WMF. Additionally some of them do not even know how to edit a wiki and/or detest doing so which is probably even worse. I hope to be proven wrong.
`</rant>`

**Comment by mwjames** [comment]
> I also believe that Niklas has a fair bit of understanding for this and is not necessarily a friend of changes such as the one that has happened here to put it in mild words. As a matter of fact he is running a wiki on MW master together with third party software. That is what I consider brave.

Which I certainly acknowledge and surely find commendable. The whole problems starts with WMF employees making  statements like the one in [0] which more or less translates into "Well, WMF is working fine and I don't fucking care for the rest" attitude knowing that not everyone runs a WMF cluster.

**Comment by tgr** [comment]
WMF employees are paid with donor money and it's not their call (nor should it be) what that money is spent on. You can argue that supporting third-party MediaWiki code is directly beneficial to the Wikimedia  Foundation's mission (although there is not much point in having that argument in issue tracker threads because most of the people who would disagree with you don't read those in the first place), but short of that it doesn't seem any more fair to expect the WMF to spend resources on updating code it does not actually need than to expect third parties to spend time updating their code because of changes that probably do not benefit them; and at least one of the two has to happen.

To give a bit of background, there was a probable security vulnerability in MediaWiki ([T125283](https://phabricator.wikimedia.org/T125283)) which was too infrequent to positively identify the source, but session handling in load.php was one of the more credible explanations, so wanted to get rid of it as soon as possible. (It probably brings some marginal performance improvement as well.) The change was delayed until after the release branch cut to minimize inconvenience to third parties; not warning about it sooner was an oversight (although there isn't any good way to tell what will be affected short of using the wiki and watching whether it would break), and I apologize for that, but it's unrealistic to expect the WMF to not make such changes unless it can commit to updating all the extensions in existence.

**Comment by nemobis** [comment]
Tisza Gergő, 10/05/2016 16:04:
> WMF employees are paid with donor money and it's not their call (nor
> should it be) what that money is spent on.

You speak as if a donor petition or a WMF board of trustees resolution 
explicitly required you to break MediaWiki extensions.

> it's
> unrealistic to expect the WMF to not make such changes unless it can
> commit to updating all the extensions in existence.

Sure, but updating the 20 or so most popular extensions 
(https://wikiapiary.com/wiki/Extension:Extensions ) probably has higher 
returns (in userbase, developer base etc.) and less costs than what it 
costs to end up writing such issue tracker messages for not fixing your 
own breakages yourself.

**Comment by s7eph4n** [comment]
@tgr, the point is not so much that somebody expects WMF employees to fix extensions they do not use. (In fact if you ask me it would be great if they refrained from blanket applying patches that "can not possibly go wrong" without actually testing them to all extensions, as happened in the past)
The point here is that WMF again and again introduces breakages without caring one jot who might be affected. There are procedures on how to deprecate functionality but they seem to be applied only when convenient.
I will grant you that in this particular case there probably was an urgent issue. Then again it seems not to be urgent enough to put it into 1.27 or a security patch.

**Comment by mwjames** [comment]
> I apologize for that, but it's unrealistic to expect the WMF to not make such changes unless it can commit to updating all the extensions in existence.

This is not the first issue that I came across with the 1.27 release and as a volunteer that makes me sad and leaves me frustrated.

Some examples (off the top of my head) that appeared during the last six month:

- Someone changed the TitleMoveComplete execution signature which broke the invocation
- Suddenly all wikipage edits/updates run in deferred mode and broke all of our integration tests (making me spent 20+ hours to figure out a way around)
- The TransactionProfiler is polluting the log with messages no one really cares unless your are running WMF
- and now the "no sessions" constraint issue

All in all, I'm a bit in a dent when it comes to fixing things that have more or less nothing to do with the extension.

PS: Fixes sometimes may involve only a bit of work but nevertheless requires from a volunteer to install a new master, isolate the issue, and figure out a fix. In the end, any change has to pass our test suite (without changing the tests) which compared to other non-WMF extensions is rather extensive in scale and coverage therefore any minor issue can elevate itself into a real show stopper.

PSS: Just awaiting the next chaos with ResourceLoader/addModuleStyles changes.

**Comment by JeroenDeDauw** [comment]
I think it's important to recognize that there is an inherent conflict between framework authors and extension developers. And that in case of MediaWiki, this conflict is made quite noticeable due to MediaWiki being a big ball of mud with extensions binding to it heavily, and a good dose of xenophobia. I suspect spending effort on mitigating these is more effective than countering the problems they bring forth.

There are WMF employees that don't care about extensions. This is not surprising. In all but rare exceptions, you will have people that don't care and just come in to do a 9 to 5 job in large development organizations. Those who care about the WMF mission, yet not about extensions, are already well ahead of that crowd. One can argue about if WMF employees should care about extensions or not, however it seems to me you will always have some that do not. At the same time you have ones that do, so it's important to not reinforce the xenophobia and put everyone in the same bucket.

By no means do I intend to play down efforts being done by anyone here. I very much understand the frustration of extension developers, as it in part is what made me quit MediaWiki and extension development. Thank you to everyone who is doing the hard work to fix these breakages, or to prevent them in the future.

**Comment by hexmode** [comment]
Looks like this issue just appeared on the MW Support Desk.  Whee!

https://www.mediawiki.org/wiki/Topic:Tmrlqagno27nsun0
