### ISSUE TITLE
Invasion!

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1581]
Earlier today hostile aliens arrived in low Earth orbit. By infiltrating humanities communications, they quickly and correctly identified Semantic MediaWiki as our species most critical piece of infrastructure. Their actions where as swift as they where brutal. Firstly they took over @mwjames his account, and then used it to launch a massive denial of service attack.

![invazion](https://cloud.githubusercontent.com/assets/146040/15232672/303d4b26-18a3-11e6-8feb-eb89f831358c.png)

**Comment by gesinn-it** [comment]
@mwjames hey, what did you have for breakfast. You raise the bar for "commits/minute"...

:-)

**Comment by mwjames** [comment]
> Earlier today hostile aliens arrived in low Earth orbit. By infiltrating humanities communications, they quickly and correctly identified Semantic MediaWiki as our species

Can you imagine this guy knocked on my door earlier this morning and said either to improve Semantic MediaWiki (apparently they using it as KB software on their mother ship and hastily awaiting a new release since using the bare metal MediaWiki just sucks) or he would sent in some invasion troops to enslave the human race (the reason the didn't have done it yet is because they are proud users of SMW).

![image](https://cloud.githubusercontent.com/assets/1245473/15255322/a9db86b2-193b-11e6-9af7-a0435b7d3f64.png)

**Comment by kghbln** [comment]
Great that we survived the invasion by these rays of sunshine! :)
