### ISSUE TITLE
Leave SourceForge?

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#1609]
SourceForge has become a rather controversial provider of software downloads [0][1][2] and is now routinely blocked by e.g. uBlock [3] as well as at least one corporate firewall I know.

Would it make sense to leave SourceForge and use GitHub to distribute tar balls instead?

[0] http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/
[1] http://libregraphicsworld.org/blog/entry/anatomy-of-sourceforge-gimp-controversy
[2] http://www.ghacks.net/2015/06/15/popular-software-projects-leave-sourceforge/
[3] https://github.com/gorhill/uBlock/commit/c4e82357efaf18bac3f04900efb304f5a092ffe0

**Comment by JeroenDeDauw** [comment]
How would we do this on GitHub?

**Comment by mwjames** [comment]
> How would we do this on GitHub?

https://github.com/blog/1547-release-your-software

> SourceForge has become a rather controversial provider of software downloads

Well, we had to switch away from SF for Travis because of unreliability [0] but I didn't know it sparked that sort of controversy.

> Would it make sense to leave SourceForge and use GitHub to distribute tar balls instead?

Probably can not happen over night but the proposal has my endorsement.

It would be great if we could automate the build/deploy process when releasing a new version \[1, 2, 3, 4] (to avoid making zip's from hand).

[0] https://github.com/mwjames/travis-support
[1] https://docs.travis-ci.com/user/deployment/releases
[2] https://developer.github.com/v3/repos/releases/#upload-a-release-asset
[3] http://stackoverflow.com/questions/9577968/how-to-upload-files-on-github
[4] http://blog.wercker.com/2014/05/08/Deploying-assets-to-github-releases.html

**Comment by kghbln** [comment]
> Would it make sense to leave SourceForge and use GitHub to distribute tar balls instead?

Reading all of this it indeed makes sense to move away from SourceForge

**Comment by kghbln** [comment]
Just comes to my mind. It's not just the downloads but also the mailing lists which are over there. Wouldn't like to touch these.

**Comment by s7eph4n** [comment]
> How would we do this on GitHub?
In Principle it should be as easy as attaching a file to the release.

The list of files on GitHub is not as concise as the one on SourceForge, but it should work. I am more worried about the included download links with every release, that may mislead users. Have a look at a release for Semantic Glossary I just made: https://github.com/SemanticMediaWiki/SemanticGlossary/releases/tag/2.0.1

**Comment by JeroenDeDauw** [comment]
+1 from my side

**Comment by mwjames** [comment]
> I am more worried about the included download links with every release, that may mislead users. 

I tweak the obvious.

**Comment by mwjames** [comment]
smw@org has several SourceForge references those need to be changed.

https://www.semantic-mediawiki.org/w/index.php?search=SourceForge&title=Special%3ASearch&go=Go

**Comment by JeroenDeDauw** [comment]
Kinda sad to leave the list of releases since 2005. Still +1 tho. Fun fact: apparently 0.1 rel had 5 PHP files ;p

**Comment by mwjames** [comment]
> Fun fact: apparently 0.1 rel had 5 PHP files ;p

I think we can get their again (goes without saying no tests for such version) :-) but apparently other developers swear its the new hot-pot approach.

**Comment by kghbln** [comment]
> smw@org has several SourceForge references those need to be changed.

so these should now point to https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases?!

**Comment by mwjames** [comment]
> so these should now point to

I'd say during a transitional phase (at least for 2.4) having them posted in both places may avoid confusion and doesn't require an ad-hoc change on wiki.

**Comment by kghbln** [comment]
One thing that just comes to my mind. Just to make sure: Don't we need to somehow also include the autoloading stuff for the libraries stuff of MW itself for 1.25+ for file releases to work?

**Comment by JeroenDeDauw** [comment]
I suspect not. Though not 100% sure I understand you correctly.

**Comment by mwjames** [comment]
> autoloading stuff for the libraries stuff of MW itself for 1.25+ for file releases to work?

I'm also not sure what this means but I would think the process remains the same by running the build script and upload those files after a release via:

![image](https://cloud.githubusercontent.com/assets/1245473/15859432/6c658d44-2cc5-11e6-9523-0bb19f03b193.png)

**Comment by kghbln** [comment]
Let me put it in other words: I believe that MediaWiki 1.25+ is loading the required libraries via some file containing the autoload information created by composer which is located somewhere at vendor. So what happens if I move our tarball over to vendor which also contains autoload information for SMW. If this file has the same name, then I suspect a problem since we are overwriting core information, or is it a file with a different name. Basically the question is whether Composer creates mashup file for everything that is supposed to be loaded or do we have multiple files, e.g. one per library, extension etc. which do the loading. I the first case I expect issues in the latter I do not.

**Comment by JeroenDeDauw** [comment]
The vendor dir we create in the tarball is in SMW itself, so there will be no file conflicts with mwcore/vendor. Things can still go pear shaped if different versions of a library get loaded by both autoloaders, but this has been the case for a long time already.

**Comment by kghbln** [comment]
Ah right, thanks for bringing me back on track. Senior moments ...

**Comment by kghbln** [comment]
I believe this is done now. Still using the mailing lists though but this was not the issue after all.

**Comment by kghbln** [comment]
I have just updated [sourchfore here](https://sourceforge.net/projects/semediawiki/) and [there](https://sourceforge.net/projects/semediawiki/files/semediawiki/) to point to the [new location](https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases)
