### ISSUE TITLE
Illegal property key "" error during SMW rebuildData

### ISSUE THREAD

**Issue by lloonngg** [SemanticMediaWiki/SemanticMediaWiki#1690]
### Setup and configuration

- SMW version:  2.4.0-rc1 (ca64a56)
- MW version:  1.27.0-rc.0
- DB (MySQL etc.):  10.1.14-MariaDB-1~trusty
- SparqlStore:  BlazeGraph 2.1.0
- SemanticForms:  3.6 (75a2f62)

### Issue
I have set up a new stack to test SMW 2.4.0 with BlazeGraph 2.1.0 as a SparqlStore.  The build passed phpunit testing ([1583](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1583#event-702115484)).  I migrated over 185,000 pages from our older production MW 1.20.2+SMW 1.8.0.5 and initiated update.php from MW and rebuildData.php from SMW.  During the process I encountered the following error.  I have found a similar error online ([920](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/920)) but was wondering if this is a new one that may not have been seen or addressed before.  Unfortunately, my wiki is a private one running behind our firewall, and I will not be able to share a link to it.

Produces the following error:

```
....
(83/320 26%)    Page Property:Has_default_form
[8f056c4f55a916af8a0ce5be] [no req]   SMW\InvalidPropertyException from line 82 of /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: Illegal property key "".
Backtrace:
#0 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/export/SMW_Exporter.php(235): SMW\DIProperty->__construct(string)
#1 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/export/SMW_Exporter.php(161): SMWExporter::makeExportDataForSubject(SMW\DIWikiPage)
#2 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(220): SMWExporter::makeExportData(SMW\SemanticData)
#3 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(177): SMW\SPARQLStore\TurtleTriplesBuilder->prepareUpdateExpData(SMW\SemanticData)
#4 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(85): SMW\SPARQLStore\TurtleTriplesBuilder->serializeToTurtleRepresentation()
#5 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(156): SMW\SPARQLStore\TurtleTriplesBuilder->doBuild()
#6 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(208): SMW\SPARQLStore\TurtleTriplesBuilder->hasTriplesForUpdate()
#7 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(182): SMW\SPARQLStore\SPARQLStore->doSparqlFlatDataUpdate(SMW\SemanticData)
#8 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(230): SMW\SPARQLStore\SPARQLStore->doSparqlDataUpdate(SMW\SemanticData)
#9 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(248): SMW\SPARQLStore\SPARQLStore->doDataUpdate(SMW\SemanticData)
#10 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/StoreUpdater.php(186): SMW\Store->updateData(SMW\SemanticData)
#11 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/StoreUpdater.php(126): SMW\StoreUpdater->doRealUpdate()
#12 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/StoreUpdater.php(92): SMW\StoreUpdater->performUpdate()
#13 /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/ParserData.php(290): SMW\StoreUpdater->doUpdate()
#14 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(171): SMW\ParserData->updateStore()
#15 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(147): SMW\MediaWiki\Jobs\UpdateJob->updateStore(SMW\ParserData)
#16 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(118): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#17 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(87): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#18 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(56): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#19 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(162): SMW\MediaWiki\Jobs\UpdateJob->run()
#20 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(142): SMW\Maintenance\DistinctEntityDataRebuilder->doExecuteUpdateJobFor(Title)
#21 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(193): SMW\Maintenance\DistinctEntityDataRebuilder->doRebuild()
#22 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(230): SMW\Maintenance\DataRebuilder->doRebuildDistinctEntities()
#23 /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(167): SMW\Maintenance\DataRebuilder->doRebuildAll()
#24 /var/www/html/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(149): SMW\Maintenance\DataRebuilder->rebuild()
#25 /var/www/html/mediawiki/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#26 /var/www/html/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(197): require_once(string)
#27 {main}
```

**Comment by mwjames** [comment]
>  Page Property:Has_default_form
[8f056c4f55a916af8a0ce5be] [no req]   SMW\InvalidPropertyException from line 82 of /var/www/html/mediawiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: Illegal property key "".
Backtrace:

Do you use a never SF? Since a certain time SF doesn't use any properties so when the Exporter tries to match the internal key, it returns "" and [0] fails.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/export/SMW_Exporter.php#L234-L237

**Comment by lloonngg** [comment]
We upgraded from SF 2.7 to 3.6.  Is there a fix for this?

**Comment by kghbln** [comment]
What happens after you replaced all occurences of `[[Has_default_form::Name_of_Form]]` by SF's new syntax `{{#default_form:Name_of_Form}}`?

**Comment by mwjames** [comment]
> We upgraded from SF 2.7 to 3.6. Is there a fix for this?

This is a bit of a hot needle but could you try to change the following section in [0]:

```
@@ -148,10 +148,15 @@ class SMWExporter {
 		// property caused by a different user language)
 		if ( $subject->getNamespace() === SMW_NS_PROPERTY && $subject->getSubobjectName() === '' ) {
 			$subject = DIProperty::newFromUserLabel( $subject->getDBKey() )->getCanonicalDiWikiPage();
 		}
 
+		// #1690 Couldn't match a CanonicalDiWikiPage, so use the normal subject
+		if ( $subject->getDBKey() === '' ) {
+			$subject = $semdata->getSubject();
+		}
```


[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/c857b719fb0e4b2c8aac86b3e1511321dd1b33b7/includes/export/SMW_Exporter.php#L141-L168

**Comment by lloonngg** [comment]
I tried your suggestion to patch SMW_Exporter.php and it seems to work.

During SMW data rebuild, I ran into the curl issue [1306](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1306).  I set [$smwgSparqlRepositoryConnectorForcedHttpVersion](https://www.semantic-mediawiki.org/wiki/Help:$smwgSparqlRepositoryConnectorForcedHttpVersion) to true and still got the curl error.  In the end, upgrading to curl 7.36 seems to fix the curl error as suggested [here](https://github.com/jackalope/jackalope-jackrabbit/issues/89).

I have 185,000+ pages to rebuild.  Is there any way to run rebuildData.php with multiple threads?  Seems to be proceeding rather slowly and will take a while to complete.

**Comment by mwjames** [comment]
> I tried your suggestion to patch SMW_Exporter.php and it seems to work.

:+1: 

> I have 185,000+ pages to rebuild. Is there any way to run rebuildData.php with multiple threads? Seems to be proceeding rather slowly and will take a while to complete.

#927 contains a discussion about `runJobs` being able to use the `--proc` option in connection with the `ForkController` (which only works on Linux [0, 1]). Since I develop on Windows, I have no way of testing this option or provide a possible extension to the `rebuildData.php` script.

[0] https://github.com/wikimedia/mediawiki/blob/e7a9ef0f9f25bf0ffc804ceb17382246316828b3/includes/ForkController.php#L23-L28
[1] http://php.net/manual/en/pcntl.installation.php

**Comment by lloonngg** [comment]
I am indeed running on Ubuntu and have used --procs in the past successfully with runJobs.  If I initiated rebuildData.php via command line rather than from Special:SMWAdmin, and then cancelled it to perform runJobs, will runJobs handle the rest of the rebuildData tasks?  Previously I used Special:SMWAdmin to launch the rebuild but right now I can't do that because my wiki is unusable due to the vast number of pages needed to be rebuilt.

**Comment by mwjames** [comment]
While both (`rebuildData.php` and `Special:SMWAdmin`) are using the `UpdateJob` to rebuild the data, `rebuildData.php` uses it in direct mode instead of running it through the JobQueue (as this would only add another layer).  `Special:SMWAdmin` on the other hand pushes `UpdateJob` into the JobQueue and then have the `runJobs` finalize the execution.

As soon as jobs are pushed (without processing), `runJobs` takes care of execution or re-runs etc. If the job creation is cancelled in between then jobs until the point of cancellation will still be available through the queue hence its execution continues to be part of the `runJobs` planning.

**Comment by lloonngg** [comment]
So I ended up cancelling the rebuildData.php and initiated updating through Special:SMWAdmin.  I also made a copy of my VM and have in parallel the same database content for both VMs but one set to use SQLStore3 and the other SPARQLStore (with BlazeGraph 2.1.0).  I then runjobs for both with --procs=24.  The SQLStore3 VM is on a mechanical hard drive with 16GB RAM.  The SPARQLStore VM is on an SSD drive (probably 2-3 times faster than the mechanical drive) also with 16GB RAM.  A few observations:

(1) The SQLStore3 runjobs easily runs 10+ times faster from just observing the individual tasks/job ids fly by on the terminal compared to the SPARQLStore run jobs.  Is there any reason to believe that the number of refresh/updates/jobs on the SQLStore3 would be any different from SPARQLStore?  Are the lines of jobs flying by on the terminal indicative of performance between the two setups during rebuild?

(2) Do we know that for sure that BlazeGraph will provide better performance compared to SQLStore3 (I'm using MariaDB)?  So far it appears to me that SQLStore3 shows better performance (runjobs speed, page load, etc.).  It could be that my BlazeGraph setup is not ideal here.  I see that the BlazeGraph status webpage is showing 20-30 queries per second during rebuild.  I have seen up to 1200 qps when running jobs prior to rebuild.  I don't know how to explain the drop in qps.

Of note, I have 185,000 pages in my wiki with almost exclusively SMW data.  I don't know how many triples I have but it has to be at least 10-20 million or more.  Any way to count this from SMW?

(3) In both VM setups, I get the following error.  Is this expected during rebuilding of the SMW data?  I have run the update script prior to SMW data rebuild.

```
2016-06-29 18:42:13 SMW\UpdateJob Page1 pm= requestId=d57a5607fa378b24b3910eaf (id=584526,timestamp=20160628004407) t=60444 error=DBQueryError: A database error has occurred. Did you forget to run maintenance/update.php after upgrading?  See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: UPDATE  `smw_prop_stats` SET usage_count = usage_count + '1' WHERE p_id = '97'
Function: SMW\SQLStore\PropertyStatisticsTable::addToUsageCount
Error: 1205 Lock wait timeout exceeded; try restarting transaction (localhost)
```

**Comment by mwjames** [comment]
Thanks for the feedback and I try to get back to at a later point. As for:

> Error: 1205 Lock wait timeout exceeded; try restarting transaction (localhost)

The DB tries to insert/update the row and encounters a lock (probably due to unfinished transactions) which then raises a `Lock wait timeout` (if you google "mediawiki +  Lock wait timeout" then you should find some hits on this topic).

[0] tries a simple update without an atomic transaction trace, I don't know if it would help to isolate the `update` with something like below under the assumption that the MW transaction scheduler retries on a lock contention:

```php
@@ -78,20 +78,26 @@ class PropertyStatisticsTable implements PropertyStatisticsStore {
 
 		if ( $value == 0 ) {
 			return true;
 		}
 
-		return $this->dbConnection->update(
+		$this->dbConnection->beginAtomicTransaction();
+
+		$result = $this->dbConnection->update(
 			$this->table,
 			array(
 				'usage_count = usage_count ' . ( $value > 0 ? '+ ' : '- ' ) . $this->dbConnection->addQuotes( abs( $value ) ),
 			),
 			array(
 				'p_id' => $propertyId
 			),
 			__METHOD__
 		);
+
+		$this->dbConnection->endAtomicTransaction();
+
+		return $result;
```

Normally, you cannot test or simulate cases as above (e.g. DB lock) since it depends solely on the environment and external factors as to when locks occur, so its a bit like fishing in a pond.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/9ee1dcca85d1d0e19f00a309f6db50e023094ba2/src/SQLStore/PropertyStatisticsTable.php#L83-L92

**Comment by lloonngg** [comment]
I applied your PropertyStatisticsTable.php patch and the lock wait timeout error has gone away; however, I now see a new error for both SQLStore3 and SPARQLStore rebuilds:

`2016-07-01 11:21:11 SMW\UpdateJob Page1 pm= requestId=98f77460f6daa953e257afe7 (id=1014036,timestamp=20160630132851) t=7740 error=DBUnexpectedError: Invalid atomic section ended.`

Is this expected as a result of the patch?

**Comment by mwjames** [comment]
> DBUnexpectedError: Invalid atomic section ended

shh .. and this isn't a really helpful message which happens here [0]. I'm bit out of ideas right now as to what to do with that.

Sorry for the piecemeal work.

> Could it be that MariaDB/Blazegraph can't keep up with the 24 parallel threads for runjobs (--procs)?

I would say that "24 parallel threads" is causing this and normally `__METHOD__` as marker is enough for a section to not cause any trouble [1]. I choose `beginAtomicTransaction` over `beginTransaction` to avoid breaking the commit queue.

What happens if you use `beginTransaction` \ `commitTransaction` instead of `beginAtomicTransaction` \ `endAtomicTransaction`?

> It seems to only happen with SMW\UpdateJob

Well, `UpdateJob` is the point that initiates the `updateStore` (which marks and starts transactions) and therefore responsible to make the final `commit`.

Not sure [2] can be of any help.

> I have not come across these errors (MW 1.20.2, SMW 1.8.0.5).

Some comments about the changed DB transaction model in MW [3]. `SMW 1.8.0.5` never cared much for transactions resulting in side effects like duplicate rows etc.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/db/Database.php#L2553-L2557
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Database.php#L490-L518
[2] https://www.mediawiki.org/wiki/Manual:$wgDebugDBTransactions
[3] https://www.mediawiki.org/wiki/Database_transactions

**Comment by mwjames** [comment]
> What happens if you use beginTransaction \ commitTransaction instead of beginAtomicTransaction \ endAtomicTransaction?

@lloonngg Most likely forcing a direct `commitTransaction` is not such a good idea. Could try instead (it should make each query its own transaction when the DB allows it):

```
@@ -78,20 +78,29 @@ class PropertyStatisticsTable implements PropertyStatisticsStore {
 
 		if ( $value == 0 ) {
 			return true;
 		}
 
-		return $this->dbConnection->update(
-			$this->table,
-			array(
-				'usage_count = usage_count ' . ( $value > 0 ? '+ ' : '- ' ) . $this->dbConnection->addQuotes( abs( $value ) ),
-			),
-			array(
-				'p_id' => $propertyId
-			),
-			__METHOD__
-		);
+		$connection = $this->dbConnection;
+		$table = $this->table;
+		$fname = __METHOD__;
+
+		$connection->onTransactionIdle( function() use( $connection, $table, $fname, $propertyId, $value ) {
+			$connection->update(
+				$table,
+				array(
+					'usage_count = usage_count ' . ( $value > 0 ? '+ ' : '- ' ) . $connection->addQuotes( abs( $value ) ),
+				),
+				array(
+					'p_id' => $propertyId
+				),
+				$fname
+			);
+		} );
+
+		return true;
```

**Comment by mwjames** [comment]
The initial issue of "Illegal property key "" error" has been solved and the discussion about "1205 Lock wait timeout exceeded; try restarting transaction (localhost)" should be continued in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1709.

**Comment by WolfgangFahl** [comment]
@lloonngg  did using blazegraph finally work for you? I Intend to tryout blazegraph my self and I also get errors when doing the initial data rebuild.

**Comment by lloonngg** [comment]
We tried blazegraph and after migrating about 180K pages tested the
performance.  We were not impressed with the speed compared to mysql.
Mostly likely because we were running blazegraph on cpu rather GPU.  We
didn't pursue this further.

**Comment by WolfgangFahl** [comment]
@lloonngg  Thank you that feedback is very useful.
