### ISSUE TITLE
SMW disables itself when Cargo is installed

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#1748]
This behaviour is present since SMW 2.4 and was intentionally added. My view is that this is an anti-feature that is not in the interest of most users and should be removed.

See also these threads on the mailing list:

* [Semantic MediaWiki and Cargo/WikiBase](https://sourceforge.net/p/semediawiki/mailman/semediawiki-user/thread/1466658604630-5064994.post%40n6.nabble.com/#msg35177423)
* [all smw functionality missing after upgrade to SNPedia.com](https://sourceforge.net/p/semediawiki/mailman/semediawiki-user/thread/CAGdMhTa8v-n-GBMkSq5iCU%2BaX5Go2r%2B%3D_1bLAmK%2BtBjMT%2BGmHg%40mail.gmail.com/#msg35253456)

**Comment by JeroenDeDauw** [comment]
If you are running into this, untill it is fixed, you can get around it by setting this in your LocalSettings.php:

```php
$GLOBALS['smwgEnabledCompatibilityMode'] = true;
```

**Comment by mwjames** [comment]
All I have to say in this topic, I did so with [0].

If a users wishes to run the software then s(he) has to make the appropriate settings __BUT__ it will no longer be expected to work specified or tested (which nullifies any possible volunteer support time).

[0] http://wikimedia.7.x6.nabble.com/Semantic-MediaWiki-and-Cargo-WikiBase-tp5064994p5065021.html

**Comment by ckoerner** [comment]
@mwjames, I understand your frustration and appreciate all the time you have dedicated to this project. There have been a few long-time SMW folks getting bitten by this change. Not replying to the questions posed by others in the mailing list and repudiating further discussion doesn't seem like the right approach. Please reconsider.

Again, i know this bugs you, but may I make a suggestion? A compromise of sorts? Perhaps instead of silently disabling SMW we should instead give the user a notification of some sort. Something that can't be missed and could alert the user to concerns over compatibility.

This address, in part, your concerns of "Hey, don't bug me when things break with XYZ Extension!" and lets folks know what's going on rather than spending their time digging around trying to figure out what is 'broken'.
