### ISSUE TITLE
Multiple entries for an entity with same the subject is returned by the Store

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#191]
https://bugzilla.wikimedia.org/show_bug.cgi?id=48707

**Comment by jcostello1** [comment]
Not sure it will help but here it is anyways. Perhaps some new clues....

I recently was hit with a mass of duplicate entries on my site. I recently upreved to SMW 2.3.1 but can't say that's when it happened. For quite a while I had been carrying a single duplicate page result, a real page name as well as a previous version of the page name that contained an accented character. I chalked it up to the accent and the name change until last night when I discovered a large number of duplicates in a particular query, about 1/3-1/2 of the results. 

All duplicates were strange in that they had odd capitalization of the real page names. Either just the first, the first couple or sometimes all of the words in the titles were fully capitalized but otherwise correct. My original as well as these latest duplicates were all pages with the same infobox template inclusion which sets the semantic properties that were being queried and I haven't detected duplicates in any other area of my site. 

Rebuilding did not correct the issue and nor did editing and saving the effected pages so in the end I removed all the smw_ tables (after backing up of course), reinitialized and rebuilt. With that, all duplicates were removed. Thank goodness my site is small enough!

I'm currently running: MW 1.23, SMW 2.3.1, PHP 5.5.33

**Comment by mwjames** [comment]
> All duplicates were strange in that they had odd capitalization of the real page names. Either just the first, the first couple or sometimes all of the words in the titles were fully capitalized but otherwise correct.

That seems odd and an example or screenshot would have been helpful.

> My original as well as these latest duplicates were all pages with the same infobox template inclusion which sets the semantic properties

One hypothesis of mine was that it has something to do with a race condition during the update (and templates play a vital role in how/when) or DB transaction rollbacks somehow interfering with the update process but this issue is very hard to pin point and with no exact way of reproducing it chances to find the condition as to when and where a duplication occurs are greatly diminished. 

 2.4 might help with the transaction lag since updates are pushed into a deferred queue (#1435) together will all the other MW DB commits.

> Rebuilding did not correct the issue and nor did editing and saving the effected pages so in the end I removed all the smw_ tables (after backing up of course), reinitialized and rebuilt. With that, all duplicates were removed.

Hopefully this is fixed by detecting "null" entities (those that have no references, #1216) and being removed during the `rebuildData.php` run.

**Comment by jcostello1** [comment]
Thanks for the info @mwjames. I loaded the backup database into a dev environment to 'poke around' with it so here is the screenshot.

![smw duplicates screenshot](https://cloud.githubusercontent.com/assets/17897526/14118388/3ee69a1a-f5b7-11e5-87fa-dc062e9cd9cd.jpg)

**Comment by mwjames** [comment]
The issue is fairly old based on an outdated SMW version, if the issue surfaces again then a new issue should be opened together with some information on how to reliably replicate the issue.
