### ISSUE TITLE
#sparql parser function

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1987]
The `#ask` parser function provides a vast (in terms of supported features) and easy access to both `SQLStore` and a triple store (using the `SPARQLStore` and `RespositoryConnector`) and is for most users of SMW the optimal solution to abstract a query from a specific knowledge domain and/or require a user to learn the SQL or SPARQL language.

Yet, for some power users it maybe beneficial to have direct access to the triple store back-end by allowing to use `SPARQL` as query language. This task seeks feedback and suggestions about introducing a `#sparql` parser function aimed at power users in addition to the existing `#ask`.

## Questions 

- Does it makes sense to provide a  `#sparql` parser function?
- What are the use cases where  `#sparql` would be of advantage compared to the use of `#ask`?
- What features of  `#sparql` would be expected?
- How would a `#sparql` implementation need to be designed to make existing query printers to use the returning results?
- Should  `#sparql` actually provided an interface to existing query printers?
- Would a simple table and JSON export be sufficient for a  `#sparql` output?

## Notes

- https://github.com/RubenVerborgh/SPARQL.js

PS: I have no immediate plans on working towards an implementation of said function but I'll be receptive to anyone (with a strong focus on developers) who want to see this task/RFC being resolved.

**Comment by lalquier** [comment]
Take a look at the [LinkedWiki](https://www.mediawiki.org/wiki/Extension:LinkedWiki) extension, which current offers a #sparql parser function and covers several options and use cases.

To me, benefits over #ask are mostly a more expressive query language with finer control over very complex queries and the option to query internal and external triple stores (including Wikidata)

A bridge to current query printers would be great.

I know it is not necessarily linked to a #sparql parser function byt another feature I would love to see is a way to send a list of certain properties to a separate graph inside a triple store or to a separate triple store altogether. Admin properties like 'Has query' for example tend to clutter sparql queries with results that have little to do with the content of the wiki.

**Comment by plegault2** [comment]
The [https://www.mediawiki.org/wiki/Extension:LinkedWiki LinkedWiki] extension is where I'm running into issues, when trying to upgrade. Something always changes in the way subobjects are stored are the way the query is handled. I then have to search far and wide to figure out what changed to fix it. It would be nice if ask could do the complex queries, it seems that when changes happen the ask query is usually kept in sync.

**Comment by mwjames** [comment]
>Did you take a look at the LinkedWiki extension? it currently offers a #sparql parser function and covers several options and use cases.

Yes, I'm aware of that extension but the idea here is not to copy the function but instead have a discourse of what makes sense in terms of SMW and what use cases are crucial and hereby provides a functionality map that may benefit SMW in general without introducing too much technical debt and/or maintenance burden.

> Admin properties like 'Has query' for example tend to clutter sparql queries with results that have little to do with the content of the wiki.

Let's keep the discussion focused but have a look at 1827.

**Comment by mwjames** [comment]
> Something always changes in the way subobjects are stored are the way the query is handled. I then have to search far and wide to figure out what changed to fix it.

There was once a change (I don't remember which release) in terms of how `-aux` being used as auxiliary marker but I do remember that I remarked on an email that you could use the BC setting to retain those old markers until SMW 3.x.

**Comment by s7eph4n** [comment]
> Does it makes sense to provide a #sparql parser function?

Yes! So much so, that I considered doing it.

> What are the use cases where #sparql would be of advantage compared to the use of #ask?

Any query that is too complex for #ask. Or if not too complex then too time-consuming, e.g. when nesting queries.

> How would a #sparql implementation need to be designed to make existing query printers to use the returning results?

That's a question I would ask you. I guess connecting the results from the SPARQL query to the correct data types could be an issue.

> Should #sparql actually provided an interface to existing query printers?

Yes. That would be the main advantage over e.g. LinkedWiki.

An alternative might be to somehow open up the result formats and define an interface so that it would be possible to directly use a LinkedWiki result (or possibly any other tabular wiki data).

> Would a simple table and JSON export be sufficient for a #sparql output?

IMHO it would be a start, but should not be the end.

**A (near) real life use case:**

I have an issue tracking system. Every week there is a meeting discussing some of the issues. This produces log entries. So I have three categories of objects:
* log entries
* issues
* meetings

Issues have properties like title, responsible, target date, last comment.

Meetings have properties like meeting date.

Log entries have properties like meeting date, issue title, issue responsible, issue target date, comment.

Each log entry contains updates to some of the attributes of the issues, e.g. the target date, but not necessarily all of them. The properties of the issue are derived by #asking for all relevant log entries, sorting them by meeting date and taking the newest non-empty value for each attribute. (E.g. it could be that the responsible is assigned once and is never updated. The last comment on the other hand will change with every meeting.) This means the properties of issues (and meetings) are set from the result of #ask queries.

(Log entries are imported using the DataTransfer extension. Pages for issues and meetings that are not yet existing are created on the fly using [AutoCreatePage](/mkroetzsch/AutoCreatePage).)

To prepare for upcoming meetings the issues on the agenda are queried and their attributes shown in a formatted table (+ an Excel download).

Problems I have:
* Importing log entries is slow due to all the queries that have to be performed to set attributes of issues.
* Often pages for log entries are created, but properties seem not to be stored (could be a DataTransfer bug).
* Pages for issues are not properly updated.
* Pages for upcoming meetings are not properly updated.

I get the impression that I run into race conditions from concurring jobs.

It could be a solution to not store any properties of issues or meetings at all, but instead to directly access the properties of the log entries. Which I think could be achieved using (rather complex) SPARQL queries.

**Comment by Reasno** [comment]
I would prefer a lua implementation. It is more customisable and easier to learn.

**Comment by mwjames** [comment]
> I would prefer a lua implementation.

Lua is not part (as dependency) of SMW-core and should (if) be handled by https://github.com/SemanticMediaWiki/SemanticScribunto.

**Comment by mwjames** [comment]
Has been moved to the "Enhancements and features" kanban, any implementation can make a reference to this issue.
