### ISSUE TITLE
Wikia and SMW

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2003]
This task is to solicit some feedback on the recent transition by Wikia from SMW 1.8 to SMW 2.4.1 [0]. 

[1, 2] shows required changes in context of that transition with some adaption of the code base being unavoidable given Wikia's structure and its wiki environment, yet we should aim at minimizing possible changes or at least provide an easy migration path (if this is possible).

@macbre, @TK-999 given the involvement [0] some feedback would be welcome as to:

- How easy or difficult was the transition to SMW 2.4.1?
- Did the change to SMW 2.4.1 had any positive/negative side effects?
- Did the change had an impact (improved/remained/worsened) on the DB cluster for executed SMW queries compared to SMW 1.8?

## Notes 

A quick review on the changes by reading the headline of [0] revealed that:

- "Register SMW namespaces as early as possible" expected to be addressed with #1887 and back-ported to the upcoming 2.4.2
- Change to "LazyDBConnectionProvider" to incorporate `DBO_TRX`, #1758 in 2.5 provides a setting to allow temporary tables to be executed in auto-commit mode avoiding an issue in case of `enforce_gtid_consistency=true` 
- "JobBase: push SMW jobs to Wikia Tasks queue" is Wikia specific within an isolate change to the base class
- "API: make getExamples methods in SMW modules public" ?
- "Wikia changes in SMW from 1.8.5"
 - "SMW_SQLHelpers.php" was removed in 2.5 and replaced by `SMW\SQLStore\TableBuilder\MySQLTableBuilder.php`
 - I wonder about the `SMW_SQLStore3_Writers.php` change after the JobBase class has been adapted 
- "Smw QueryEngineDatabaseConnectionProvider" is the expected use case I had in mind when part of the code got refactored to isolate the call directed to the QueryEngine without touching any other code within SMW-core/MW
- "Remove all files from autoloader" ?
- "SUS-1234: Fix PHP fatal in SMW BrowseByProperty API" addressed with #1990
- "SUS-1238: Fix JS error in SMW tooltips" Wikia specific (#1994)

Any other changes?

[0] http://community.wikia.com/wiki/User_blog:DaNASCAT/Technical_Update:_Semantic_MediaWiki_Upgrade_On_November_3rd
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/master...Wikia:2.4.2_Wikia
[2] https://github.com/Wikia/SemanticMediaWiki

**Comment by TK-999** [comment]
We removed SMW from Composer autoload because it caused SMW to be loaded on all wikis even if SMW was not enabled on that particular wiki. So we load it from config now to ensure local settings are respected.

`getExamples` methods were made public because of MW 1.19 - [required by ApiBase class](https://www.mediawiki.org/w/index.php?title=API:Extensions&oldid=606250)

We also plan to change how default values are applied in https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/load.php#L75 - https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/DefaultSettings.php is currently overwriting `$GLOBALS` directly, however our MediaWiki extension used to manage configuration settings for individual wikis is run before SMW is included, so any config options changed via that extension are overwritten by the defaults - we'll add a simple check to only apply defaults if the variable hasn't been declared yet.

As for our changes in 1.8, they were also TaskQueue-related and also introduced a separate query group for SMW queries.

We're currently finalizing our performance assessment and will follow up with further details shortly. Thanks for your cooperation! 😃

**Comment by JeroenDeDauw** [comment]
> We removed SMW from Composer autoload because it caused SMW to be loaded on all wikis even if SMW was not enabled on that particular wiki. So we load it from config now to ensure local settings are respected - this is only an issue in multi-wiki environments.

While I don't like this kind of fix (it undermines the safety of the package installation process), it's been something that's been requested often and is now finally done in Maps: https://github.com/JeroenDeDauw/Maps/blob/c4b1312ffb3498930ceb6a99e0782ea5e26dd5b4/Maps.php#L51-L53

Having such a setting for SMW would solve the issue for you right?

**Comment by TK-999** [comment]
Certainly - since our install is shared a config var is out best option to turn SMW on/off for individual wikis.

Please let us know if you need any further information, and thank you for reaching out and for your continued dedication to making SMW even better :)

@macbre , @sqreek, @mixth-sense - please add any additional observations :)

**Comment by mwjames** [comment]
> We also plan to change how default values are applied in https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/load.php#L75 - https://github.com/Wikia/SemanticMediaWiki/blob/2.4.2_Wikia/DefaultSettings.php is currently overwriting $GLOBALS directly, however our MediaWiki extension used to manage configuration settings for individual wikis is run before SMW is included, so any config options changed via that extension are overwritten by the defaults - we'll add a simple check to only apply defaults if the variable hasn't been declared yet.

- [ ] Wikia/app#11922 addressed with #2029

## Other issues
- [x] http://naruto.wikia.com/wiki/Thread:217742#29 addressed with #2022

**Comment by kghbln** [comment]
It appears that SMW is basically working alright for Wikia after the big update with them reporting occurring issues as they are observed.
