### ISSUE TITLE
No update when modifying leading zeros on property of type text

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#2061]
### Setup and configuration

- SMW version: 2.4.0
- MW version: 1.25.5
- PHP version: 5.6.14
- DB (MySQL etc.): MySQL 5.6.34

### Issue

* Create [[Property:My property]] with [[Has type::Text]]
* Create a page with [[My property::001]]
* Verify in [[Special:Browse]] that My property = 001
* Edit the page to [[My property::000001]]
* **Bug:** My property still = 001

**Comment by kghbln** [comment]
Indeed, I was able to replicate this behaviour on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/2061)

**Comment by mwjames** [comment]
... on my weekly support round ...

## Analysis 

The issue is caused by [0] which compares old with new values in order to decide whether they are equal or not. Doing `011 == 0011` for a string will return `TRUE` with the consequence that it will not initiate an update process as no difference has been recognized.

Obviously this is incorrect but this function has performance relevance and the note about `==` vs `===` cannot be ignored either, so it needs careful consideration.

> // Delete matching values
// use of == is intentional to account for oldValues only
// containing strings while new values might also contain other
// types


For string values, the comparison `011 == 0011` will yield `TRUE` while `011 === 0011` returns `FALSE. [1, 2]

PS: I'm amazed that legacy issues still find its way without being detected (this is not a 2.4 or 2.0 regression [3]).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/PropertyTableRowDiffer.php#L265-L272
[1] http://php.net/manual/en/language.operators.comparison.php
[2] http://stackoverflow.com/questions/80646/how-do-the-php-equality-double-equals-and-identity-triple-equals-comp
[3] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.9/includes/storage/SQLStore/SMW_SQLStore3_Writers.php#L354-L357

**Comment by mwjames** [comment]
Addressed with #2064.
