### ISSUE TITLE
ContentHandler related deprecations

### ISSUE THREAD

**Issue by reedy** [SemanticMediaWiki/SemanticMediaWiki#2079]
Creating this as somewhat of a Meta task; it's applicable to SemanticMediaWiki, and your other extensions too

Partially copy from https://phabricator.wikimedia.org/T151973

In MediaWiki 1.21, many functions and hooks were deprecated and replaced as part of Daniel Kinzlers ContentHandler improvements

The Semantic* extensions are responsible for a lot of the usages of these still (granted, some are function_exist() guarded, for various back compat etc)

I'd be grateful if you could see about fixing up all your usages (whether guarding them all if you need MW back compat, or if it's just replacing them completely if you don't care about < MW 1.21) as I'd ideally like to get these removed in the 1.29 release cycle, as they've been around for at least 4 years as is.

If possible, any sync back to WMF hosted extensions (even if not canonical) to improve grepping/IDE find functions would be greatly appreciated.

**Comment by reedy** [comment]
I should note, at this point, I don't know how far we're diverged on various extensions...

I'll open a task about that...

**Comment by reedy** [comment]
See also https://phabricator.wikimedia.org/T151968

**Comment by JeroenDeDauw** [comment]
Thanks for bringing this up @reedy 

> if you don't care about < MW 1.21

Our current compar is MW 1.23 and later, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

> I'd be grateful if you could see about fixing up all your usages

Pull requests are of course welcome

> If possible, any sync back to WMF hosted extensions

AFAIK we no longer have a copy on Gerrit since TWN started supporting GitHub. We certainly are not syncing anymore. If there is a copy on Gerrit of the extensions we have in this GitHub org left it should be removed to avoid confusion.

**Comment by kghbln** [comment]
> In MediaWiki 1.21, many functions and hooks were deprecated and replaced as part of Daniel Kinzlers ContentHandler improvements

- [ArticleAfterFetchContent](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=ArticleAfterFetchContent&type=Code) - no occurrence
- [ArticleInsertComplete](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=ArticleInsertComplete&type=Code) - no occurrence
- [ArticleSave](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=ArticleSave&type=Code) - no occurrence
- [ArticleSaveComplete](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=ArticleSaveComplete&type=Code) - no occurrence
- [EditFilterMerged](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=EditFilterMerged) - no occurrence
- [EditPageGetPreviewText](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=EditPageGetPreviewText&type=Code) - no occurrence

So I believe the work was already done.

> I should note, at this point, I don't know how far we're diverged on various extensions...

I'd say quite a lot since the complete switch was on April 1, 2016.

**Comment by kghbln** [comment]
@reedy I appreciate that you actually care about issues like this one.

**Comment by reedy** [comment]
No problem. I don't mind putting some effort in, and it's not nice to just break things unnecessarily, and more so, purposefully.

The versions of your extensions in gerrit *do* have various uses of those functions etc, but if they're lagging behind anyway... Of course they're going to :)

If #2080 is the better "fix" for this, that's fine by me. If someone wants to make the patches in gerrit master branches to clear out the migrated extensions, that'd be great. Alternatively, giving a list here, on #2080 or on https://phabricator.wikimedia.org/T151968

**Comment by JeroenDeDauw** [comment]
@kghbln I'm afraid you did not look for occurrences of those property. `ClassName::methodName` is just how people indicate which class the method belongs to. Typically you won't have that format used in the code though. I did a search for the last method and found a bunch of matches, so the other are probably also still used.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?utf8=%E2%9C%93&q=prepareTextForEdit

**Comment by kghbln** [comment]
> @kghbln I'm afraid you did not look for occurrences of those property.

@JeroenDeDauw Indeed, I only looked for exact string matches. Probably a reason why I back off from programming. If you tell me which hooks and functions are actually affected I could create an issue each, if this helps keeping track of this pot-pourri

**Comment by reedy** [comment]
It can get quite difficult with the dynamic-ness. Similarly, just grepping for getText() will give a whole host of false positives

I did dump some lists on https://phabricator.wikimedia.org/T151973, and a Ctrl + F in your browser shows 42 things to look at, and it'll be more/less based on titles, or just extension names being used as grouping

**Comment by mwjames** [comment]
[0] failed because of:

```
Fatal error: Call to undefined method Mock_WikiPage_a6a5568c::prepareTextForEdit() in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/EditInfoProvider.php on line 105
```

... and this is what I mean, I'll come back a week later and instead of working on extension related stuff in my limited support time, I now have to spent time to get this fixed which is surely not appreciated.

Those things really make my weekend!

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/184729265

**Comment by reedy** [comment]
I'm sorry, but it's a two way street here.

MW 1.21 was released March 2013. We're now 3 years and 9 months later on. I'm not sure how it's "our fault" if you haven't fixed it up in that period. It's not like you're even still supporting < 1.21

It was wfDeprecated (so throws a warning) a couple of versions later.

I think, as we're now on 1.29 (in alpha), that 7 release versions (and 2 LTS), so on the 8th after being deprecated... It's fair we remove it.

And as above, it's hard. If the extensions are under "our control" (ie in gerrit), we can fix them easily enough; and we have been.

How do you expect us to support all these extensions stored in different places? What about extensions we don't know about? How do you want us to support those?


You're a competent developer; these instances are being easily fixed by beginner developers as GCI tasks. This shouldn't take you long to fix, if you need to.
