### ISSUE TITLE
Printouts of chained property values

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#2189]
In ask queries you can use property chains in the condition part of an ask query.
For instance you can ask for all cities which are located in something that is member of (a union):
```
{{#ask: [[Category:City]] [[locatedIn.MemberOf::+]]}}
```

What you cannot do is to printout the values of chained properties, e.g. ```?locatedIn.MemberOf```

This is something that is currently possible in SPARQL, but I think it would be nice to support this in SMW, too.

Copied from https://phabricator.wikimedia.org/T23232.

**Comment by kghbln** [comment]
Can't this somehow be achieved with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1824 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2073 up for release with SMW 2.5.0. Have you tried this?

**Comment by alex-mashin** [comment]
That would be great, but I am currently under SMW 2.4.4 and do not dare to upgrade to a beta version: the costs of upgrading and then rolling back would be to great; and my hardware is below adequate.

**Comment by kghbln** [comment]
Try the [sandbox wiki](https://sandbox.semantic-mediawiki.org/wiki/Main_Page).

**Comment by alex-mashin** [comment]
Looks like it works: https://sandbox.semantic-mediawiki.org/wiki/Test_property_chains_in_printouts.

**Comment by kghbln** [comment]
Cool and not quite unexpected!

**Comment by mwjames** [comment]
> Copied from https://phabricator.wikimedia.org/T23232

I wasn't aware that we have a eight year old request for this feature, I mainly needed this for the new `Reference` type and required some extensive re-factoring before it would pass our test suite [0].

> Can't this somehow be achieved with #1824 and #2073 

Yes, #1824 is the main anchor point.

> Try the sandbox wiki.

Cited issue contains links to available examples.

> and do not dare to upgrade to a beta version

Software is never flawless and therefore always in a kind of beta state because no matter how hard you try to anticipate decision paths of a user or system sooner or later a bug will appear. We attempt to mitigate that situation by adding more tests but this is just as good as we can encounter them before hand. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0434.json
