### ISSUE TITLE
semantic properties not registered in the special page "special:properties"

### ISSUE THREAD

**Issue by pertineze** [SemanticMediaWiki/SemanticMediaWiki#2190]
### Setup and configuration

- SMW version: 2.4.5
- MW version:1.28.0
- PHP version:5.5.9-1ubuntu4.20 (apache2handler)
- DB (MySQL etc.):MySQL 5.5.53-0ubuntu0.14.04.1

Hi! I've installed a local MediaWiki with the Semantic MediaWiki extension.   When I create a page with semantic properties, they are not registered in the special page "Special:Properties". I added the following to my "LocalSettings.php" file but it doesn't work:

```php
$smwgCacheUsage = array(
    'smwgWantedPropertiesCache' => true,
    'smwgWantedPropertiesCacheExpiry' => 86400,
    'smwgUnusedPropertiesCache' => true,
    'smwgUnusedPropertiesCacheExpiry' => 86400,
    'smwgPropertiesCache' => true,
    'smwgPropertiesCacheExpiry' => 3600,
    'smwgStatisticsCache' => true,
    'smwgStatisticsCacheExpiry' => 86400
);
```

**Comment by kghbln** [comment]
You did not really change the caching behaviour with your [`$smwgCacheUsage`](https://www.semantic-mediawiki.org/wiki/Help:$smwgCacheUsage) setting change. For special page "Properties" it is still at one hour.

**Comment by kghbln** [comment]
Do they show in the meantime?

**Comment by pertineze** [comment]
Hi kghbln, 

no, i change the parameter and increase it quite a bit but it does not change anything, sorry.

Cheers and thank you for your help

**Comment by kghbln** [comment]
> i change the parameter and increase it quite a bit 

Increasing means extending the time the pages are cached.

What is your job queue looking like? Example: [sandbox job queue](https://sandbox.semantic-mediawiki.org/w/api.php?action=query&meta=siteinfo&siprop=statistics)

**Comment by mwjames** [comment]
> no, i change the parameter and increase it quite a bit but it does not change anything, sorry.

Okay, the information are a bit sparse to make any recommendations therefore let's have a look at the list below and check the items before we continue the analysis:

- [ ] Installations instructions were followed including:
 - [ ] Run `update.php` [0]
 - [ ] Added `enableSemantics` [1] to the `LocalSettings`
- [ ] Functionality as shown in [2] work and result in the same output as in the video

> When I create a page with semantic properties, they are not registered in the special page "Special:Properties".

When reporting an issue, you should describe your actions as detailed as possible so that someone like @kghbln can have some pointers on what is meant by "create a page with semantic properties" and hereby avoids interpretive freedom on the possible cause for the "not registered in the special page special:properties".

> change the caching behaviour with your $smwgCacheUsage setting change

It shouldn't and even if it did the default is set to 1 hour and after that you access the `Store` the retrieve the data from the backend.

[0] https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
[1] https://www.semantic-mediawiki.org/wiki/Help:EnableSemantics
[2] https://www.youtube.com/watch?v=N5rlX9yCqDo

**Comment by kghbln** [comment]
Admittedly I thought not just the statistical data is cached by also the list of properties. Good to know. Apart form that I never ever directly looked at special page "Special:Properties" after creating a page with properties new to the wiki to see if they are registered there. So this kind of issue never popped up on my radar. Will test myself now.

**Comment by mwjames** [comment]
This issue has been open for 23 days without further interaction or feedback, I closing this in anticipation that this issue has been solved. If this assumption is invalid, please feel free to reopen this ticket and try to elaborate on https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2190#issuecomment-274223302.
