### ISSUE TITLE
Composer.lock not up to date after installation of SMW

### ISSUE THREAD

**Issue by RobinMathewRajan** [SemanticMediaWiki/SemanticMediaWiki#2323]
After installation of semantic mediawiki through Composer, when I run maintenance/update.php, the script exits with an error, that the composer.lock is not up to date! Why is it happening? Is there any way to solve this error?

The mediawiki version is 1.27.1 LTS

SMW: 2.4.6

PHP: 7.0.16-4+deb.sury.org~xenial+1 (cgi-fcgi)

MySQL: 5.7.17-0ubuntu0.16.04.1

Ubuntu 16.04 LTS

**Comment by mwjames** [comment]
> Why is it happening? Is there any way to solve this error?

Because during the update process, `update.php` detects [0] a change and informs the user to run `composer update` before continuing. This isn't really an issue but our 1.27 test run encounters a similar fate [1] due to how MW-core is using `composer.json` for its own purpose.

```
php maintenance/update.php --quick
MediaWiki 1.27.1 Updater

phpunit/phpunit: 4.8.35 installed, 4.8.* required.
Error: your composer.lock file is not up to date. Run "composer update" to install newer dependencies
```

> Is there any way to solve this error?

You can use `php maintenance/update.php --skip-external-dependencies` to avoid the check.

[0] https://github.com/wikimedia/mediawiki/blob/master/maintenance/update.php#L132-L139
[1] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/209971803

For reference https://phabricator.wikimedia.org/T114182, https://phabricator.wikimedia.org/T147614

**Comment by kghbln** [comment]
I have [documented this in the wiki](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AInstallation%2FTroubleshooting&type=revision&diff=49845&oldid=49698). Closing this assuming that this issue is resolved.

**Comment by RobinMathewRajan** [comment]
Thanks for the clarification folks! :)

Could we workaround/suppress this error by using composer.local.json instead of composer.json?

**Comment by kghbln** [comment]
Always use "composer.local.json" since this is upgrade safe. Apart from that: I guess that this will not help.
