### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by stuppie** [SemanticMediaWiki/SemanticMediaWiki#2333]
### Setup and configuration

- SMW version: latest
- MW version: 1.29
- PHP version: HipHop VM 3.12.7 (rel)
- DB (MySQL etc.): mysql

### Issue

I was trying to follow the installation instructions [here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md), which caused dependency failures with composer. After much wasted time troubleshooting, I saw the require is different on the [main readme](https://github.com/SemanticMediaWiki/SemanticMediaWiki). I think it should be updated to read "mediawiki/semantic-media-wiki": "~2.5@dev"  ?

**Comment by kghbln** [comment]
Thank you for reporting and I am sorry for the troubles you encountered.

Indeed the installation document was updated last week for the upcoming 2.5.0 release which will most likely happen tomorrow and is not yet tagged. The document should indeed always refer to the latest stable version so it should rather be `~2.4` in "INSTALL.md" and "README.md" since I guess that you did not want to install master as most other people, too.

What could be done is to add a section to "INSTALL.md" stating how master may be installed, i.e. informing that `"mediawiki/semantic-media-wiki": "~2.5@dev"` instead of what is written in step x of the instructions.

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames I added two action items to the release process at the very end. I guess this is ok.

**Comment by stuppie** [comment]
Thanks. I think the instructions [here](https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B) should be updated also?

**Comment by kghbln** [comment]
> What could be done is to add a section to "INSTALL.md" stating how master may be installed, i.e. informing that "mediawiki/semantic-media-wiki": "~2.5@dev" is the way instead of what is written in step x of the instructions.

Done with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/dbbf3d1e465f95c912da2ef421db729ad90f993e#diff-a40e078c3972c1f698f6ed3d4a47b0c2

**Comment by kghbln** [comment]
> Thanks. I think the instructions here should be updated also?
[Done](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AInstallation%2FUsing_Composer_with_MediaWiki_1.25%2B&type=revision&diff=50329&oldid=50287)
