### ISSUE TITLE
Invalid data value annotations not directly shown for datatype "Text"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2342]
### Setup and configuration

- SMW version: 2.5.0
- MW version: 1.28.0
- PHP version: 5.6
- DB (MySQL etc.): 10

### Issue
In contrast to earlier versions of Semantic MediaWiki <= 2.4.x erroneous values are no longer shown when annotated. Just the warning icon is show at the spot which allows to hover for information about the error.

I believe that it is better to be able to directly see the incorrectly annotated value instead of having to hover for it.

### Example
[Jane Do](https://sandbox.semantic-mediawiki.org/wiki/Do,_Jane)

**Comment by mwjames** [comment]
Hi,

> In contrast to earlier versions of Semantic MediaWiki <= 2.4.x erroneous

I believe this isn't correct for the `Text` type because the source
from 1.9.2 [0] (and it is equal to what 2.5.0 does) says something
like "When the value is invalid return an empty string to the caller".

If you want to change the behaviour then you would need to adjust the
source (I haven't test the change nor did I run the test suite itself
on this).

```
@@ -41,10 +41,11 @@ class SMWStringValue extends DataValue {

 		if ( $value === '' ) {
 			$this->addErrorMsg( 'smw_emptystring' );
 		}

+		$this->m_caption = $value;
 		$this->m_dataitem = new DIBlob( $value );
 	}
```

```
@@ -47,11 +47,11 @@ class StringValueFormatter extends DataValueFormatter {
 		if ( $this->dataValue->getCaption() !== false && $type ===
self::HTML_SHORT ) {
 			return smwfXMLContentEncode( $this->dataValue->getCaption() );
 		}

 		if ( !$this->dataValue->isValid() ) {
-			return '';
+			return $this->dataValue->getCaption();
 		}
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.9.2/includes/datavalues/SMW_DV_String.php#L119-L120

Cheers

**Comment by kghbln** [comment]
> I believe this isn't correct for the `Text` type

Just verified this. Indeed I was wrong. 

> If you want to change the behaviour

I still believe that this should be consistent for all datatypes so ...

**Comment by kghbln** [comment]
I can imagine that the reason for datatype "Text" not having this feature is that in former times allows value restrictions were probably only applied to datatype "String". Since these were merged.
