### ISSUE TITLE
SMW off/on in #info parser tag (SMW 2.5.0)

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#2347]
### Setup and configuration

- SMW: 2.5.0
- MW: 1.28.0
- PHP: 5.6.30-0+deb8u1 (cgi-fcgi)
- DB: 10.0.30-MariaDB-0+deb8u1

### Issue

All publications in our bibliography (http://www.vanhamel.nl/codecs) are stored on their own pages and we have a couple of templates that can be used elsewhere to produce conveniently formatted citations. These templates contain queries with "format=template" to render the citations, which are added to variables (Variables extension) and these variables are then printed in both #info bubbles and lists of endnotes at the bottom of the page. The recommended workaround for equal signs (that is, recommended on semantic-mediawiki.org) is followed here. 

Everything was working fine until last week, when I upgraded to SMW 2.5.0. The link for every publication shown by the query is now surrounded by links saying "SMW::on" and "SMW::off". Here is an example: 

http://www.vanhamel.nl/codecs/Tan_b%C3%ADm_eter_mo_shruithe

(See the tooltip for the comment about the linguistic dating of this text)

I'm parking this here now and realise there may not be enough to build a clear case but I hope to be adding more details soon.

**Comment by kghbln** [comment]
Thank you for reporting. These "signal markers" appear on and off from time to time. I assume that you upgraded from 2.4.x

**Comment by D-Groenewegen** [comment]
Yes, I should 've mentioned that I upgraded from 2.4.6 > 2.5.0. The issue I recreated over at the sandbox is not entirely true to my use case, but I was wondering myself about interferences from any extension. In fact, there's something that might point to the Interwiki extension:

> <a class="extiw" href="http://semantic-mediawiki.org/wiki/off" title="smw:on">SMW::off</a>
> <a class="extiw" href="http://semantic-mediawiki.org/wiki/on" title="smw:off">SMW::on</a>

Is "extiw" (external interwiki?) is a class speciic to the Interwiki extension? I should note that the "smw:" prefix is used by that extension to refer to semantic-mediawiki.org, which probably explains how those href links to non-existing pages entered the code. 

P.S. The above helps to provide a CSS quickfix 

> .extiw[title="smw:off"], .extiw[title="smw:on"] {
>    display:none;
> }

**Comment by kghbln** [comment]
[`extiw`](https://github.com/wikimedia/mediawiki/blob/aeedfb8526e9d221553e430437a7572a6da2ba65/includes/linker/LinkRenderer.php#L287) appears to be a class provided by MediaWiki core and applied to interwiki links. So the issue starts out earlier. The "Interwiki" extension is basically just a tool that provides an interface and thus helps you avoid editing the [interwiki database table](https://www.mediawiki.org/wiki/Manual:Interwiki_table) directly. By default the interwiki prefix for smw.o is "semantic-mw" so "smw" is probably a custom prefix. However I guess that not just "codecs" will get the idea of using this prefix, meaning if there is something that SMW can do to mitigate this unwanted interaction it should probably do so.

**Comment by mwjames** [comment]
>  surrounded by links saying "SMW::on" and "SMW::off"

Those are internal markers to indicate that text between them are not supposed to be processed as annotations in the `InTextAnnotationParser` [0]. 

>  I assume that you upgraded from 2.4.x. Interestingly on sandbox the issue does not seem to appear, so what is the difference. 

The change appeared with #1768 and the reason why it doesn't appear on the sandbox is because of `$GLOBALS['smwgLinksInValues'] = SMW_LINV_OBFU;` setting where the `Obfuscator` is doing some extra encoding and removes "hanging" markers.

> Everything was working fine until last week, when I upgraded to SMW 2.5.0. The link for every publication shown by the query is now surrounded by links saying "SMW::on" and "SMW::off".

Given that it is indeed a regression, I removed the necessary `[` encoding in #2351 and added an extra test to cover this use case.

PS: While the removal is certainly "tiny" compared to the overall changes that happened between 2.4 and 2.5, I cannot stress enough the fact that I wished we would find those issues earlier (and not six months after a change). The more test cases we control the more likely it is that we can avoid situations like above as it took me two hours to bisect the relevant change and create a replicable use case. 

PSS: Changes to the code base are unavoidable to increase its robustness and extensibility but not on the expense of readability and maintainability. To avoid regressions we use a wide range of integration tests [1] that would fail by the time semantic changes no longer correspond to the expected output of previous versions, yet those tests are only as good as to the area they cover.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Parser/LinksProcessor.php#L184-L196
[1] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by kghbln** [comment]
What makes things like this one harder to detect is probably that some implementations of features like the one described here are not as wide spread in usage so even if 20 people were doing field tests the likelihood for something like this to be detected is not too high. One of the disadvantages of versatility which we still all very much like to have. This situation indeed also emphasizes the need to provide automated testing wherever possible.

**Comment by D-Groenewegen** [comment]
Thanks for your efforts! 

> What makes things like this one harder to detect is probably that some implementations of features like the one described here are not as wide spread in usage

True, and it only requires a rather minor change on my part to fix or work around it. 

> $GLOBALS['smwgLinksInValues'] = SMW_LINV_OBFU;

Thanks for reminding me of this useful new feature. I added it to my local settings.

>  I removed the necessary [ encoding in #2351 

which incidentally, may solve another of my issues. I have a situation with an info parser that is returned by a template and part of what gets printed to the screen is this: 
`&#x005B;&#x005B;SMW::on]]`
(But obviously that's for another report, if things really do persist)

**Comment by mwjames** [comment]
> which incidentally, may solve another of my issues. I have a situation with an info parser that is returned by a template and part of what gets printed to the screen is this:

If you think that you found something else, please be so kind and isolate the issue on the sandbox. For the above described issue it just so happened that a simple template setup allowed to replicate the observation.

**Comment by D-Groenewegen** [comment]
> If you think that you found something else, please be so kind and isolate the issue on the sandbox. 

Now covered by Peter Bodifee #2392 - problem with info parser on table rows; placing the tag on the next line seems to work.

**Comment by kghbln** [comment]
> Now covered by Peter Bodifee #2392 - problem with info parser on table rows; placing the tag on the next line seems to work.

Perhaps you could help creating a non-working example on sandbox?
