### ISSUE TITLE
SMW API and JSON format do not support printout formats

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2368]
### Setup and configuration

- SMW version: 2.5.0 (dbbf3d1)
- MW version: 1.27.1 (2f9cdcc)
- PHP version: 7.0.15
- DB (MySQL etc.): MySQL 5.7.17

### Issue

Neither the SMW API nor the JSON format support printout formats, e.g. for 
```
{{#ask: [[Located in::Germany]]
 |?Area#sqmi
 |?Modification date#-F[d-m-Y]
 |format=json
}}
```

See https://www.semantic-mediawiki.org/w/api.php?action=ask&format=jsonfm&query=[[Located%20in%3A%3AGermany]]|%3FArea%23sqmi|%3FModification%20date%23-F[d-m-Y]

Is this intentional?

**Comment by kghbln** [comment]
Thanks for asking. I added the question tag for now, which may be changed to enhancement or bug once the answer is known.

**Comment by mwjames** [comment]
> Neither the SMW API nor the JSON format support printout formats, e.g. for

As for the API output, it is format agnostic and should not change with a specific printout formatting (we have two formats for the date type because due to legacy reason the timestamp as selected first as representation but is lacking expressiveness for the dates < 1970, therefore 2.4 (I think) added the raw serialization in order to support all dates that are stored in SMW).

An API consumer is informed about a requested printout format using:

```
            {
                "label": "Modification date",
                "key": "_MDAT",
                "redi": "",
                "typeid": "_dat",
                "mode": 1,
                "format": "-F[d-m-Y]"
            }
```

As for the JSON format, it uses the `QueryResult::serializeToArray` [0] which relies on the same agnostic representation [1] as the API output therefore `#...` attributes are not taken into account.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/JsonResultPrinter.php#L93
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Serializers/QueryResultSerializer.php#L132-L135

**Comment by s7eph4n** [comment]
So, yes, intentional. :)
Thanks!
