### ISSUE TITLE
Error: Call to a member function newInfoLinksProvider() on null

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2403]
### Setup and configuration

- SMW version: 2.5.0 (a41d159)
- MW version: 1.29.0-alpha (9a6a304)
- PHP version: 7.0.15
- DB (MySQL etc.): MySQL 5.7.17

### Issue

```
[32a8ccab200a7255a72d3a2b] /wiki/Property:Location Error from line 646 of /.../mw/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php: Call to a member function newInfoLinksProvider() on null

Backtrace:

#0 /.../mw/extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(345): SMWDataValue->getInfolinkText(integer, Linker)
#1 /.../mw/extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(278): SMWPropertyPage->subjectObjectList(array)
#2 /.../mw/extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(80): SMWPropertyPage->getPropertyValueList()
#3 /.../mw/extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php(185): SMWPropertyPage->getHtml()
#4 /.../mw/extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php(94): SMWOrderedListPage->showList()
#5 /.../mw/includes/actions/ViewAction.php(71): SMWOrderedListPage->view()
#6 /.../mw/includes/MediaWiki.php(497): ViewAction->show()
#7 /.../mw/includes/MediaWiki.php(291): MediaWiki->performAction(SMWPropertyPage, Title)
#8 /.../mw/includes/MediaWiki.php(860): MediaWiki->performRequest()
#9 /.../mw/includes/MediaWiki.php(521): MediaWiki->main()
#10 /.../mw/index.php(43): MediaWiki->run()
#11 {main}
```

Steps to reproduce the observation:
* Maps extension is not installed.
* Create page `Property:Location` with
```
[[Has type::Geographic coordinate]]
```
* Visit page `Property:Location`

**Comment by s7eph4n** [comment]
Hmm. I ran `rebuildData` and the error is gone. Probably forgot to run the script when I uninstalled Maps.

**Comment by mwjames** [comment]
> Hmm. I ran rebuildData and the error is gone. Probably forgot to run the script when I uninstalled Maps.

That should have nothing do with each other because the error `.../datavalues/SMW_DataValue.php: Call to a member function newInfoLinksProvider() on null` can only happen when `$this->dataValueServiceFactory` is not initialized but all DV object instantiation in SMW are done via `DataValueFactory` (which sets the `DataValueServiceFactory`) and so does `SMWPropertyPage->subjectObjectList`.

`DataValueServiceFactory` is one reason we no longer allow arbitrary DV object creation (as done so in https://github.com/SemanticMediaWiki/SemanticGlossary/commit/05872d8819925c86261aa93f4c11f7367859735b).

The objective is that we can inject services [0] into a DV instance without breaking the DV interface.

PS: I tried your example (without Maps) but couldn't replicate the error.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/src/Services

**Comment by s7eph4n** [comment]
Ok, so running `rebuildData` is probably unrelated. I'll keep my eyes open and reopen this issue if I see it again.
