### ISSUE TITLE
parser called again by SMW when DPL extension wants to update pages.

### ISSUE THREAD

**Issue by PeterBodifee** [SemanticMediaWiki/SemanticMediaWiki#2404]
### Setup and configuration

- SMW version: 2.5.0 (6ddb4c6)
- MW version: 1.27.1
- PHP version: 5.5.38
- DB (MySQL etc.): 5.5.50

### Issue

Extension DynamicPageList has the capability to update pages. Most likely not a frequently used feature, as I detected several permission issues, which I could solve..... But when eventually the page is parsed and encounters a DPL construct with `updaterules` it will call `doEditContent` to update the content of all applicable pages. In the initial part of `doEditContent` it goes down a path where the parser is called again. However the parser isn't stateless so an exception is thrown:

> MWException from line 6420 of /var/www/TST_prorail/127/includes/parser/Parser.php: Parser state cleared while parsing. Did you call Parser::parse recursively?

I tried using `doQuickEditContent` hoping I could avoid calling the parser again, but then I discovered that SMW attaches to hook 'NewRevisionFromEditComplete' (the hook is run in both `doEditContent` and `doQuickEditContent`) and in its process the parser is called.

Wondering if this problem can be solved at all. Any suggestions/ideas?

For more extensive report see also https://github.com/Alexia/DynamicPageList/issues/34

**Comment by mwjames** [comment]
> But, as we are using the SemanticMediaWiki extension which uses the hook 'NewRevisionFromEditComplete' SMW is now calling the parser.... :-(

To clarify we don't call the `Parser`, we call [0] which is to fetch the `ParserOutput` via  `prepareContentForEdit` which is normally provided before `NewRevisionFromEditComplete` is called . Of course, if some extension hooks into `NewRevisionFromEditComplete` and does some unexpected behaviour and `prepareContentForEdit` is not  available it may well be that the Parser is called out on the consequence that the `editinfo` isn't available [1, 2].

Copied from https://github.com/Alexia/DynamicPageList/issues/34

>Backtrace:
>#0 /var/www/TST_prorail/127/includes/parser/Parser.php(4835): Parser->lock()
#1 /var/www/TST_prorail/127/includes/content/WikitextContent.php(140): Parser->preSaveTransform(string, Title, User, ParserOptions)
#2 /var/www/TST_prorail/127/includes/page/WikiPage.php(2076): WikitextContent->preSaveTransform(Title, User, ParserOptions)
#3 /var/www/TST_prorail/127/extensions/SemanticMediaWiki/src/MediaWiki/EditInfoProvider.php(105): WikiPage->prepareContentForEdit(WikitextContent, NULL, User, string)
#4 /var/www/TST_prorail/127/extensions/SemanticMediaWiki/src/MediaWiki/EditInfoProvider.php(83): SMW\MediaWiki\EditInfoProvider->prepareContentForEdit()
#5 /var/www/TST_prorail/127/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(105): SMW\MediaWiki\EditInfoProvider->fetchEditInfo()
#6 /var/www/TST_prorail/127/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(71): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->fetchParserOutputFromEditInfo()
#7 /var/www/TST_prorail/127/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(246): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->process()
#8 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks{closure}(WikiPage, Revision, boolean, User)
#9 /var/www/TST_prorail/127/includes/Hooks.php(195): call_user_func_array(Closure, array)
#10 /var/www/TST_prorail/127/includes/page/WikiPage.php(2324): Hooks::run(string, array)
#11 /var/www/TST_prorail/127/extensions/DynamicPageList/classes/DynamicPageList.php.local-mod(1043): WikiPage->doQuickEditContent(WikitextContent, User, string)

> #11 /var/www/TST_prorail/127/extensions/DynamicPageList/classes/DynamicPageList.php.local-mod(1043): WikiPage->doQuickEditContent(WikitextContent, User, string)

Since this involves another extension, I'm not sure what you want us to do since we expect to run on the `NewRevisionFromEditComplete` event.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/EditInfoProvider.php#L83
[1] https://github.com/wikimedia/mediawiki/blob/master/includes/page/WikiPage.php#L1598-L1599
[2] https://github.com/wikimedia/mediawiki/blob/master/includes/page/WikiPage.php#L1970

**Comment by kghbln** [comment]
I may be wrong but from my memory about DPL you can do everything that it can do with SMW too. So a quick way out may be to just uninstall DPL unless some migration still has to be done.

There are indeed extensions around that do not play well together but judging from James' comment the issue is probably somewhere with DPL rather than SMW.

**Comment by PeterBodifee** [comment]
@mwjames @kghbln Thank you for your feedback.
As for SMW capabilities we are very pleased, DPL we use for some odd cases, where I haven't figured out how to do this with the (new) version of SMW (yet). And in those cases DPL and SMW co-exitst nicely.  
I am not aware of SMW being able to select pages based on criteria and then allow om those pages to select text with regex and replace. DPL promises to make that happen. It is not something we offer our regular users, this is more for the bureacrats to assist in making bulk content updates for well planned migrations.

**Comment by mwjames** [comment]
> #11 /var/www/TST_prorail/127/extensions/DynamicPageList/classes/DynamicPageList.php.local-mod(1043): WikiPage->doQuickEditContent(WikitextContent, User, string)

Two things:

*  I'd be very wary about `WikiPage::doQuickEditContent` as this function no longer exists in MW 1.28/1.29 [0]
* Calling an update (`doEdit` etc.) from within a parser function should be avoided at all costs as it is very likely that a `Parser::lock` is a consequence of it

[0] https://github.com/wikimedia/mediawiki/blob/REL1_28/includes/page/WikiPage.php

**Comment by PeterBodifee** [comment]
Thanks for the heads up @mwjames on `doQuikEditContent`, I was just experimenting.
On your second point, I wonder if any one got the DPL `updaterules` feature working (I ran into several bugs even before it starts to try the actual function). Maybe it works when the hook `NewRevisionFromEditComplete` isn't used...
At this point I will need to find another way of getting the job done. Wished that extension MassEditRegex has more flexibility on selecting pages... that would do the job too.

**Comment by kghbln** [comment]
> MassEditRegex

Indeed a great one. Perhaps using a [bot](https://www.mediawiki.org/wiki/Manual:Pywikibot) will be more suitable in you environment. There are some around afaik but I cannot exactly tell which one.

**Comment by PeterBodifee** [comment]
My use case is that we are going to change user names as we are switching to Single Sign On in the near future. The content editors use e.g.[[Editor::User:Peter Bodifee]] all over the place. 

I discovered that MassEditRegex has a backlinks option and by putting 'User:Peter Bodifee' in the pages to edit, I can change the value of property Editor for this particular user on all pages in one run. At least preview shows it finds all pages in the main namespace, but execute (run in browser) fails with 'Error: Unknown error during request to MediaWiki API.'  Will report in phabricator.
