### ISSUE TITLE
Special property "Language code" and its language code validation

### ISSUE THREAD

**Issue by simonschlosser** [SemanticMediaWiki/SemanticMediaWiki#2455]
### Setup and configuration

- SMW version: ???
- MW version: 1.28
- PHP version: 7.0
- DB (MySQL etc.): MySQL

### Issue
The issue refers to a discussion in the SMW user mailing list [2].
In short: the special property 'language code' does not accept to assign 'no' as a value (Norwegian). However, in general it is a known language tag of MediaWiki, see e.g. [3]. 

The current approach of testing whether a language code is acceptable for the language code property employs the method Language::isSupportedLanguage, it would be better to use Language::isKnownLanguageTag instead.

Here the proposal from the mailing list:
> As for Property:Language_code, first we convert any user input with the help of wfBCP47 [0] and later ask MediaWiki ( `Language::isSupportedLanguage` [1] ) to tell us whether it is a supported language or not using the language code as identifying factor.
We rely on MediaWiki to tell us that "no" is a supported language but maybe a better method is Language::isKnownLanguageTag instead of Language::isSupportedLanguage [1].
L212

 [0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Localizer.php#L225
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Localizer.php#L203-
[2] http://wikimedia.7.x6.nabble.com/Language-code-property-does-not-identify-quot-no-quot-as-a-supported-language-code-td5074770.html
[3] https://github.com/wikimedia/mediawiki/blob/master/languages/data/Names.php

**Comment by kghbln** [comment]
Thanks for bringing up this issue.

I do not know why but nowadays I only get half of the e-mails send to the mailing lists. They do not even end up in my spam filter. Well that's a different story. Thank you for linking to the list archive.

I suspect that "no" is still in the "Names.php" file for legacy reasons. I know for sure that MediaWiki dropped "no". I have been named a fascist bastard [sic!] out of the blue back in 2008 after politely informing that MediaWiki will only use "nb" and "nn" in the future in some discussion on Wikipedia. The reason for the switch if I remember correctly: What is "no"? Bokmål, Nynorsk? Exactly! As even [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) states "no" is a macro language.

We will never get translations for "no" so this issue is indeed if SMW accepts something like "no" etc. for local forks. If it is just a tiny adjustment ... Why not?

**Comment by mwjames** [comment]
@Nikerabbit @nemobis Any insights on the no vs. nb controversy and a possible change on our side from using `Language::isKnownLanguageTag` instead of `Language::isSupportedLanguage`?

**Comment by Nikerabbit** [comment]
`Language::isSupportedLanguage`: _Checks whether any localisation is available for that language tag in MediaWiki_
`Language::isKnownLanguageTag`: _Returns true if a language code is an IETF tag known to MediaWiki_

I am not sure of the context, but the first function is usually used to determine whether language can be used as an interface language. Latter one seems more appropriate here. Do note that the MediaWiki knows more codes if the CLDR extensions is installed.

**Comment by kghbln** [comment]
Thanks for your input. The reason is/was that some external third party software uses "no" and thus does not integrate with MediaWiki's "nb" or "nn".

**Comment by kghbln** [comment]
Will be served with SMW 2.5.3
