### ISSUE TITLE
Warning: Parameter 1 Hooks\{closure}() expected to be a reference, value given in ... Hooks.php on line 195

### ISSUE THREAD

**Issue by sereAbi** [SemanticMediaWiki/SemanticMediaWiki#2456]
### Setup and configuration

- SMW version: 2.5 / 2.5.1
- MW version: 1.28.2
- PHP version: 5.5.38
- DB (MySQL etc.): MySQL (XAMPP 7.1.2)

### Issue

Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /Applications/XAMPP/xamppfiles/htdocs/mediawiki-1.28.2/includes/Hooks.php on line 195

This line shows up multiple times in all the pages of a freshly installed empty mediawiki on local machine.

The semantic media wiki pages are showing up, and enableSemantic is set to localhost.
Tried both with 2.5 and 2.5.1 (via composer.phar)

Any clue?
Thanks a lot.

**Comment by mwjames** [comment]
> - MW version: 1.28.2
> - PHP version: 5.5.38
> - DB (MySQL etc.): MySQL (XAMPP 7.1.2)

I think something isn't entirely correct with you provided information, XAMPP 7.1.2 refers to PHP 7.1.2 which also means that your issue is related to [0] as outlined in [1].

> Warning: Parameter 1 to
> SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected
> to be a reference, value given in
> /Applications/XAMPP/xamppfiles/htdocs/mediawiki-1.28.2/includes/Hooks.php on
> line 195

Currently only 1.29+ is compatible to be run on 7.1.* [0] , SMW is tested and passes its tests on 7.1 as recorded in #1733.

[0] https://phabricator.wikimedia.org/T153505
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility

**Comment by kghbln** [comment]
Thanks for reporting. Indeed the setup should be clarified. I added the "discussion" label for the time being.

**Comment by sereAbi** [comment]
I'm sorry to have this wrong. I was running php 7.1.2.
I tried to remove the value passing (&$this) problem as pointed out, which I found in:
- ./src/MediaWiki/Specials/Browse/ContentsBuilder.php;
- ./src/SQLStore/PropertyTableDefinitionBuilder.php;
With no success.

I downgraded to php 5.6.30, and all the warning disappeared as promised.
Thanks.

**Comment by kghbln** [comment]
Thanks for clarifying!

**Comment by hexmode** [comment]
I wouldn't say this is invalid. For instance, MW core (the code that will turn into MW 1.31) currently calls the `OutputPageParserOutput` hook:
``` php
Hooks::run( 'OutputPageParserOutput', [ &$this, $parserOutput ] );
```
And, SMW declares its hook:
``` php
$this->handlers['OutputPageParserOutput'] = function ( &$outputPage, $parserOutput ) {
```
Which all seems right.

However this ends up in the following warning with php7:
```
Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given
```
Removing the `&` gets rid of the warning in php 7 and the code continues to work in php 5.

**Comment by mwjames** [comment]
Your premise is wrong. If you run 7.1+ then you have to use at least
MW 1.29 due to [0] (as it is noted in [1]), any earlier release will
hit the `&$this` reference issue.

The hook definition is correct as long as you are wary about the
outlined boundaries.

PS: Our tests pass on both 5.6 (MW ???) and 7.1 (MW 1.29) for the
given environment, so I'm pretty confident that we are not missing
something (those hooks are tested).

[0] https://phabricator.wikimedia.org/T153505
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility

Cheers

**Comment by mwjames** [comment]
@hexmode Did you read my comment? Did the comment suffice?

**Comment by hexmode** [comment]
mwjames <notifications@github.com> writes:

> @hexmode Did you read my comment? Did the comment suffice?

I did.  I haven't had time to check my setup to see if I can pinpoint
the problem.  I want to do that before I throw in the towel.

I had the same problem with another extension and they said it shouldn't
be an issue as well.
