### ISSUE TITLE
"edit with form link" does not show up after page creation until runjobs.php is triggered

### ISSUE THREAD

**Issue by ubibene** [SemanticMediaWiki/SemanticMediaWiki#2468]
### Setup

- MW version: 1.27.3 
- DB (MySQL etc.): 5.7.17
- PHP version:  5.6.30
- SMW version:  2.5.1
- Page Forms 4.1.1
- Browsers and versions (if applicable): NA

### Issue

1) create a new page with a form
2) save it
3) You cannot see the "edit with form"on the freshly created page   , but 
you can see the "edit" link, even when logged as a non-sysop user and
having

$wgGroupPermissions['*']['viewedittab']=false;
$wgGroupPermissions['sysop']['viewedittab']=true;

in LocalSettings.php

also in my case $wgJobRunRate=0 , a cron task calls runJobs

4) add  action=purge to the url does nothing, "edit with form" does not 
show up
5)call runJobs, refresh the page and then "edit with form" shows up

Note that pages which had been already created with the form show the 
"edit with form link"

**Comment by osnard** [comment]
Hi!

This is probably an issue of PageForms, not of SemanticMediaWiki itself. You may want to file the bug there, if you did not already.

I think the problem originates from this commit: https://gerrit.wikimedia.org/r/#/c/212726/1/includes/page/WikiPage.php

"LinksUpdate" is now run deferred. So the "categorylinks" table is not being updated directly when the page is saved. PageForms relies on the information in "categorylinks" table in order to show the "Edit with form" tab.
A simple fix would be to write a little callback for "ArticleSaveComplete" hook and run the "LinksUpdate" job manually.

--
Robert

**Comment by ubibene** [comment]
Many thanks Robert, I'll quote your answer in a post to the SMW user list 

Cheers

Michel

**Comment by kghbln** [comment]
@yaronkoren [is in the loop](http://wikimedia.7.x6.nabble.com/Page-Forms-creating-a-page-using-a-form-the-edit-with-form-does-not-show-tp5073337p5075008.html)
