### ISSUE TITLE
smw_querytoolarge needs PLURAL support

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#250]
Import from https://phabricator.wikimedia.org/T20515

mediawiki:smw_querytoolarge should be using PLURAL,
depending on the number of items in the list in $1.

--  Purodha Blissenbach 2009-04-19 09:34:03 UTC

**Comment by mwjames** [comment]
@kghbln ?

**Comment by kghbln** [comment]
@JeroenDeDauw Still have no idea how SMW compiles this message.

**Comment by mwjames** [comment]
@kghbln Can we kick this one?

**Comment by kghbln** [comment]
We need an additional parameter here that allows to count the number of query conditions displayed in $1 in order to be able to change

"smw_querytoolarge": "The following query conditions <code>$1</code> could not be considered due to this wiki's restrictions on query size or depth."

to

"smw_querytoolarge": "The following query {{PLURAL:$2|condition|conditions}} <code>$1</code> could not be considered due to this wiki's restrictions on query size or depth."

While changing the system message as such to support plural is no problem for me I do not know how to make SMW count the number of different conditions.

Since the error reporting was improved in SMW 2.4 it might not indeed be the right time to tackle this issue.

**Comment by kghbln** [comment]
Back when I figured that the same applies to the messages "smw_noqueryfeature", "smw_noconjunctions" and "smw_nodisjunctions". Nowadays I believe this is not the case since `$1` in these three messages just present a uncountable chuck of "ignored" ask query code.
