### ISSUE TITLE
Inverse properties with #show not working

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#2548]
### Setup and configuration

- SMW version: 2.5.3
- MW version: 1.27.x
- PHP version: 7
- DB (MySQL etc.): MySQL

### Issue

According to https://www.semantic-mediawiki.org/wiki/Help:Inverse_properties, inverse properties should be working with both `#ask` or `#show`.

As shown in https://sandbox.semantic-mediawiki.org/wiki/Daren_Welsh, this seems to be not the case.

**Comment by mwjames** [comment]
> As shown in https://sandbox.semantic-mediawiki.org/wiki/Daren_Welsh, this
> seems to be not the case.

Your premises is incorrect because `{{#show: -Has father::Daren Welsh
}}` is not going to work due to #show [0] only excepting a page entity
as condition and not any other construct.

As for #show, `{{#show: Humpty Dumpty |?-Has father }}` would work and
if we take aside the questionable usefulness of such construct, the
condition has to be a page type entity.

[0] https://www.semantic-mediawiki.org/wiki/Help:Inline_queries#Parser_function_.23show

**Comment by kghbln** [comment]
There was indeed a glitch in the docu which I have now [amended.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AInverse_properties&type=revision&diff=52298&oldid=50295)
