### ISSUE TITLE
"Links to" special property?

### ISSUE THREAD

**Issue by kriegfrj** [SemanticMediaWiki/SemanticMediaWiki#2566]
I had an idea today for use in our internal SMW-enabled wiki where it might be nice to include a list of pages that link to this page. I know that there is the "what links here" link already, but I would like to embed the results into the body of the page. If SMW provided built-in property definitions for links (similar to what it does for Display title of, for example), then it would be possible to do all sorts of queries on pages that link. So anytime you do a plain internal MW link, behind the scenes it is equivalent to writing [[Links to::<page>]], with the property "Links to" having a type of "Page".

It wouldn't be too difficult to do this manually by defining the property and always using [[Links to::<page>]] instead of simply [[<page>]], but this is hard to retro-fit to an existing large wiki. And it also doesn't seem that it would be particularly hard to do automatically as a special property.

**Comment by kghbln** [comment]
MediaWiki is currently removing such functionality which works similarly, i.e. magic links. When you have "Links to" stored on a page you still have to query on the linked pages for them, so I guess it will be better to annotate and when ask using the [incoming format](https://www.semantic-mediawiki.org/wiki/Help:Incoming_format).

**Comment by mwjames** [comment]
> So anytime you do a plain internal MW link, behind the scenes it is equivalent to writing [[Links to::]], with the property "Links to" having a type of "Page".

If I understand the issue correctly, you want SMW to parse standard links like [[ ... ]] (i.e. not to be mistaken with [[ :: ]])  and create annotations for each of them in order to map those links to a `Links to` property.

I'm not sure that the performance implication would warrant such extension of the standard parsing logic. You may be able to use `LinkBegin` [0] to fetch such links when MediaWiki is parsing them from the text source but again, I would be cautioned about using that hook in SMW-core as it would be called on each instance MediaWiki is trying to make a link and therefore is unlikely to be performant.

Maybe MediaWiki's `Parser` object already has a suitable method or handler to fetch parsed links and allows to iterate over them in a post process. It should be noted that I haven't looked at this approach so I can't say for sure, someone else might find a better (and by this I mean performance related) approach to fetch those links without SMW to re-parse the raw text itself.

[0] https://www.mediawiki.org/wiki/Manual:Hooks/LinkBegin as "Used when generating internal and interwiki links in Linker::link(), before processing starts."

**Comment by mwjames** [comment]
What are we going to do with this issue? Is something missing or is the provided answer insufficient?

**Comment by WolfgangFahl** [comment]
At BITPlan we use http://wiki.bitplan.com/index.php/Template:Link and http://wiki.bitplan.com/index.php/Template:WhatLinksHere to solve this problem and only use the standard Link syntax where we are not interested in the values. At SMWCon2017 Fall Rotterdam I will also show a tagcloud Version of this.

**Comment by mwjames** [comment]
I'm inclined to close this issue for reasons already cited, if your interested in a technical (instead of a process) solution then you may propose a PR in [0] where it is easier to add an extra `LinkToPropertyAnnotator` and allow potential users to enabled/disabled it per request.

[0] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties

**Comment by kriegfrj** [comment]
No problem. It was just a thought.

**Comment by Sophivorus** [comment]
MediaWiki already has the [pagelinks table](https://www.mediawiki.org/wiki/Manual:Pagelinks_table) to keep track of all links between pages. Wouldn't it be possible for Semantic MediaWiki to reuse this table? Perhaps it would require a new syntax (hopefully not)? Something like:

```
{{#ask:
[[Category:Foo]]
[[Property::Value]]
[[Links to:::Some page]]
}}
```

**Comment by WolfgangFahl** [comment]
The issue would have to be reopened which i am in favor of.
