### ISSUE TITLE
Forced to rebuild smw data upon upgrade to 2.5.x with SPARQL backend

### ISSUE THREAD

**Issue by Reasno** [SemanticMediaWiki/SemanticMediaWiki#2587]
### Setup and configuration

- SMW version:2.5.3
- MW version:1.29.0
- PHP version:HHVM 3.20.2
- DB (MySQL etc.):MySQL 5.6

### Issue

Recently I upgraded SemanticMediaWiki from 2.4.x to 2.5.3 for a group of wikis. It turns out (after update.php is run) all wikis with SQL store worked out of box, but other wikis using SPARQL store (I am using blazegraph) lost all SMW data. I was forced to run rebuildData.php to get them back.

Is this an expected behavior or did I do something wrong?

Thanks!

**Comment by kghbln** [comment]
Well, blazegraph loosing all semantic data sounds a bit odd. Which version are you using?

In general I always do a full data rebuild after upgrading from one major version of SMW to the next. Also having to run "setupStore.php" or "update.php" respectively means that there were schema changes so it is best to rebuild data for the relational backend anyways, too.

**Comment by mwjames** [comment]
> Is this an expected behavior or did I do something wrong?

Looking at the diff [0, 1] of the `Exporter` 2.4/2.5, one can see that we extended the use of `smwgExportBCNonCanonicalFormUse` to ensure that we always export the RDF in a canonical form (means in English, so something like `Special:URIResolver` remains `Special:URIResolver` and is not transformed into a content localized string like `特殊:URI分解器`) unless the BC setting states otherwise.

Machine readable content is expected to be interchangeable, generating resource links that dependent on non-canonical links defies the idea of being exchangeable.

I hypothesize that in 2.4 your triple store used `zh-hans` encoded resource links (e.g. `特殊:URI分解器`) where in 2.5 it should contain something like `Special:URIResolver` hence the need for a remapping that also requires to run `rebuildData.php` for exported data.

## Example output

`$wgLanguageCode = "zh-hans";`, `$smwgExportBCNonCanonicalFormUse = true;`

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:swivt="http://semantic-mediawiki.org/swivt/1.0#" xmlns:wiki="http://example.org/id/" xmlns:category="http://example.org/id/-25E5-2588-2586-25E7-25B1-25BB-3A" xmlns:property="http://example.org/id/-25E5-25B1-259E-25E6-2580-25A7-3A">
<owl:Ontology rdf:about="http://127.0.0.1:8080/mw-master/index.php/%E7%89%B9%E6%AE%8A:ExportRDF/Berlin">
<swivt:creationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2017-08-06T14:57:23+02:00</swivt:creationDate>
<owl:imports rdf:resource="http://semantic-mediawiki.org/swivt/1.0"/>
</owl:Ontology>
<swivt:Subject rdf:about="http://example.org/id/Berlin">
<rdf:type rdf:resource="http://example.org/id/-25E5-2588-2586-25E7-25B1-25BB-3ASample_pages"/>
<rdf:type rdf:resource="http://example.org/id/-25E5-2588-2586-25E7-25B1-25BB-3ACity"/>
<rdfs:label>Berlin</rdfs:label>
<rdfs:isDefinedBy rdf:resource="http://127.0.0.1:8080/mw-master/index.php/%E7%89%B9%E6%AE%8A:ExportRDF/Berlin"/>
<swivt:page rdf:resource="http://127.0.0.1:8080/mw-master/index.php/Berlin"/>
<swivt:wikiNamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</swivt:wikiNamespace>
<swivt:wikiPageContentLanguage rdf:datatype="http://www.w3.org/2001/XMLSchema#string">en</swivt:wikiPageContentLanguage>
```

`$wgLanguageCode = "zh-hans";`, `$smwgExportBCNonCanonicalFormUse = false;`

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:swivt="http://semantic-mediawiki.org/swivt/1.0#" xmlns:wiki="http://example.org/id/" xmlns:category="http://example.org/id/Category-3A" xmlns:property="http://example.org/id/Property-3A">
<owl:Ontology rdf:about="http://127.0.0.1:8080/mw-master/index.php/Special:ExportRDF/Berlin">
<swivt:creationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2017-08-06T14:59:08+02:00</swivt:creationDate>
<owl:imports rdf:resource="http://semantic-mediawiki.org/swivt/1.0"/>
</owl:Ontology>
<swivt:Subject rdf:about="http://example.org/id/Berlin">
<rdf:type rdf:resource="http://example.org/id/Category-3ASample_pages"/>
<rdf:type rdf:resource="http://example.org/id/Category-3ACity"/>
<rdfs:label>Berlin</rdfs:label>
<rdfs:isDefinedBy rdf:resource="http://127.0.0.1:8080/mw-master/index.php/Special:ExportRDF/Berlin"/>
<swivt:page rdf:resource="http://127.0.0.1:8080/mw-master/index.php/Berlin"/>
<swivt:wikiNamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</swivt:wikiNamespace>
<swivt:wikiPageContentLanguage rdf:datatype="http://www.w3.org/2001/XMLSchema#string">en</swivt:wikiPageContentLanguage>
```
[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/ff40c48bc0e8a90189b781d807694492aa8aab4d
[1] #1813

**Comment by Reasno** [comment]
Thanks. We are indeed using zh-hans. This must be the case.

**Comment by kghbln** [comment]
@Reasno and @mwjames Thanks a lot for you input and feed-back!
