### ISSUE TITLE
SMW breaks formatting of Cite references.

### ISSUE THREAD

**Issue by Alexia** [SemanticMediaWiki/SemanticMediaWiki#2671]
### Setup and configuration

- SMW version: 2.5.3
- MW version: 1.29.1
- PHP version: 7.0

### Issue
When SMW is enabled it causes the ending bracket of a Cite reference to no longer be part of the A HREF link.

```
<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1</a>]</sup>
```

That bracket should be inside the A HREF.

Example: https://meeseeks.gamepedia.com/Zelda_Test

**Comment by kghbln** [comment]
Thanks for reporting. I have seen this issue on many of my wikis but blamed the Foreground skin. This is however not enabled on your wiki so ... Moreover this issue is not isolated to the references. It affects all appearances of a trailing `]` e.g. also my regular wiki signature which is `[[kgh]]`. Obviously I did not expect SMW to be the "transgressor".

**Comment by Alexia** [comment]
I only figured it out because I disabled all extensions then went through individually enabling extensions one by one(only enabling one at a time) until I figured out which one was causing it.

**Comment by mwjames** [comment]
> That bracket should be inside the A HREF.

I took me a moment to understand the issue (and I had to install Cite) to create an actual reproducible use case. The issue has its root cause in the fact that the `#cite` parser function encodes its text components such as `[` and `]` in a manner of:

```
<sup id="cite_ref-1" class="reference">[[#cite_note-1|&#91;1&#93;]]</sup>
```

Unfortunately, `#cite` uses the same encoding strategy as we do for the `]` and when the `InTextAnnotationParser` sees a text with `&#93;` it believes that it is a string itself has encoded earlier to distinguish a simple `[ ... ]` from a `[[ ... ]]`. There was a similar issue with `&#91;` (#2193) hence I'm switching to a different encode string for `]` (`&#x005D;`) in #2672.

I do hope that we are not creating some kind of hidden regression therefore I expect some rigorous pre-release testing since changing parse related code shouldn't be done lightly. 
 
> Moreover this issue is not isolated to the references. It affects all appearances of a trailing ] as part of the visible link display e.g. also my regular wiki signature which is [[kgh]]. 

Not sure I understand this part.

Is there a way to create a use case without Cite, currently I don't have an integration test for the cited issue (unit test, yes but that's not the same as an integration test) and we DO want to avoid the issue in future.

**Comment by kghbln** [comment]
> Not sure I understand this part.

Ah, I thought it was the link, however MediaWiki adds `[[Utilisateur:Kghbln|&#91;&#91;kgh&#93;&#93;]]` thus I see the same behaviour due to the `&#93;``even with Cite disabled which I have just [done on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Citable). So yes, it is the `&#93;` bringing pain.

**Comment by kghbln** [comment]
Yeah, avoiding the `&#93;` has solved the issue, with or without the Cite extension enabled since the issue was the `&#93;` whatever software it may use, MediaWiki core, Cite extension, etc. @mwjames Thanks for the effort fixing it and @Alexia thanks for taking the time to identify and report.

**Comment by kghbln** [comment]
I have back-ported the fix to the 2.5.x branch so the fix will serve with SMW 2.5.5!

**Comment by mwjames** [comment]
We should have an integration test where something like `[[Foo|&#91;&#91;Foo&#93;&#93;]]` is tested which should cover the initial issue without having to install `Cite`.

**Comment by mwjames** [comment]
> We should have an integration test where something like [[Foo|&#91;&#91;Foo&#93;&#93;]] 

Done with #2683
