### ISSUE TITLE
Support for `Allows value` to display translatable values

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2769]
The issue is about __display__ characteristics not storing. Storing and comparing of "allowed values" will always happen against the canonical form (i.e. the one it is stored with `[[Allows value::Bar]]`).

## Issue

Currently, `Allows value` defines fixed constraint values that can only be displayed in its canonical form.

It is proposed to use `MediaWiki:Smw_allows_value-` as prefix so that a translatable literal (for `_txt` type values) can be represented in the form of:

* `Property:Foo` is defined as `[[Has type::Text]]` with `[[Allows value::Bar]]` 
* `Bar` as literal is expected to match  `MediaWiki:Smw_allows_value-Bar` and its language pairs such as `MediaWiki:Smw_allows_value-Bar/fr` or `MediaWiki:Smw_allows_value-Bar/ja` 

### Page type values

The problem with page type values is that it is a resource and contains two parts a link and a link text `[[Link|Link text]]`. What is the expected behaviour?

**Comment by Nikerabbit** [comment]
Won't this cause problems if two different properties use same allowed value, making it impossible to use different translations for them? That could be solved by adding the name of the property to the string key.

I would be happy to add integration to Translate extension that automatically creates a group which allows translating all registered allowed values.

**Comment by JeroenDeDauw** [comment]
`MediaWiki:Smw_allows_value-Bar/fr` is that a wiki page? If so, why use a wiki page and not extend the wikitext somehow? Perhaps something like `[[Allows translated value::fr/BarFR]]`?

I'm very much not up to speed with this stuff so might be missing the obvious here or proposing something that totally does not work or is a bad idea.

**Comment by jaideraf** [comment]
> [[Allows translated value::fr/BarFR]]

Or `[[Allows value::Bar@en]]`, like it is done in [monolingual text datatype](https://www.semantic-mediawiki.org/wiki/Help:Type_Monolingual_text).

**Comment by Nikerabbit** [comment]
I don't see how you would link either of those to the canonical Bar while also specifying the translation. While easier for users to specify all translations in one page, managing those programmatically is a tad harder because of the variety of different ways the pages can be formatted, not alone templates.

**Comment by JeroenDeDauw** [comment]
Right, I'd need to be something like `[[Allows translated value::BarCanonical/fr/BarFR]]`. I agree that this kind of notation is not ideal.

Having one page per canonical value seems reasonable. If the title holds the canonical form, then you could have a content in the format:

```
fr: fooFr
nl: fooNl
```

Or perhaps a JSON map. In both cases pages of this type could have their own MediaWiki content model that translates the data into SMW datasets. This would also make it easy to have a GUI for editing these values rather than forcing people to use text (while still allowing text based editing if desired).

Putting the canonical form in the title does actually not seem appealing to me. I rather have it in the page. And if you have it in the page, then you can just as well have all value restrictions for a single property there. In which case a format such as this is cool:

```
{
    "CannonicalA": {
        "fr": "frVariantA"
    },
    "CannonicalB": {
        "nl": "nlVariantB"
    },
}
```

Or perhaps

```
{
    {
        "canonicalA",
        "fr": "frVariantA"
    },
    {
        "CannonicalB",
        "nl": "nlVariantB"
    },
}
```

**Comment by mwjames** [comment]
> different translations for them? That could be solved by adding the name of the property to the string key.

Good point, if we assume that `Property:Foo` with `[[Allows value::Bar]]` and `Property:Foobar` and `[[Allows value::Bar]]` and the declared  value constraint is a different thing and is not interchangeable in its canonical interpretation.

Is a constraint value context bound (i.e. is bound to the property entity)? Do we have an example where a translation would be different for the same canonical constraint where a different property context would determine its label representation?

>  Perhaps something like [[Allows translated value::fr/BarFR]]?

I don't think we want to introduce a new syntax here. As @jaideraf outlined the excepted approach for an in-page language annotation syntax is `Something@lang` introduced with the monolingual type. 

> Or something like [[Allows value::Bar@fr]]

I thought about this but I think it is going to be difficult (in terms of editing practice) to maintain such constructs for a n:m relation on a single page. Take for example [0], here it is manageable on a 1:n relation but this would become less clear when you have 10 allows value and you want to maintain each in 10 different languages.

I don't envision users to actually add 10 different languages after all we are not Wikidata but I'm looking for a approach that is stable and easily to follow without introducing a performance penalty on either the page or the lookup.
 
Another issue is when values are defined through a `Allows value list` [1, 2] where the list is only kept as a reference on the property page.

> Or perhaps a JSON map. In both cases pages of this type could have their own MediaWiki content model that translates the data into SMW datasets. 

Yes, that seems to be the end goal where a JSON schema can direct a form and allows an API to update such page in a structured way without extra parsing.

While the vision is good, I don't see this happening in near future:

* It would break the existing editing practice for property pages if only the JSON schema is allowed
* Would require resources (man power and hours) and effort that I don't see to be available

I suggest turning this into a separate RFC (including some more fine grained discussion about feasibility and feature expectation).

> Putting the canonical form in the title does actually not seem appealing to me. I rather have it in the page. 

See above comment about maintainability.

> Which leads me to another idea: if the data is stored in such a format, why not put it on the property pages directly. The property pages could have their own content model. This can be done in a compatible way, where the handling code detects the JSON and continues handling the wikitext as usual.

Mixing JSON with wikitext? I don't think this is a good idea, having two editing forms one for JSON and one for wikitext seems a more amendable suggestions to avoid confusion towards the end-user.

See `EditPage::showEditForm:fields`.

> Putting the canonical form in the title does actually not seem appealing to me.

We do this in other places [3, 4] so this is somewhat of common practice.

[0] https://sandbox.semantic-mediawiki.org/wiki/Attribut:P106
[1] https://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_publication
[2] https://sandbox.semantic-mediawiki.org/wiki/MediaWiki:Smw_allows_list_Publication_categories
[3] https://www.semantic-mediawiki.org/wiki/Help:Import_vocabulary#Selected_list_of_imported_vocabularies
[4] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Allows_value_list

**Comment by JeroenDeDauw** [comment]
> I thought about this but I think it is going to be difficult (in terms of editing practice) to maintain such constructs for a n:m relation on a single page. Take for example [0], here it is manageable on a 1:n relation but this would become less clear when you have 10 allows value and you want to maintain each in 10 different languages.

I think this can work just fine depending on how you go about it. From a UI perspective you can certainly have 10 sections, each one being about a constraint, having a list with translations. If this is stored in JSON then directly editing that would also not be difficult, and likely a lot easier than the wikitext people currently are dealing with in many places.

> Mixing JSON with wikitext? I don't think this is a good idea, having two editing forms one for JSON and one for wikitext seems a more amendable suggestions to avoid confusion towards the end-user.

Not sure mixing is the right word for what I have in mind. I think it would be bad to use wikitext in this JSON or use the JSON inside of wikitext. What I'm suggesting is having a page that has two parts:

* optional JSON blob that defines the property (starting with value constraints) and can be edited via UI elements
* optional wikitext for showing things on the page or defining property stuff in (legacy) wikitext form

Typically people would choose a single way to do things. And for new users, it seems likely many won't even care to know about the difference and just use the UI.

> * It would break the existing editing practice for property pages if only the JSON schema is allowed

Indeed. I think this should be avoided, and can be avoided relatively easily.

> * Would require resources (man power and hours) and effort that I don't see to be available

It does not seem that big of a task to me. Breaking it down:

* New content type for property pages
* Decide on JSON structure (or other notation) to use 
* Detect this JSON in the content and convert it into semantic data rather than parsing it as wikitext
* (optional) Create an editing interface on top of this content type and JSON structure to gain eternal love by users

That is only 2 required coding tasks, compared to at least 1 of comparable size if you go with the subpage approach. And if you go with the subpage one, it is a step away from having the property easily editable on a single page.

On top of that I'd be happy to do some or even most of the work.

But before getting to that it'd be nice to get some feedback from the users.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
