### ISSUE TITLE
RDF export escapes non-ascii URLs and property names

### ISSUE THREAD

**Issue by changwoo** [SemanticMediaWiki/SemanticMediaWiki#2781]
### Setup and configuration

- SMW version:2.5.4
- MW version:1.29
- PHP version:7.0.19
- DB system (MySQL, Blazegraph, etc.) and version:mariadb 10.2.9

### Issue:

I'm using non-ascii characters for SMW properties and it seems to work great. But in the exported RDFs  those non-ascii names are escaped using non-standard `-XX` form. Like this:

```
<swivt:page rdf:resource="http://localhost:8080/wiki/-EA-B0-80-EA-B3-B5_-28001-29_-28-ED-95-9C-EA-B5-AD-EC-96-B4-EA-B8-B0-EC-B4-88-EC-82-AC-EC-A0-84_27947-29"/>
```
```
<wiki:Property-3A-EA-B0-88-ED-80-B4-3A-EB-9D-BC-EC-9D-B4-EC-84-A0-EC-8A-A4 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">CC BY-SA 2.0 KR</wiki:Property-3A-EA-B0-88-ED-80-B4-3A-EB-9D-BC-EC-9D-B4-EC-84-A0-EC-8A-A4>
```

But AFAIK they don't have to be escaped at all because,

- according to the RFC3986, the default URL encoding is UTF-8. So I think URLs don't have to be escaped. Or at least URLs should be encoded in the standard `%XX` form, not `-XX` form.
- And according to the XML spec, all the Unicode word characters can be used for tag names. Thus such characters don't have to be escaped.

**Comment by mwjames** [comment]
There is some history on the encoding issue but since I'm pressed with time during my weekend sprint, I can only add some quick notes and may have to come back to this in a week or so.

Generally, the generated XML (RDF) is only expected to be consumed by a "machine" not a human therefore readability isn't really required as long as the generate XML is consistent over the encoded content.

> And according to the XML spec, all the Unicode word characters can be used for tag names. Thus such characters don't have to be escaped.

Not really, and if I recall correctly tags that contain a `:` are causing issues.

> according to the RFC3986, the default URL encoding is UTF-8. So I think URLs don't have to be escaped. 

See [0] on whether this can solve your issue on the UTF-8 aspect or not. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1210-L1224

**Comment by changwoo** [comment]
>     And according to the XML spec, all the Unicode word characters can be used for tag names. Thus such characters don't have to be escaped.
> 
> Not really, and if I recall correctly tags that contain a : are causing issues.

Yes, I understand colons need be escaped in tagnames as a colon is for XML namespaces. And maybe also other symbols do. My concern was about non-ascii word characters.

>     according to the RFC3986, the default URL encoding is UTF-8. So I think URLs don't have to be escaped.
> 
> See [0] on whether this can solve your issue on the UTF-8 aspect or not. (refs #2188, #2207)
> 
> [0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1210-L1224

Thanks a lot for the pointers. Setting `$smwgExportResourcesAsIri` worked as what I expected! Except `:` and `-` in URLs are escaped in `-XX` form.
