### ISSUE TITLE
Special properties documentation for _LCODE, _ASK, _INST, _SKEY and others

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2793]
Using the SMW api there were some Special properties with the labels:

- _LCODE
- _ASK
- _INST
- _SKEY

for which I tried to find  the documentation
most property labels like _CDAT, _MDAT and  so on can be found in:
- https://www.semantic-mediawiki.org/wiki/Help:Special_properties

the four above are hard to find e.g. in:
- https://www.semantic-mediawiki.org/wiki/Help:$smwgFulltextSearchPropertyExemptionList
they are mentioned and for _LCODE it's unclear what the "correct" label is. According to

- https://www.semantic-mediawiki.org/wiki/Help:Special_property_Language_code
it would be SMW_DV_MLTV_LCODE  but in the query json format result it's returned as _LCODE.

If you take an api example like:

https://www.semantic-mediawiki.org/w/api.php?action=browsebysubject&subject=Help:Debug_format

and get the special properties starting with an underscore with
grep property ask.txt | cut -f2 -d":" | cut -f2 -d'"' | sort -u | grep "^_"

you end up  with the following list:

- _ASK
- _ASKDE
- _ASKDU
- _ASKFO
- _ASKPA
- _ASKSI
- _ASKST
- _CDAT
- _INST
- _LEDT
- _MDAT
- _NEWP
- _SKEY
- ___CUSER
- ___NREV
- ___PAGEID
- ___PAGELGTH
- ___REVID

It would be great if all of the above would be documented consistently. I am willing to help in this but need some hint on what the systematic approach would be to do so.

**Comment by mwjames** [comment]
> Using the SMW api there were some Special properties with the labels:

Meaning exactly what? Using the the #ask API creates [0] something like:

```
    "query": {
        "printrequests": [
            {
                "label": "",
                "key": "",
                "redi": "",
                "typeid": "_wpg",
                "mode": 2
            },
            {
                "label": "Modification date",
                "key": "_MDAT",
                "redi": "",
                "typeid": "_dat",
                "mode": 1,
                "format": ""
            }
        ],
```
Here you get the key and the label of a property.

> it would be SMW_DV_MLTV_LCODE but in the query json format result it's returned as _LCODE.

`SMW_DV_MLTV_LCODE` [1] is a setting and not comparable to `_LCODE` which a property key [2].

> If you take an api example like:
> https://www.semantic-mediawiki.org/w/api.php?action=browsebysubject&subject=Help:Debug_format

What is the use case here? `browsebysubject` produces a serialization of the `SemanticData` object for external use but of course it would require additional processing and depends solely on the objective [3] of the consumer of what happens to or with the data.

The difference between `_...` (`___...` defined by extensions) and _non_ `_...` properties is established a convention that dictates that the latter is a user-defined property while the former is identified as predefined property.

> It would be great if all of the above would be documented consistently. I am willing to help in this but need some hint on what the systematic approach would be to do so.

[4] should contain a complete list. Normally we don't promote those directly since only a developer may require a matching matrix but then again, s(he) will find those in [4].

As for the documentation part, [5] shows an incorrect information on `Label: | SMW_DV_MLTV_LCODE`
, first it should be called key since it is a `key` not a `label` with the label being "Language code", and secondly `_LCODE` would be the correct assignment here.

[0] https://www.semantic-mediawiki.org/w/api.php?action=ask&query=%5B%5BModification%20date::%2B%5D%5D%7C%3FModification%20date%7Csort%3DModification%20date%7Corder%3Ddesc
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1269
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/PropertyRegistry.php#L484
[3] https://github.com/spellcheck-ko/galkwiki-bots/blob/4c334a132827b6c12efcfd3caae74562aa501e70/bot.py#L169-L203
[4] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/i18n/extra/en.json
[5] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Language_code

**Comment by kghbln** [comment]
Thanks for reporting. I will try to work on this today.

**Comment by kghbln** [comment]
So the labels are in there now. @mwjames About the keys. Is there a spot where I can find them centrally?

**Comment by mwjames** [comment]
> @mwjames About the keys. Is there a spot where I can find them centrally?

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/i18n/extra/en.json

**Comment by kghbln** [comment]
These are the labels. I was thinking about `SMW_DV_MLTV_LCODE`, etc.

**Comment by mwjames** [comment]
> These are the labels. I was thinking about SMW_DV_MLTV_LCODE, etc.

This is a setting! [0] Keys are identified as `_...` with labels representing a human readable component.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1269

**Comment by kghbln** [comment]
> This is a setting! [0] Keys are identified as _... with labels representing a human readable component.

A thanks. I the heat of the action I mixed this up. That's fixed now in the documenation.

> These are the labels. I was thinking about SMW_DV_MLTV_LCODE, etc.

I am not sure if this should be documented on the special property level at all. That's specific to a configuration setting and documented on the respective page.

**Comment by kghbln** [comment]
> https://www.semantic-mediawiki.org/wiki/Help:$smwgFulltextSearchPropertyExemptionList
they are mentioned and for _LCODE it's unclear what the "correct" label is

@WolfgangFahl  Just in the line explaining the default setting of this configuration parameter there was a reference to the respective label-key pairs. So even without adding the keys to the special property pages it should have been quite easy to get the information required. ;)

Still the keys are now prominently documented for the special properties provided by SMW core. The keys were generally not documented since in earlier versions they there only important for page related special properties. Only more recent versions of SMW made all of these keys increasingly important. I just did not think about adding them in before.

The special properties provided by SESP are not documented on the wiki so the keys are not documented on the wiki either. We could add all special properties provided by SESP but I will not have the time to do this though everything is set up to do so. Thus `___CUSER` etc. are not documented. If you like you could give this a shot.

I believe that this issue is resolved now.

**Comment by kghbln** [comment]
I also created a page on [property keys](https://www.semantic-mediawiki.org/wiki/Help:Property_keys) which is linked from the respective configuration settings and vice versa.

**Comment by kghbln** [comment]
Also added the "hidden special properties" with [subobjects](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ASpecial_properties&type=revision&diff=56863&oldid=56802). @mwjames Do you think is is worth creating regular pages for them?

**Comment by WolfgangFahl** [comment]
How about _SKEY and _INST - what are these and where are they documented?

**Comment by kghbln** [comment]
Please use the search feature on the [property keys](https://www.semantic-mediawiki.org/wiki/Help:Property_keys) page.

**Comment by mwjames** [comment]
>How about _SKEY and _INST - what are these and where are they documented?

- `_SKEY` is an internal property that can not be used by a user [0]
- `_INST` represents a category instance (which is different from a `rdf:Class` representation [1])

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/PropertyTableDefinitionBuilder.php#L241-L244
[1] https://www.w3.org/TR/1999/PR-rdf-schema-19990303/#core

**Comment by WolfgangFahl** [comment]
https://www.semantic-mediawiki.org/wiki/Template:SpecialPropertyRow
shows two  more inconsistencies and it would be great if the tables e.g. in 
https://www.semantic-mediawiki.org/wiki/Help:Property_keys
would each have a link to the given property. I am still looking for a short ask / show query that takes a property key and points to the given property page. The template approach above is a bit complicated I think.

**Comment by kghbln** [comment]
>  shows two red links at this time - so there are 3.0.0 properties that do not show yet in the wiki.

Correct since the wiki is indeed still running 2.5.5

> It would be great if the tables e.g. in https://www.semantic-mediawiki.org/wiki/Help:Property_keys would each have a link to the given property.

This page was meant to allow searching for the keys more easily. Otherwise it would basically just be a duplicate page to [special properties](https://www.semantic-mediawiki.org/wiki/Help:Special_properties). Another option will be to replace the table with a query form.

**Comment by kghbln** [comment]
> Another option will be to replace the table with a query form.

I just created the search form and added it to the necessary spots so we got rid of the datatable with was somehow irritating you. As a positive side effect the page looks much leaner now.
