### ISSUE TITLE
Help List of datatypes documentation inconsistencies

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#2795]
In
https://www.semantic-mediawiki.org/wiki/Help:List_of_datatypes

1. the datatype telephone number doesn't show any more in the list of types.
2. The list of examples seems to be incomplete. e.g. I just added an example for external identifier

The behavior of external identifier seems strange to me it does not show an ask result is that an issue with the example or intended behavior.

Again I'm willing to help if I'd understand the  structure of things. 

So https://www.semantic-mediawiki.org/wiki/Template:Docinfo
seems to be the culprit because the query asks for 
lang=en
and status=effective

In the https://www.semantic-mediawiki.org/wiki/Help:Type_Telephone_number there is 
Template:Doc.info used which seems to set the properties.

Trying this out is tedious due to the query results not being updated immediately.

**Comment by mwjames** [comment]
>The behavior of external identifier seems strange to me it does not show an ask result is that an issue with the example or intended behavior.

Behaviour and intend are outlined in #1708. Do you have a specific question since I cannot comment on "seems strange".

>  does not show an ask result is that an issue with the example or intended behavior.

- https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5BEC+number%3A%3A%2B%5D%5D&po=EC+number&eq=yes&p%5Bformat%5D=broadtable&p%5Bsource%5D=&p%5Blimit%5D=200&p%5Boffset%5D=0&p%5Blink%5D=all&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&sort_num%5B%5D=&order_num%5B%5D=asc&sort_num%5B%5D=&order_num%5B%5D=asc&eq=yes

- https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5BEC+number%3A%3A3.1.1.3%5D%5D&po=%3FEC+number%0D%0A&eq=yes&p%5Bformat%5D=broadtable&p%5Bsource%5D=&p%5Blimit%5D=200&p%5Boffset%5D=0&p%5Blink%5D=all&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&sort_num%5B%5D=&order_num%5B%5D=asc&sort_num%5B%5D=&order_num%5B%5D=asc&eq=yes

**Comment by WolfgangFahl** [comment]
@mwjames thank you for looking into this so quickly.
The "strange behavior" was that there was initially no result shown. So this is then about the delay it takes until the query results show. Initially on first edit the result was empty. If i remember right  there is already an issue discussing this delaying which happens more often than not with the latest SMW versions e.g. the 2.5.6-alpha (22aaa78) 15:34, 25 October 2017 currently installed on www.semantic-mediawiki.org. A save of a page alone will not always update the query results.

**Comment by mwjames** [comment]
> 2.5.6-alpha (22aaa78) 15:34, 25 October 2017 currently installed on www.semantic-mediawiki.org. A save of a page alone will not always update the query results.

As for the in-page or self-reference discussion, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2549#issuecomment-315545252.

> not always update the query results.

Updates are done once the system has processed the deferred update queue, see also above linked thread.

**Comment by mwjames** [comment]
> The "strange behavior" was that there was initially no result shown. So this is then about the delay it takes until the query results show. 

Also, if you change the type of a property, change propagation has to take place. 2495 and 2494 outlines the issues related to it and possible ways to improve the update process (not update speed!).

**Comment by WolfgangFahl** [comment]
https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl/Workdocumentation_2017-11-04_WF shows the analysis

**Comment by kghbln** [comment]
Thanks for reporting.

**Comment by WolfgangFahl** [comment]
@kghbln  - you are welcome.
Please note that I'd like to change https://www.semantic-mediawiki.org/wiki/Template:Datatype but I do not have the rights to do so.

**Comment by kghbln** [comment]
So I switched from the "docinfo" to the "doc.info" template. Now the info provided is consistent.

> Please note that I'd like to change...

What is missing?

**Comment by WolfgangFahl** [comment]
I think #2808 is not quite finished yet. An example for reference is missing and I think it would be good to have a "in this wiki" example link in the german and english template.

**Comment by kghbln** [comment]
Done with this [edit](https://www.semantic-mediawiki.org/w/index.php?title=Template%3ADatatype&action=historysubmit&type=revision&diff=57069&oldid=50906) I dunno though how #2808 comes into play here.

**Comment by WolfgangFahl** [comment]
I am sorry - that 2808 was just a typo.
In https://www.semantic-mediawiki.org/wiki/Category:Datatypes#tab=Datatypes the query does not show anything right now - is that the delay problem again?

**Comment by kghbln** [comment]
> I am sorry - that 2808 was just a typo.

Ah, ok, no worries.

>  query does not show anything right now - is that the delay problem again?

No, I just did not [adapt the query](https://www.semantic-mediawiki.org/w/index.php?title=Category%3ADatatypes&type=revision&diff=57074&oldid=56866)
