### ISSUE TITLE
Use tags for CI testing against EOL MediaWiki branches

### ISSUE THREAD

**Issue by legoktm** [SemanticMediaWiki/SemanticMediaWiki#2809]
Prior discussion:
* https://phabricator.wikimedia.org/T179754
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2794

The SMW CI tests should use git tags for testing against EOL MediaWiki branches, as those are permanent and will never go away. Branches on the other hand will be dropped sometime after the support cycle ends (specifics TBD). These branches will receive no more backports and the last git tag should be equivalent to the branch.

**Comment by kghbln** [comment]
I believe the arguments for using branches instead of tags were already stated along #2794. It is just an extra effort to change all the numerous testing setups every time an EOL is reached just to get the very same code in.

However I would be willing to take on this extra task for all these extensions in the SMW repository group as a sign of good will.

I still think that retaining the branches a bit longer for volunteer projects is not too much of a burden.

**Comment by legoktm** [comment]
> However I would be willing to take on this extra task for all these extensions in the SMW repository group as a sign of good will.

That would be appreciated, however maybe I've underestimated the scope of this work. How many repositories would this affect? I was just thinking of the main SMW repo, but you alluded to other extensions.

> I still think that retaining the branches a bit longer for volunteer projects is not too much of a burden.

Agreed. Do you want to make a comment at https://phabricator.wikimedia.org/T179754#3742523 ?

**Comment by kghbln** [comment]
> How many repositories would this affect?

15+ here at SemanticMediaWiki and still counting

> Agreed. Do you want to make a comment at https://phabricator.wikimedia.org/T179754#3742523 ?

Ok, will do.

**Comment by kghbln** [comment]
In case we need environments which are unsupported I will switch from REL1_x to a tag of that REL. However this should not be necessary often. I will close this for now however move this to the release management project to still keep this as an action item.
