### ISSUE TITLE
Consider re-aligning MediaWiki versions supported w/ MediaWiki support cycle

### ISSUE THREAD

**Issue by legoktm** [SemanticMediaWiki/SemanticMediaWiki#2810]
In the [compatibility matrix](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md#platform-compatibility), it lists support as version ranges, e.g. 2.5.x supports MW 1.23-1.29. 1.23 is the floor because its LTS, but it was supported much longer than 1.24 and 1.25. In fact, 1.23 has bug fixes that those two later releases never saw.

In addition, just like we strongly encourage people to upgrade their PHP version for security reasons, we should also be doing the same for MediaWiki - and continuing to provide support for EOL versions of MediaWiki works against that goal.

My naive proposal is to take the current compatibility table and just drop support for MW versions as upstream drops support for them. But I am not familiar with the needs/requirements of SMW users or really how the SMW development cycle looks like, so I'm sure that others have much better ideas than me. But my main point is that I don't think it's a good idea to support such old versions that no longer receive security fixes.

**Comment by kghbln** [comment]
SMW 2.5 was released in March and at that time MW 1.23 was still with us. Breaking compatibility within a release series does not appeal to me personally and probably to others too. MW is not doing that either for a reason.

SMW is indeed aiming to follow the release circle MW is doing and as a matter of fact the SMW 2.5 series is approaching EOL too. The release cycle is somewhere between six and nine months.

However this project is solely supported by volunteers, so it may take more time to create a new release than anticipated. We all know already from e.g. MW 1.28 that it is complex and requires effort to do a cool release even for much stronger organizations than the SMW project. SMW 3.0 was originally scheduled for the for the third quarter of 2017 but along the way unanticipated issues have to be overcome etc, which have to be dealt with. Most recently PostgresQL is bellies up all of a sudden. Moreover this will be a big release requiring even more attention. As a result more time is needed.

Deliberately breaking compatibility with MW 1.24 to 1.26 while still supporting MW 1.23 does not appeal to me either. However, I understand that in an ideal world users of these unsupported versions should migrate to supported branches. What I will do is add in more encouragement to do so in our documentation.

REL1_27 was inherently broken (job queue) until the 1.27.3 release at the very end of April so users of SMW which probably tend to have more complex setups than regular users could only safely start migrating after this point. Sadly this time the intended migration period to the new LTS branch was down from 12 to 2 months. That's not ideal but may happen. Thus people are working longer with older versions than envisioned. We should probably not make it harder for them.

Last but least, I have the impression that the SMW clientele is a bit more conservative since it appears that RHEL and CENTOS is not uncommon in environments. I got this impression from the past discussion about dropping PHP 5.3 support which was painful.

To cut it short: Sometimes more time is needed for a melange of various reasons and not deleting a branch does not appear to be too much of a burden to provide a bit more extra time. In the end I do not really see much of a dissent on this subject if at all.

**Comment by legoktm** [comment]
Thanks, that was really insightful. I should have mentioned that I was proposing this independently of the "old branches were deleted" issue, I just happened to notice this at the same time.

The main point I seem to be getting is that the intention is to be aligned with MW cycles but reality often gets in the way. If that's the case, I think we can close this task.

Some inline comments:
> Deliberately breaking compatibility with MW 1.24 to 1.26 while still supporting MW 1.23 does not appeal to me either. However, I understand that in an ideal world users of these unsupported versions should migrate to supported branches. What I will do is add in more encouragement to do so in our documentation.

Thanks, I think that would be helpful. My worry is that some theoretical bug fix will get backported to 1.23 but not 1.24 because of EOL, and then SMW can't really be compatible with the EOL version.

> REL1_27 was inherently broken (job queue) until the 1.27.3 release at the very end of April so users of SMW which probably tend to have more complex setups than regular users could only safely start migrating after this point. Sadly this time the intended migration period to the new LTS branch was down from 12 to 2 months. That's not ideal but may happen. Thus people are working longer with older versions than envisioned. We should probably not make it harder for them.

I assume you're referring to https://phabricator.wikimedia.org/T142751. I don't see any comments from SMW developers, which I think would be useful for prioritizing and understanding the impact of the issue in the future. I know that mwjames lately cc's me on tasks that are affecting SMW so I can help prioritize/triage them, and alert the relevant people - something that I think has been pretty productive for most cases recently.

> Last but least, I have the impression that the SMW clientele is a bit more conservative since it appears that RHEL and CENTOS is not uncommon in environments. I got this impression from the past discussion about dropping PHP 5.3 support which was painful.

Hm, that's interesting. I think comments like that would be useful on tasks like <https://phabricator.wikimedia.org/T178538>.

**Comment by kghbln** [comment]
> The main point I seem to be getting is that the intention is to be aligned with MW cycles but reality often gets in the way

Affirmative. SMW used to support a much wider spectrum of MediaWiki until the 2.4 branch but this is a story of history past.

> Thanks, I think that would be helpful.

Done with #2818 

> My worry is that some theoretical bug fix will get backported to 1.23 but not 1.24 because of EOL, and then SMW can't really be compatible with the EOL version.

If this backport requires changes on the SMW side when tests for the EOL version should ideally break and be kicked.

> I assume you're referring 

There were some more if I recall correctly and they they that bad that MediaWiki rendered being unusable with or without SMW being installed. I think in the end it was Tim who got these issues moving on since it also affected one of his external projects.

Anyways it appears to me that there is now a mode in place that allows to tackle issues better in the future or at least make people aware of them. I believe this is the main point.

> Hm, that's interesting. I think comments like that would be useful on tasks like https://phabricator.wikimedia.org/T178538.

Though they will always lag and unsupported versions of MW or SMW which we cannot do much about. That's basically why SMW moved on to PHP 5.5

I added this thread to the project documentation for future reference.
