### ISSUE TITLE
ask query, 'limit' number seems applied prior reaching 'root' page

### ISSUE THREAD

**Issue by pitchke** [SemanticMediaWiki/SemanticMediaWiki#2834]
(I wanted to post this at https://www.semantic-mediawiki.org/wiki/Help_talk:Inline_queries,
but don't have permissions to)

===== Context: =====
* I just upgraded from MW 1.27 to 1.29.1 with all software/SMW/extensions/Composer updated - but this is probably not relevant here.
* I do use SMW with ''parent'' relathionship, hence defining a tree between pages.
* There's about +300 pages in the structure, and the example below uses ''root=Apple'' to define the i.e. ''Apple'' page as the considered root page.

===== Findings: =====
The following query (limit=10):

<pre><nowiki>
{{#ask: [[Category:Thèmes évènements]]
 |format=tree
 |limit=10
 |parent=Thème Parent
 |root=Apple
}}
</nowiki></pre>

does not report any content,
while the next query (limit=500):

<pre><nowiki>
{{#ask: [[Category:Thèmes évènements]]
 |format=tree
 |limit=500
 |parent=Thème Parent
 |root=Apple
}}
</nowiki></pre>

does report the "Apple" page and its two child pages.

===== Outcome: =====
A priori, I was expecting the 1st query to show the total 3 pages (below the limit=10).

While this can be by design (to limit server-side processing), it is not just limiting the "maximal number of pages selected" as reported in the #Ask documentation.

Am I doing something wrong, is this a bug or designed-as-is feature ?

In the later case, maybe the documentation could be updated to warn about this a-priori limitation on ''processed'' pages, and not related to final ''selected'' pages results.
Also, in future SMW may consider two different parameters for (1) Server-side pages ''à-priori'' limitations, and (2) effective results selected pages limitation.

Thanks for any feedback.
Regards,
Pierre

**Comment by kghbln** [comment]
First of all thanks for taking the time to report something what may be an issue.

> (I wanted to post this at https://www.semantic-mediawiki.org/wiki/Help_talk:Inline_queries,
but don't have permissions to)

You ran into one of our counter spam machanisms since I forgot to grant the contributor privilege right away. :|

> I just upgraded from MW 1.27 to 1.29.1 with all software/SMW/extensions/Composer updated - but this is probably not relevant here.

Does this meant that you also upgraded SMW from version x to y? Moreover does this meant that what you are reporting was working earlier on? If you answer the latter question with yes that I would indeed be puzzled.

> The following query (limit=10):

I believe that this is just a matter of page selection meaning that you want to consider all pages that were added to `[[Category:Thèmes évènements]]` which contains 300+ pages without narrowing down the number of possible results any further. If you however add a limit of 10 to you query yoiu are basically telling the query to select the first 10 pages located in the `[[Category:Thèmes évènements]]` category. I the Apple page is not among these first 10 pages selected you are getting no result as expected. If you set a wider limit like 500 you will be getting results because the Apple page will definitively be among the pages selected.

So you indeed either have to set wider limits to your queries or narrow down the set of selected pages by adding some more selection criteria to your query.

**Comment by mwjames** [comment]
As outlined above, the condition does exactly what is supposed to do with the limit as condition restriction namely to return the first 10, 100, or 500 matches that meets the requirements of the `#ask` (you can verify this by using the `format=table` format).

Now, if you use `format=tree` then a result set post-processing is applied to make format specific adjustments as for the `root` and `parent` requirements. You can choose a wider range or a narrower condition and allow the original `#ask` condition to return a better result scope which then the `tree` post-processing can work more effectively (means to filter less from the original result set).

![image](https://user-images.githubusercontent.com/1245473/32979450-c610139a-cc98-11e7-9107-c29e11de0291.png)

**Comment by kghbln** [comment]
I assume that the question has been answered. Thus closing which does not mean that feedback can no longer be posted.

**Comment by pitchke** [comment]
Yes, thanks to both of you for your feedback.
