### ISSUE TITLE
QUnit tests need update for QUnit 2.4 in MW 1.31+

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#2849]
### Setup and configuration

- SMW version: 3.0@dev
- MW version: 1.31+
- PHP version: any
- DB system (MySQL, Blazegraph, etc.) and version: any

### Issue
The QUnit library was updated from 1.3 top 2.4 in MW 1.31. `QUnit.asyncTest()` used by SMW is not supported anymore. See below.

### Steps to reproduce
1. Enable JavaSvript testing in LocalSettings.php: `$wgEnableJavaScriptTest = true;`
2. Run JS tests: http://127.0.0.1/wiki/Special:JavaScriptTest/qunit/plain?debug=true&module=ext.smw

![screenshot-2017-12-1 qunit](https://user-images.githubusercontent.com/2829850/33461926-f3c6281a-d634-11e7-9668-cbbddce7e0e2.png)

Edit:
See https://phabricator.wikimedia.org/T170515

**Comment by mwjames** [comment]
> The QUnit library was updated from 1.3 top 2.4 in MW 1.31. QUnit.asyncTest() used by SMW is not supported anymore.

That's very unfortunate, and as you can imagine it is very unlikely that I will find the time within the next quarter to look at it since it is caused by a change that did not originate in SMW itself.

I do hope that somehow can pick up the tab given that those tests worked before and should work hereafter on the assumption that a simple replacement is available and can be done independent of any SMW specific knowledge.
