### ISSUE TITLE
setupStore.php: Use wgDBadminuser instead wgDBuser

### ISSUE THREAD

**Issue by saerdnaer** [SemanticMediaWiki/SemanticMediaWiki#2963]
When setting $wgDBadminuser and -password in LocalSetttings.php the setupStore.php maintenance script, should use these instead of $wgDBuser and -password, as its done by native MediaWiki maintenance scripts, c.f. https://www.mediawiki.org/wiki/Manual:$wgDBadminuser .

### Steps to reproduce
configure remove CREATE TABLE, etc. rights from the mysql user your semantic mediawiki is using, and try to install/upgrade semantic mediawiki -> Tables does not get created.

**Comment by mwjames** [comment]
> When setting $wgDBadminuser and -password in LocalSetttings.php the
> setupStore.php maintenance script, should use these instead of $wgDBuser and

We never access `wgDBadminuser` or for that matter `wgDBuser` and rely
on the `wfGetLB` method (provided by MediaWiki) to give us a handle to
a DB connection.

**Comment by kghbln** [comment]
This means that `wfGetLB` does not properly handle the credentials? I guess at some point MediaWiki has to be fed with the user and credentials for the database, either via `$wgDBadminuser` or `$wgDBuser`.

**Comment by mwjames** [comment]
> I guess at some point MediaWiki has to be fed with the user and credentials for the
> database, either via `$wgDBadminuser` or `$wgDBuser`.

Yes, and since we don't want to manage credentials (with all the
security implications) we rely on `wfGetLB` to give us an appropriate
handle.

I cannot really evaluate how this becomes an issue for SMW now or for
running a maintenance script but if someone wants to work on this fine
be me but it would require careful verification on all related
settings.

The following code has __not__ been verified, so anyone interested in
a solution should test this carefully as I won't have time beyond
providing the following suggestions.

This is written against the master (3.0+).


```
@@ -3,10 +3,12 @@
 namespace SMW\Maintenance;

 use SMW\Store;
 use SMW\StoreFactory;
 use Onoi\MessageReporter\MessageReporterFactory;
+use SMW\Connection\ConnectionManager;
+use SMW\Connection\CallbackConnectionProvider;
 use SMW\SQLStore\Installer;

 $basePath = getenv( 'MW_INSTALL_PATH' ) !== false ? getenv(
'MW_INSTALL_PATH' ) : __DIR__ . '/../../..';

 require_once $basePath . '/maintenance/Maintenance.php';
@@ -109,10 +111,28 @@ class SetupStore extends \Maintenance {
 		} else {
 			$messageReporter =
MessageReporterFactory::getInstance()->newObservableMessageReporter();
 			$messageReporter->registerReporterCallback( array( $this,
'reportMessage' ) );
 		}

+		// #2963 Use the DB handler from the Maintenance script which may access
+		// the `$wgDBadminuser` instead of the regular `$wgDBuser`
+		$callbackConnectionProvider = new CallbackConnectionProvider( function() {
+				return $this->getDB( DB_MASTER );
+			}
+		);
+
+		$connectionManager = new ConnectionManager();
+
+		$connectionManager->registerConnectionProvider(
+			DB_MASTER,
+			$callbackConnectionProvider
+		);
+
+		$store->setConnectionManager(
+			$connectionManager
+		);
+

```

Add a new `CallbackConnectionProvider` to encapsulate the DB instance.

```
<?php

namespace SMW\Connection;

use Closure;

/**
 * @license GNU GPL v2+
 * @since 3.0
 *
 * @author mwjames
 */
class CallbackConnectionProvider implements ConnectionProvider {

	/**
	 * @var Closure
	 */
	private $callback;

	/**
	 * @var mixed
	 */
	private $connection;

	/**
	 * @since 3.0
	 *
	 * @param Closure $callback
	 */
	public function __construct( Closure $callback ) {
		$this->callback = $callback;
	}

	/**
	 * @since 3.0
	 *
	 * @return mixed
	 */
	public function getConnection() {

		if ( $this->connection === null ) {
			$this->connection = call_user_func( $this->callback );
		}

		return $this->connection;
	}

	/**
	 * @since 3.0
	 */
	public function releaseConnection() {
		$this->connection = null;
	}

}
```

What's left?

- `CallbackConnectionProvider` needs a unit test
- CI is required to pass all tests
- Works with both `$wgDBuser` and  `$wgDBadminuser` side by side and
it has been verified that when `$wgDBadminuser` is maintained it uses
the script DB handle

[0] https://github.com/wikimedia/mediawiki/search?utf8=%E2%9C%93&q=wgDBadminuser&type=
