### ISSUE TITLE
Combining #ask query with #show statement (to create multiple values from single property) 

### ISSUE THREAD

**Issue by antohabio** [SemanticMediaWiki/SemanticMediaWiki#3387]
### Setup and configuration

- SMW version: last
Debian
MediaWiki | 1.28.0
PHP | 7.0.27-0+deb9u1 (apache2handler)
MariaDB | 10.1.26-MariaDB-0+deb9u1
ICU | 57.1

### Issue

This query its ok;
```
{{#ask: [[Category:Publications]] [[Publications authors::Author1||Author2]]
 |format=broadtable
}}
```

But, if I'm inserting "Author1||Author2" by "#show" (PropertyContain "Author1||Author2"):
```
{{#ask: [[Category:Publications]] [[Publications authors::{{#show: {{PAGENAME}}|?PropertyContain}}]]
 |format=broadtable
}}
```
, get error (show publications by all authors).

**Comment by mwjames** [comment]
> SMW version: last

That is unspecific because from where I standing that would be SMW 3.0 but I doubt that you're using this version, so precision is key.

> [[Publications authors::Author1||Author2]]

Is a disjunction (aka OR).

> [[Publications authors::{{#show: {{PAGENAME}}|?PropertyContain}}]]

This doesn't create a disjunction out of the box and more importantly `#show` without any parameters (that formats the output) will create a table/list by default (just use `{{#show: {{PAGENAME}}|?PropertyContain}}` and you'll see how the result will look like.

To avoid any ambiguity (on the matter of types used etc.) it is best to create a simple example at [0] so someone can help you with getting your `#show` to the right form (link=none,mainlabel=-, template=... etc.).

[0] https://sandbox.semantic-mediawiki.org

**Comment by kghbln** [comment]
[Here](https://sandbox.semantic-mediawiki.org/wiki/Issue/3387) you can see why it is not working. I recommend using `#ask` in this case instead of `#show` and use the list format or so to be able to specifiy `||` as a separator instead of `,`.

**Comment by antohabio** [comment]
Hello.
I try: 
`{{#ask: [[Category:Publications]] [[PAuthors::{{#ask: [[{{PAGENAME}}]] |?PropertyContain|format=list|limit=10000|headers=hide|link=none|mainlabel=-}}]]}}`
But get publications by all authors, again.

**Comment by mwjames** [comment]
> {{#ask: [[Category:Publications]] [[Publications authors::{{#ask: [[{{PAGENAME}}]] |?PropertyContain|format=list|limit=10000|headers=hide|link=none|mainlabel=-}}]]}}
But get publications by all authors, again.

Again, `{{#ask: [[{{PAGENAME}}]] |?PropertyContain|format=list|limit=10000|headers=hide|link=none|mainlabel=-}}` returns a list and unless `[[Publications authors:: ...]]` is stored with such a list the above query does not work. Please use the referenced sandbox link to clarify your use case.

`[[Publications authors::Author A, Author B]]` is something different than `[[Publications authors:: Author A||Author B]]`. `[[Publications authors::Author A, Author B]]` expects those values to appear as-is and are therefore matchable in exactly the order the are stored namely `Author A, Author B`. A completely different context is `[[Publications authors::Author A]]` `[[Publications authors::Author B]]`.

**Comment by kghbln** [comment]
Probably my advice to use `#ask` instead of `#show` was misleading in respect of what wanted to be done. It was distracting from what I wanted to convey with switching to a specified result format, i.e. "list" to be able to change the separator.

I personally prefer to use `#ask` for more complex stuff while I use `#show` for the page scope which we have here but only to return simple results without further voodoo.

@antohabio Indeed your try still returns values separated with a comma. So you have to specify a different separator.

```
{{#ask:
 [[Category:Song]]
 [[Is performer::{{#show: {{PAGENAME}} |?Is performer |valuesep={{!!}} }}]]
 |format=broadtable
}}
```
or
```
{{#ask:
 [[Category:Song]]
 [[Is performer::{{#ask: [[{{PAGENAME}}]] |?Is performer |headers=hide |link=none |mainlabel=- |valuesep={{!!}} }}]]
 |format=broadtable
}}
```
Note that the sandbox wiki is already on SMW 3.0.0, so using "sep" instead of "valuesep" should do the trick.

@mwjames What I found a bit suprising is that you get a different formatting when explicitly specifying "list" (values are wrapped into spans) as the format in contrast to do not doing so (values are not wrapped into spans). This is why one gets the whole lot as the first example shows.

**Comment by kghbln** [comment]
> Can I working with sandbox without registration?

No.

**Comment by antohabio** [comment]
I register early, but not approved.

**Comment by kghbln** [comment]
> I register early, but not approved.

This is a self-service wiki that requires no extra approval. You only have to get passed the Captcha.

So replacing "valuesep" by "sep" does not change a thing?

**Comment by antohabio** [comment]
No changes.
I get 500 error on https://sandbox.semantic-mediawiki.org

**Comment by kghbln** [comment]
> No changes.

Well, I cannot tell why it is not working for you. I propose to have a good nights sleep and have another look at it tomorrow.

> I get 500 error on https://sandbox.semantic-mediawiki.org

Not any longer. Just had an issue upgrading the software. :)

**Comment by kghbln** [comment]
I added a test to a wiki basically running your environment and it works as expected: [see here](https://smwtest.wikihoster.net/whn/Tracks). Thus I created an account for you on this wiki by sending a temporary password to your e-mail address. So please check you spam. As far as I am concerned the question was answered so I close this issue. This does not meant that we cannot use this for further conversation.
