### ISSUE TITLE
Allow to skip optimize step on update.php for MediaWiki 1.32+

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3507]
### Setup and configuration

- SMW version: 3.0.0-rc.1
- MW version: e53f26bde1d4a7763f243fa8a04f2a51131e995f (master)
- PHP version: 7.1.20-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.0.36-MariaDB-0ubuntu0.16.04.1

### Issue
On systems where running update.php is part of all code and configuration deployments, the mandatory optimization of tables slows down all deployments. In my wikis this is taking 5+ minutes (haven't yet tested on the largest ones). I have a farm with multiple wikis where update.php is run serially, so this will take quite a while.

### Steps to reproduce

I'm using https://github.com/CSCfi/Kielipankki-palvelut/blob/master/servers/sanat/roles/mediawiki/tasks/instance.yml

**Comment by Nikerabbit** [comment]
Actually, I cannot:

```
php maintenance/update.php --skip-optimize
Unexpected option skip-optimize!
```

**Comment by Nikerabbit** [comment]
Probably due to https://gerrit.wikimedia.org/r/c/mediawiki/core/+/450097

**Comment by kghbln** [comment]
I do not know why this is not working for you. I just tested this on sandbox which is running 1.31.1 (8641df9) 06:59, 26. Sep. 2018 prior to answering you.

**Comment by kghbln** [comment]
> I just successfully tested this on sandbox which is running 1.31.1 (8641df9) 06:59, 26. Sep. 2018 prior to answering you. 

Probably this is already MW 1.32

**Comment by kghbln** [comment]
This also applies to the `--skip-import` flag

**Comment by mwjames** [comment]
> configuration deployments, the mandatory optimization of tables slows down all deployments.

I understand the problem but as you might imagine most users will NOT run `optimize` or any other DB specific methods just because our documentation recommends it in order to improve the query planner statistics. Running `optimize` is to have those steps done automatically to ensure the DB backend is setup appropriately.

> You should use the --skip-optimize flag from the "setupStore.php" script which is also honored by the "update.php" script.

When I added the feature I also had users in mind that where more proficient in backend maintenance by allowing them to use the `--skip-optimize` flag.

> Unexpected option skip-optimize!
> Probably due to https://gerrit.wikimedia.org/r/c/mediawiki/core/+/450097

Well, that's unfortunate but what should I do now? Preventing us from designing an extension in the most suitable way is very unfortunate but I don't see any possibility the counter those changes introduced unless the responsible developer provides a hook so we can registered our flags and make it possible to interact more fluently with `update.php` and the user.

@hexmode @Nikerabbit maybe petition a new hook so we can go back to previous behaviour.

This is not a bug since mentioned flag does work for a range of MW releases, yet we are limited by mentioned PR and are unable to restore the intended behaviour by means of SMW functionality.

**Comment by Nikerabbit** [comment]
Filed https://phabricator.wikimedia.org/T213893

**Comment by mwjames** [comment]
> Filed https://phabricator.wikimedia.org/T213893

Thanks.

Two things to be considered:

- Allow to registered valid args before `update.php` reaches the `ExtensionSchemaUpdates` hook
- Ensure that `DatabaseUpdater` (in the `ExtensionSchemaUpdates` hook) has access to those args to avoid relying on `ReflectionProperty` as we did in [0] to direct the outcome of the hook

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ExtensionSchemaUpdates.php

**Comment by mwjames** [comment]
I think https://phabricator.wikimedia.org/T213893 contains the wrong link to this issue.

**Comment by kghbln** [comment]
> I think https://phabricator.wikimedia.org/T213893 contains the wrong link to this issue.

Updated.

**Comment by lisabufzinski1671** [comment]
So you have fixed my issue and I won't need to update my certificates

**Comment by bpirkle** [comment]
Sorry for the inconvenience.  I'm the developer who wrote the Gerrit change that caused the issue.  I'll prepare a fix per the Phabricator ticket.

**Comment by kghbln** [comment]
Cool, thanks a lot!

**Comment by kghbln** [comment]
@mwjames There were three questions I guess which are better answered before [changes are done](https://phabricator.wikimedia.org/T213893#4949760) and I do not feel like being the best to answer. In the end the minimum should be reinstating the MW 1.19+ behaviour we had before. I personally have the feeling the that answers are yes - no - no but I may be wrong.

**Comment by mwjames** [comment]
@bpirkle 

> Sorry for the inconvenience.

No problem and thanks for the swift response.

>  I'll prepare a fix per the Phabricator ticket.
> https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/490531/

As for the patch you prepared, I took a quick swing at it by pulling the PR against master and added some userland code for the introduced hook.

```
+	// Test
+	'MaintenanceBeforeExecute' => function( $maintenance ) {
+		$maintenance->addOption( 'skip-optimize', 'SMW, allow to skip the table optimization' );
+	}
```

The output of `update.php` is now working again with:

```
@taurus /d/xampp/htdocs/mw-master-phpunit (test-maintenance-hook)
$ php maintenance/update.php --skip-optimize
MediaWiki 1.33.0-alpha Updater

Your composer.lock file is up to date with current dependencies!
...

Selected storage engine: "SMWSQLStore3" (or an extension thereof)

Setting up standard database configuration for SMW ...

Checking table smw_object_ids ...
   Table already exists, checking structure ...

...

Database initialized completed.

Skipping the table optimization.

Adding property statistics rebuild job ...
   ... done.
```

This may not be part of the PR/hook you added but as I noted above, access to the maintenance options in the `DatabaseUpdater` class (via the `ExtensionSchemaUpdates` hook) is currently only possible using the `ReflectionProperty` [1] because the `maintenance` property is protected without a public accessor and if someone decides to meddle with that property in future we are in a similar position unable to determine what options the user has set.

[0] https://github.com/wikimedia/mediawiki/blob/0abb9338f870824e258a7a138ad07efbaa6b3894/includes/installer/DatabaseUpdater.php#L66-L69
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ExtensionSchemaUpdates.php#L82-L101

**Comment by bpirkle** [comment]
How much grief is the root issue causing?  

Per comments in the Gerrit change it might be prudent for me to refactor my first implementation.  I could also take a look at the Reflection concern at the same time (whether or not that spawns a separate task).  But all that would take longer, as I'll have to work it in amongst other things I'm doing.  It would still be on my short list of things to do, but it probably wouldn't get done this week.

**Comment by Nikerabbit** [comment]
I created a fork of SMW which doesn't run the optimization step. Obviously that is not good as it makes updating more difficult. If it takes a few weeks more to do the hook in a better way, I support that.

**Comment by kghbln** [comment]
If it takes more time to make it better when we should allow for it. MW 1.32 is already lacking the possibility but probably an aim could be to get it into MW 1.33 which will probably be branched between mid March and mid April (pretty unpredictable these days :| ).

**Comment by mwjames** [comment]
> I created a fork of SMW which doesn't run the optimization step.

Added a  note to [0].

[0] https://www.semantic-mediawiki.org/wiki/Database/Table_optimization
