### ISSUE TITLE
RFE: possible to customize the formatting of record & reference properties

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3538]
### Setup and configuration
- SMW version: 2.5.8 (and 3.0.0)

## Limitation
Currently the printout for record and reference properties is "fixed" (e.g. for records, that is in `SMWRecordValue.makeOutput->makeOutputText()`), and unfortunately CSS rules can only have a limited affect on them:
* record: val1 (val2, val3, ...)
* reference: val1<sup>Ξ</sup>

## Proposal
It would be nice to have some way to make the format configurable per record/reference propery.
For instance with a new _special property_ `[[displayed as::$1 ($2, $3)]]` or maybe `[[formatted by::<template name>]]`.  In the later case, to replicate the current format, a pre-determined template would be needed (e.g in the `MediaWiki:` NS?).  

Another alternative would be to apply different classes on the 1st, rest and last field-values, and replicate the current the formatting with CSS rules (and utilizing the `:after` and `:before` pseudo-rules).  But the capabilities might be limited.

**Comment by ankostis** [comment]
Another possibility for the formatting of the values would be to use [mustache templates](https://www.mediawiki.org/wiki/Manual:HTML_templates).

**Comment by kghbln** [comment]
Thank you for suggesting!

**Comment by ankostis** [comment]
I guess, another possibility would be to use #2273 rules.

**Comment by mwjames** [comment]
I understand the request but it is very unlikely for me to dedicated any time within the 3.x release cycle to look at it in depth therefore ...

This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
