### ISSUE TITLE
Asking for "Subcategory of" property requires explicit namespace

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3550]
### Setup and configuration

- SMW version: 3.0.0

Reproducible with https://www.semantic-mediawiki.org.

### Issue

`[[Subcategory of::Name]]` worked with 2.5.?, now it yields zero results, requiring you to use `[[Subcategory of::Category:Name]]`. The breaking change does not appear to be mentioned in the [change logs](https://www.semantic-mediawiki.org/wiki/Help:Semantic_MediaWiki_Version_History) and is not reflected in the [property documentation](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Subcategory_of). Confusingly Special:SearchByProperty still works without stating the namespace.

### Demo

* https://www.semantic-mediawiki.org/w/index.php?search=[[Subcategory+of::Document]]
* https://www.semantic-mediawiki.org/w/index.php?search=[[Subcategory+of::Category:Document]]
* https://www.semantic-mediawiki.org/wiki/Special:SearchByProperty/Subcategory%20of/Document

**Comment by kghbln** [comment]
Thanks a lot for reporting. This would be a breaking change. However since special property "Subcategory of" is supposed to hold only categories I see not reason for explicitly requiring to include the namespace prefix in the annotation. Thus I am leaning towards regarding this as a bug. The [example](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Subcategory_of#Queries_using_the_special_property) does no longer work either without the prefix.
