### ISSUE TITLE
Allow selection of inferenced subcategories

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3551]
### Setup and configuration

- SMW version: 3.0.0

There apparently is no way to select all categories under a category in the category tree (i.e. including subcategories of subcategories).

* `[[Category:Foo]]` does category inference but does not return category pages
* `[[Subcategory of::Foo]]` only returns immediate subcategories
* `[[Category:+]]` returns all categories

I think the most elegant way to solve this would be to make the following query work as one might expect instead of yielding nothing:

```
{{#ask: [[Category:+]][[Category:Foo]]}}
```

This would allow for the [tree format](https://www.semantic-mediawiki.org/wiki/Help:Tree_format) of the Semantic Result Formats extension to be used to display category trees, which currently isn't possible.

**Comment by kghbln** [comment]
Thank you for reporting. I am assuming that you are using SMW 3.0.0. Did you somehow change the setting of [`$smwgQSubcategoryDepth`](https://www.semantic-mediawiki.org/wiki/Help:$smwgQSubcategoryDepth)? I believe that the subcategories beyond the first hierarchy level should indeed be returned, too.

**Comment by Larivact** [comment]
The "Subcategory of" property does not return subcategories beyond the first hierarchy level. Demo: https://www.semantic-mediawiki.org/w/index.php?search=+[[Subcategory+of::Category:Index]]

**Comment by mwjames** [comment]
> [[Category:Foo]] does category inference but does not return category pages

Yes, it returns instances of `[[Category:Foo]]` that belong to the class (aka category) but not the instance representation of an individual class. To do that you would need a different syntax element.

> [[Subcategory of::Foo]] only returns immediate subcategories

This is how it has been implemented from the beginning, changing the behavior is unlikely to happen in the 3.x release.

> [[Category:+]] returns all categories

Is not implemented because `[[Category:...]]` requires a specific instance representation. Also, `[[Category:+]]` has the smell of creating a pathological query pattern because of the possible members it can contain especially given when resolving it as part of a hierarchy.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and in case the issue finds a sponsor or is actively worked on it can be reopened.

### Notes

I'm uncertain about the need or use cases (I understand the tree scenario) to support those patterns against the effort and complexity to implement one or or two of the requested features. Furthermore, `[[Category:+]]` is unlikely to happen for the stated reasons unless some restrictions are in place to avoid a pathological query pattern.

If someone wants to implement one of the above features, please contact us in beforehand to discuss possible limitations and restrictions.
