### ISSUE TITLE
Provide special property to identify changes in data

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#3553]
In addition to the already existing special properties "Last editor is" (`_LEDT`), "Modification date" (`_MDAT`) it would be helpful to have another special property to indicate if a property value was changed.

Botn `_LEDT` and `_MDAT` are updated on any change on  a page. But SMW knows whether the change was done in any text on the  page or was done in a value annotation. So it would probably  be easy to implement a special property storing information about the fact that this last edit did at least change one property value.

This way we could query for pages where data was modified, not any arbitrary text.

The question  is  how to implement this.
Version 1: boolean
"Modification of data"  (`_MODA`)
true, if in the last edit, a property value has been changed,  false if not

Version 2: pageid
 "Last data change version" (`_LDCV`).
this would store the page ID of the page if in this edit a data value was changed.

There are probably other possibilities as well, but in my use cases, simplest boolean value is sufficient.

The biggest challenge with this is to distinguish on what values changes are meant. Of course, it should only be changes of user-defined properties, not of special properties (because all edits everytime change property values at least in the above mentioned special  properties).

A nice side  effect is that  poperties set in  a template will not be affected,  because they don't change wikitext on  the  page. Therefore the special  property would only be set if a user changes wikitext either via source edit or even in form based edits which is the desired outcome.

**Comment by kghbln** [comment]
Thanks @krabina for submitting this feature request.

> This way we could query for pages where data was modified, not any arbitrary text.

If I understand correctly your aim is to allow for some data curation and gardening on changes of structured data only (except data stored by special properties) beyond the page level which should be queryable.

On big issue I see with your `_LDCV` proposal is that if you have frequent changes to a page since the last data curation activity you will miss all but the latest change.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.

### Note

I somewhat understand the request, the intention is still a bit unclear and boundaries of what depends on what aren't specified.
