### ISSUE TITLE
Add primary key indexes

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#3559]
While trying to import to a [Percona XtraDB Cluster](https://www.percona.com/software/mysql-database/percona-xtradb-cluster), I'm finding tables in various MW extensions that don't have primary key indexes  ([explanation](https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#tables-without-primary-keys)).

For SMW, I've made the following changes:
``` sql
ALTER TABLE smw_di_blob ADD PRIMARY KEY(p_id,s_id,o_hash);
ALTER TABLE smw_di_bool ADD PRIMARY KEY(p_id,s_id,o_value);
ALTER TABLE smw_di_uri ADD PRIMARY KEY(p_id,s_id,o_serialized);
ALTER TABLE smw_di_coords ADD PRIMARY KEY(p_id,s_id,o_serialized);
ALTER TABLE smw_di_wikipage ADD PRIMARY KEY(p_id,s_id,o_id);
ALTER TABLE smw_di_number ADD PRIMARY KEY(p_id,s_id,o_serialized);
ALTER TABLE smw_fpt_ask ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_askde ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_askfo ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_asksi ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_askst ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_cdat ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_conc ADD PRIMARY KEY(s_id);
ALTER TABLE smw_fpt_conv ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_dtitle ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_impo ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_inst ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_lcode ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_ledt ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_list ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_mdat ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_media ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_mime ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_newp ADD PRIMARY KEY(s_id,o_value);
ALTER TABLE smw_fpt_pplb ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_prec ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_pval ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_redi ADD PRIMARY KEY(s_title, s_namespace);
ALTER TABLE smw_fpt_serv ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_sobj ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_subc ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_subp ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_text ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_type ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_unit ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_uri ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_prop_stats ADD PRIMARY KEY(p_id);
ALTER TABLE smw_query_links ADD PRIMARY KEY(s_id,o_id);
```

Removing duplicates in the above is basically the following:
``` sql
mysql> show create table smw_fpt_inst;
+-------------------+----------------------------------------------------------------+
| Table             | Create Table                                                           |
+-------------------+----------------------------------------------------------------+
| smw_fpt_inst | CREATE TABLE `wiki1smw_fpt_inst` (
  `s_id` int(8) unsigned NOT NULL,
  `o_id` int(8) unsigned DEFAULT NULL,
  KEY `s_id` (`s_id`),
  KEY `o_id` (`o_id`)
) ENGINE=InnoDB DEFAULT CHARSET=binary |
+-------------------+----------------------------------------------------------------+
mysql> -- note that this table uses o_id, not o_hash or o_serialized
mysql> CREATE TEMPORARY TABLE tmp (SELECT s_id FROM smw_fpt_inst GROUP BY s_id, o_id HAVING COUNT(*) > 1);
mysql> ALTER TABLE smw_fpt_inst ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;
mysql> DELETE FROM smw_fpt_inst WHERE s_id IN (SELECT * FROM tmp) AND id MOD 2 = 0;
mysql> ALTER TABLE smw_fpt_inst DROP COLUMN id;
mysql> ALTER TABLE smw_fpt_inst ADD PRIMARY KEY(s_id, o_id);
```

**Note** that the smw_fpt_redi was more complex.  We had to make the following two changes:
``` sql
CREATE TEMPORARY TABLE tmp (SELECT s_title, s_namespace FROM smw_fpt_redi GROUP BY s_title, s_namespace, o_id HAVING COUNT(*) > 1);
DELETE FROM smw_fpt_redi WHERE (s_title, s_namespace) IN (SELECT * FROM tmp) AND id MOD 2 = 0;
```

Since it complains about MyISAM
``` sql
ALTER TABLE smw_ft_search ENGINE=InnoDB;
```

**Comment by hexmode** [comment]
``` sql
ALTER TABLE wiki1smw_fpt_ask ADD PRIMARY KEY(s_id,o_id);
```

**Comment by hexmode** [comment]
``` sql
ALTER TABLE smw_fpt_askde ADD PRIMARY KEY(s_id,o_serialized);
```

**Comment by hexmode** [comment]
``` sql
ALTER TABLE smw_fpt_askst ADD PRIMARY KEY(s_id,o_hash);
```

**Comment by hexmode** [comment]
``` sql
ALTER TABLE smw_fpt_cdat ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_conc ADD PRIMARY KEY(s_id);
ALTER TABLE smw_fpt_conv ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_dtitle ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_impo ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_inst ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_lcode ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_ledt ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_list ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_mdat ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_media ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_mime ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_newp ADD PRIMARY KEY(s_id,o_value);
ALTER TABLE smw_fpt_pplb ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_prec ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_pval ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_redi ADD PRIMARY KEY(s_title, s_namespace);
ALTER TABLE smw_fpt_serv ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_sobj ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_subc ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_subp ADD PRIMARY KEY(s_id,o_id);
ALTER TABLE smw_fpt_text ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_type ADD PRIMARY KEY(s_id,o_serialized);
ALTER TABLE smw_fpt_unit ADD PRIMARY KEY(s_id,o_hash);
ALTER TABLE smw_fpt_uri ADD PRIMARY KEY(s_id,o_serialized);
```

Removing duplicates in the above is basically the following:
``` sql
mysql> show create table smw_fpt_inst;
+-------------------+----------------------------------------------------------------+
| Table             | Create Table                                                           |
+-------------------+----------------------------------------------------------------+
| smw_fpt_inst | CREATE TABLE `wiki1smw_fpt_inst` (
  `s_id` int(8) unsigned NOT NULL,
  `o_id` int(8) unsigned DEFAULT NULL,
  KEY `s_id` (`s_id`),
  KEY `o_id` (`o_id`)
) ENGINE=InnoDB DEFAULT CHARSET=binary |
+-------------------+----------------------------------------------------------------+
mysql> -- note that this table uses o_id, not o_hash or o_serialized
mysql> CREATE TEMPORARY TABLE tmp (SELECT s_id FROM smw_fpt_inst GROUP BY s_id, o_id HAVING COUNT(*) > 1);
mysql> ALTER TABLE smw_fpt_inst ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;
mysql> DELETE FROM smw_fpt_inst WHERE s_id IN (SELECT * FROM tmp) AND id MOD 2 = 0;
mysql> ALTER TABLE smw_fpt_inst DROP COLUMN id;
mysql> ALTER TABLE smw_fpt_inst ADD PRIMARY KEY(s_id, o_id);
```

**Note** that the smw_fpt_redi was more complex.  We had to make the following two changes:
``` sql
CREATE TEMPORARY TABLE tmp (SELECT s_title, s_namespace FROM smw_fpt_redi GROUP BY s_title, s_namespace, o_id HAVING COUNT(*) > 1);
DELETE FROM smw_fpt_redi WHERE (s_title, s_namespace) IN (SELECT * FROM tmp) AND id MOD 2 = 0;

**Comment by hexmode** [comment]
Since it complains about MyISAM
``` sql
ALTER TABLE smw_ft_search ENGINE=InnoDB;
```

**Comment by kghbln** [comment]
Thanks a bunch for suggesting this enhancement and providing a solution!

**Comment by mwjames** [comment]
Some preliminary notes:

I understand the motivation but there is a fundamental issue, when you create a PRIMARY index such as `ALTER TABLE smw_di_blob ADD PRIMARY KEY(p_id,s_id,o_hash);` it requires you that no NULL exists [0, 1] (or is stored) for the values of the fields that are part of the primary key.

### NULL

Unless I misinterpret the changes, adding a PRIMARY could create issues where we don't enforce a `NOT NULL` policy for those fields. For example, let's take a look at the `smw_di_blob` table.

`DESCRIBE smw_di_blob` will tell you that:

Field | Type | Null | Key | Default | Extra |  
-- | -- | -- | -- | -- | -- | --
s_id | int(11) 				unsigned | NO | MUL | NULL |   |  
p_id | int(11) 				unsigned | NO | MUL | NULL |   |  
o_blob | mediumblob | YES |   | NULL |   |  
o_hash | varbinary(255) | YES | MUL | NULL |  

Currently both `o_blob` and `o_hash` allow NULL but with `ALTER TABLE smw_di_blob ADD PRIMARY KEY(p_id,s_id,o_hash);` you force `o_hash` to be `NOT NULL`

Maybe `o_hash`can be turned into a `NOT NULL` but that would require some effort to ensure we do not crash with existing users or where an update has a NULL suddenly fails because of the change in the field definition.

[0] “… MySQL allows you to use NULL values in unique indexes . ... a NULL value may appear only once as a primary key ...” [0]

[1] “ …  A PRIMARY index is intended as a primary means to uniquely identify any row in the table, so unlike UNIQUE it should not be used on any columns which allow NULL values.  ...”

### PRIMARY

Besides the NULL issue, all tables have individual indices that are created for a purpose (analyzing certain query patterns) while creating a PRIMARY for fields that may never use that index seems premature especially when one takes into account that a table like `smw_di_blob` can have millions of rows (i.e. it is the common `text` value table) so adding `p_id,s_id,o_hash` index just for the sake of the PRIMARY seems questionable unless of course there is evidence that the query planner would prefer the PRIMARY over any existing index.

### MyISAM 

See [2] about the background and guidance how to change it.

### What next?

As I said above, adding PRIMARY KEY to all tables arbitrarily is going to be difficult so I'm currently undecided on how to proceed. One possible solution could be for those users that require a more strict key validation to add an extra index definition via a hook (see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3675#issuecomment-459921640) and gets loaded as soon as SMW related  tables are altered (during setup or update).

[0] https://www.oreilly.com/library/view/high-performance-mysql/0596003064/ch04.html
[1] https://stackoverflow.com/questions/707874/differences-between-index-primary-unique-fulltext-in-mysql
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1576-L1601

**Comment by mwjames** [comment]
> add an extra index definition via a hook (see #3675 (comment)) and gets loaded as soon as SMW related 

As noted in #3683, we provide a hook to make those extra indices available during the setup/update run.
