### ISSUE TITLE
Property links should work also with plain Text descriptions (apart from Monolingual text)

### ISSUE THREAD

**Issue by ankostis** [SemanticMediaWiki/SemanticMediaWiki#3562]
### Setup and configuration

- SMW version: 2.5.8

### Issue
As discussed in [the SMW-site](https://www.semantic-mediawiki.org/wiki/Thread:Help_talk:$smwgDVFeatures/Tooltip_with_property_description_disabled_when_monolingual_(SMW_DV_MLTV_LCODE_)),  when the `SMW_DV_MLTV_LCODE` option is removed from the `$smwgDVFeatures` configuration variable, and after removing all @en from the property descriptions, then the tooltips generated by the [property links](https://www.semantic-mediawiki.org/wiki/Help:Property_links) stop working. In other words, the _property links_ should not just work for properties of datatype _Monolingual text_ but also for plain _Text_.

**Comment by mwjames** [comment]
Property links and possible related descriptions require a language context as noted in:

- "...of auto-property descriptions (displayed as tooltip etc.) or in future to change to a preferred label (based on the user language)." (#1855)
- " ... is a predefined property and can be used to describe a local property in context of a language." (#1381)

If you arbitrarily change the `Monolingual text` (by removing `SMW_DV_MLTV_LCODE`  and the language identifier) then you cannot expect the same functionality.

Someone may write a PR (and tests) to change the behaviour but as of now descriptions require a language context.

**Comment by mwjames** [comment]
I'm closing this as it is fairly unlikely that a core member will sponsor a PR to change the behaviour.

**Comment by ankostis** [comment]
> If you arbitrarily change the Monolingual text

But it is not arbitrarily - i did it according to the [docs](https://www.semantic-mediawiki.org/wiki/Help:$smwgDVFeatures). 
I mean, this is not an enhancement, but rather a bug: removing `SMW_DV_MLTV_LCODE` and the tooltips with property descriptions break.  Ok, user language detection logic should not kick of, but why not printing the whole tooltip?

Could it be @mwjames that you misunderstood this issue?

**Comment by mwjames** [comment]
> But it is not arbitrarily - i did it according to the docs.

Which is fine but this has nothing to do with the "Property links" which is orthogonal.

> but why not printing the whole tooltip, as is?

Because it is the codified behaviour and the way it is designed requires a language context, removing a language identifier from a text yields a context insensitive representation hence it cannot be used for a tooltip.

"A bug is the occurrence of an unintended or unanticipated behaviour that causes a vulnerability or fatal error." [0] and the behaviour is intended so its not a bug and as I said above, people can send a PR to change the behaviour as long as the primary functionality remains and the new behaviour is covered by tests.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/CONTRIBUTING.md#report-bugs

**Comment by ankostis** [comment]
But we won't be able to find pending issues like this in the future.
Could there be some "label", like `wont' fix`, to mark them?

**Comment by kghbln** [comment]
> But we won't be able to find pending issues like this in the future.

We use a project for this. I labelled it "enhancement" and "seeks developer" and added it to the [ [Enhancements and features](https://github.com/SemanticMediaWiki/SemanticMediaWiki/projects/4) to prevent it from getting lost.

**Comment by ankostis** [comment]
For the recorded, i added respective notes to the wiki about this behavior in 2 pages.
