### ISSUE TITLE
Select pages/values that start with a string

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#3624]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.0
- PHP version: 7.1.25
- MySQL version: 5.6.41-84.1

### Question
Is it possible to select pages that start with a string? For example, I want to select titles that starts with "O mundo", but I could not express it in ask query. I want to get 3 titles in the query below, but I get 6 titles. Am I doing something wrong?

Expected results:
* O mundo de Sofia: romance da história da filosofia
* O mundo do Senhor dos Anéis: vida e obra de J. R. R. Tolkien
* O mundo mágico do Senhor dos anéis: mitos, lendas e histórias fascinantes
 
Is there a difference among?

`[[Has full title::~O mundo]]`
`[[Has full title::~O mundo*]]`
`[[Has full title::~*O mundo*]]`

[See the query](http://wikincat.org/w/index.php?title=Especial:Ask&cl=Yzo1TkEKwkAQ-49QthR6KexFPXgR3zBtZ-3gdAd2pvQmvsaH-RJ3XYRAAglJgqQVzI9JYDYYGR3TSub7Nov48MDsFoQZk3pdZHeKkKaFYUT2n9e76doVSDMl1I0NZlE3MWiOS_o1Zm-nB_21rnsdKr53knK3B52chKBovnVNf8w4geFdEsFwhUgB1cBIYtOfC7q2pi5QtsPGnMnIGIfheSuvtjjLoaZdvhjr5S8)

**Comment by kghbln** [comment]
@mwjames Thanks a lot for your elaborate tip.

Another part of this issue is that I very much lag behind with documentation. Just a fortnight ago I fluffed [`$smwgFulltextSearchMinTokenSize`](https://www.semantic-mediawiki.org/wiki/Help:$smwgFulltextSearchMinTokenSize) but e.g. the [`phrase:` operator](https://www.semantic-mediawiki.org/wiki/Help:Ask_syntax/phrase:_operator) is still undocumented. Anyways we have a page on [how to search using the full-text search](https://www.semantic-mediawiki.org/wiki/Help:Full-text_search/Searching) feature which ultimately is not easy to find.

**Comment by jaideraf** [comment]
Wonderful. Thanks @mwjames. Yes, I am using `$smwgEnabledFulltextSearch = true;`.

For my use case, with your help, I got it to wortk with 
`[[Has full title::like:{{ucfirst:{{{searchString|}}}}}*]]` 
because "o mundo" (with lower "o") does not select those pages in the "normal" (not fulltext) search mode.
I need to use `{{ucfirst:}}` because I want to match the start of the title, and I think users are used to type everything in lowercase in search boxes.

@kghbln thanks to you, too. The SMW documentation is awesome. I completely understand your lag. If I had more time, I would help you, too (I do translate SMW to brazilian portuguese, it's almost 100% translated).
