### ISSUE TITLE
MW1.33+: `mediawiki.api.parse` is deprecated

### ISSUE THREAD

**Issue by Krinkle** [SemanticMediaWiki/SemanticMediaWiki#3626]
FYI:

The mw.Api parse method(s) are part of the `mediawiki.api` module bundle as of MW 1.31, leaving `mediawiki.api.parse` as deprecated alias, to be removed in MW 1.33.

(Found via [Codesearch](https://codesearch.wmflabs.org/).)

**Comment by kghbln** [comment]
Thanks for notifying!

**Comment by mwjames** [comment]
> The mw.Api parse method(s) are part of the mediawiki.api module bundle as of MW 1.31, leaving mediawiki.api.parse as deprecated alias, to be removed in MW 1.33.

Do I correctly interpret the message above that removing `mediawiki.api.parse` from the `wgResourceModules` definition is sufficient? No other actions are required, is that correct?

**Comment by Krinkle** [comment]
That's correct.

**Comment by mwjames** [comment]
Sandbox (1.33.0-rc.0) reports:

```
Error: Unknown module: mediawiki.api.parse
Stack trace:
sortDependencies@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:29:792
sortDependencies@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:30:306
resolveStubbornly@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:30:656
load@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:42:369
@https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Modifications_r%C3%A9centes:9:363
RLQ.push@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:96:199
@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:96:255
@https://sandbox.semantic-mediawiki.org/w/load.php?lang=fr&modules=startup&only=scripts&skin=vector:46:879
```

**Comment by kghbln** [comment]
The alias was only added in MW 1.32. See https://github.com/SemanticMediaWiki/SemanticCite/issues/70#issuecomment-524610193 Thank god we did not release SMW 3.1 yet. Our code change has to be reverted.

**Comment by kghbln** [comment]
When looking at [this](https://github.com/SemanticMediaWiki/Mermaid/pull/22) I conclude that we need a shim. I believe this has now officially tuned into an utter mess.

**Comment by mwjames** [comment]
> This means that we have to revert all respective changes. Is the same way of resolving this keeping the module until we no longer support MW 1.31 and later and drop it as soon as we switch to MW 1.35 as minimum support.

Seriously, I explicitly ask to ensure that volunteer developer time was minimized in regards to any change that this would require. Now, we have a bunch of repositories (extensions) that have been released and are broken [0] on MW 1.31, this is given me a headache and I don't know what to say. 

It is somewhat unacceptable given that we have users expecting LTS (which means 1.31 -> 1.35) and above comments suggests that it has been introduced in MW 1.32 and removed in MW 1.33 making it unfit for any LTS compatibility.

> When looking at this I conclude that we need a shim. 

@hexmode Someone needs to deal with this, I cannot get involved.

https://github.com/SemanticMediaWiki/SemanticCite/commit/e6a6bfd2f0f0dff53b217570c9e122e12e413946#commitcomment-34818716

**Comment by Krinkle** [comment]
>  above comments suggests that it has been introduced in MW 1.32 and removed in MW 1.33 making it unfit for any LTS compatibility.

The `mediawiki.api.parse` module has existed for much longer. It was deprecated in MW 1.32 (with automatic fallback), and removed in MW 1.33 - in line with MediaWiki's PHP deprecation policy. Nothing unusual here.

It is well-known that trying to support more than 2 stable versions of MediaWiki from a single code base is not something MW core endorses and may often require conditional checks to be inserted to differentiate behaviour as needed, similar to what [MLEB](https://www.mediawiki.org/wiki/MediaWiki_Language_Extension_Bundle) extensions tend to do.

The general recommendation is that you version the extension together with MW, and thus don't have to change code that was already working fine. E.g. the LTS-compatible branch would never have needed to have this migration patch applied (it would only apply to master and your REL1_32+) – backporting only the changes necessary for bugs or features within the extension. Anyway, unsubscribing for now. I hope the above helps to move forward.

**Comment by kghbln** [comment]
@JeroenDeDauw Will it be possible to give the shim a shot. This is really a painful matter in the end. Hopefully this can somehow be done.

**Comment by JeroenDeDauw** [comment]
I am not sure what shim you are referring to.

If in the Maps extension I run into some super painful thing I just drop support for the older version of MW. This is made possible by having frequent releases, which ends up somewhat equivalent to what Krinkle wrote.

What about making a release of the relevant extensions that does not support latest MW, and dropping the deprecated code and doing another release that adds support for latest MW and drops support for whatever old MW version no longer works?

**Comment by kghbln** [comment]
> I am not sure what shim you are referring to.

I probably should have posted [this](https://github.com/SemanticMediaWiki/SemanticCite/issues/70#issuecomment-524610193) here. Either MW 1.31 is broken or MW 1.33 is.

> This is made possible by having frequent releases, which ends up somewhat equivalent to what Krinkle wrote.

I believe not supporting LTS is utter and complete nonsense from a administrator point of view. I have so many issues with Translate because they follow this suggested path. For me this extension is broken because I cannot deploy the fixes.

This discussion now again turned into a meta discussion.

**Comment by mwjames** [comment]
> If in the Maps extension I run into some super painful thing I just drop
> support for the older version of MW. This is made possible by having
> frequent releases, which ends up somewhat equivalent to what Krinkle wrote.
>
> What about making a release of the relevant extensions that does not support
> latest MW, and dropping the deprecated code and doing another release that
> adds support for latest MW and drops support for whatever old MW version no
> longer works?

We have been releasing SMW to have at least support one LTS release,
above comments suggests we abandon this policy by only supporting MW
1.32+ and so either users have to abandon their LTS to get the newest
SMW or remain on MW LTS with no updates whatsoever. Also, citing MLEB
as example does absolutely makes not sense as argumentative line on
how to work with (and not against) users that rely on LTS support.

For institutional as well as enterprise users dropping LTS isn't an
option because of the cost and possible incompatibilities it is going
to introduce. So, just because MW (hereby WMF) is unable to provide an
alias for a period of one LTS release we are having this discussion,
which is neither productive not product oriented towards non-WMF
users.

**Comment by Nikerabbit** [comment]
> I have so many issues with Translate because they follow this suggested path.

@kghbln Could you reach out to me, in an appropriate venue, with more details?

**Comment by Nikerabbit** [comment]
> I have so many issues with Translate because they follow this suggested path.

@kghbln Could you reach out to me, in an appropriate venue, with more details?

**Comment by kghbln** [comment]
Since we will probably not getting a shim we are facing the decision to either support MW 1.31 LTS and MW 1.32 or MW 1.33 onwards for SMW 3.1. Since supporting LTS is always the better choice we have to change the supported versions overview and inform users that they will run out of luck if they want to run MW 1.33 and 1.34 with SMW. I do not like this situation but this appears to be the way it is. I will update this and do the RC soonish.

@Nikerabbit I always report the issues for Translate I encounter. From the past is was a matter of a spammed error log or a missing functionality or a an error that prevented saving on some occasions. Luckily no killer bugs yet. It just took a year or more until I was able to upgrade and resolve the issues since I follow LTS only.

**Comment by mwjames** [comment]
> Since we will probably not getting a shim we are facing the decision to either support MW 1.31 LTS and MW 1.32 or MW 1.33 onwards for SMW 3.1. Since supporting LTS is always the better choice we have to change the supported versions overview and inform users that they will run out of luck if they want to run MW 1.33 and 1.34 with SMW. 

I suspect this to be fixed this (maintaining an alias ourselves), please test and verify.
