### ISSUE TITLE
Question: Show available test cases on SMW.org?

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#3689]
I think it could be helpful to show available test cases directly on SMW.org, e.g. test cases for https://www.semantic-mediawiki.org/wiki/Help:List_format:
* [f-0104.json](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/JSONScript/TestCases/f-0104.json) Test `format=list, ul, ol, template` (#2022,`wgContLang=en`, `wgLang=en`)
* [f-0105.json](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/JSONScript/TestCases/f-0105.json) Test `format=list, ul, ol` on `_qty` property (`wgContLang=en`, `SMW_DV_NUMV_USPACE`)

Especially with the great JSONScript way of writing test cases!

Any ideas how a mechanism to automatically link test cases with SMW.org could be established?

**Comment by mwjames** [comment]
To clarify, the motivation for the `JSONScript` was to minimize the effort to write DB (incl. setup and tear down) related PHPUnit tests which would require a lot of manual (and repeated) effort to codify those test requirements into an executable form without loosing readability.

Nowadays, it is used to simply create tests that provide an interface to MW and at most require a 5 min. effort leaving the indulgences of copying bootstrap code behind and allow to focus on the task at hand.

The downside is that any new test case file requires additional DB interactions (create and delete objects in realtime) which is why running integration tests will take about 90% of the time to run the SMW test suite.

Then why not use an in-memory DB? because those are unsuitable in a live setting when you really want to make sure that your SQL instructions (insert, update, delete, and query) don't falter and mirror that of a production system (... I digress).

> I think it could be helpful to show available test cases directly on SMW.org, e.g. test cases for https://www.semantic-mediawiki.org/wiki/Help:List_format:

An uncontrolled import seems unreasonable (some cases are unfit for wiki inclusion such as special or API cases) and writing a parserfunction `{{#import_test: f-0104}}` appears to be questionable for this one use case where a simple manual process would suffice. Of course, the manual process comes with a caveat of that being "manual" and any change to a test case doesn't get transferred without user intervention.

As for the process and to separate it from any other content while making clear from where it was derived:

- Select a champion (a person, or group of persons who "champion" and curate the content as we certainly don't want to shift the work to Karsten!)
- Create a `Test` namespace
- Select test cases most suitable
- Create content in the Test NS (on occasion where property definitions diverge from existing on on-wiki, modify the test case first, have them pass, and create property definitions accordingly)
- Modify selected JSON and mark them as being used on-wiki

> Any ideas how a mechanism to automatically link test cases with SMW.org could be established?

It is not to say that if one is willing to write a parserfunction that this may any waste of resources but the use case is rather limited and if, should happen in a separate extension. Of course, it would be convenient to move some of the classes now part of SMW to that repo but this is a different discussion.

Some test cases cover different aspects because creating a test case comes at a cost of creating and tearing down a case once completed. It means is that each file causes the DB to create listed pages first, run the expected tests, and have them destroyed after and before continuing to the next case to minimize the interference with other tests. So, some tests would have to be split to appeal to an on-wiki audience.

**Comment by gesinn-it** [comment]
Hi @mwjames, I think I was unclear with my request: I was thinking of just listing the test cases to make navigation easier and making the available test's more visible (like a simple link to the JSONs on Github)

 I'm no sure if you understood my request as "putting test case code directly on SMW.org" which is not good idea, I'd say.

**Comment by mwjames** [comment]
> I was thinking of just listing the test cases to make navigation easier and making the available test's more visible (like a simple link to the JSONs on Github)

In this case, see [0].

[0] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests

**Comment by kghbln** [comment]
I actually understood the question as @mwjames did. Anyways thanks a lot for the detailed elaboration on the possibilities.

**Comment by gesinn-it** [comment]
... sorry folks for my unclear question

**Comment by kghbln** [comment]
I think we both did not understand correctly since we both knew that the overview of tests is shown on the wiki and moreover also in the readme provided with the code. No worries. :)
