### ISSUE TITLE
Special:Ask doesn't seem to support display format "#MEDIAWIKI"

### ISSUE THREAD

**Issue by nischayn22** [SemanticMediaWiki/SemanticMediaWiki#369]
http://semantic-mediawiki.org/wiki/Help:Type_Date#Display_format

When using csv format which uses Special:Ask to make the csv files #MEDIAWIKI isn't working.

**Comment by JeroenDeDauw** [comment]
Is this actually a bug? Or is it a missing feature? Thinking this maybe should be labeled as enhancement

**Comment by mwjames** [comment]
Most likely fixed by #1407.

and it works with:

http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AAsk&q=[[Modification+date%3A%3A%2B]]&po=%3FModification+date%23MEDIAWIKI%0D%0A%3FModification+date&eq=yes&p[format]=broadtable&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=%26hellip%3B+autres+r%C3%A9sultats&p[default]=&p[class]=sortable+wikitable+smwtable&p[sep]=&eq=yes
