### ISSUE TITLE
Blank page instead of upgrade error notice is shown

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#3690]
### Setup and configuration

- SMW version: 3.0.1
- MW version: 1762dcfd2f1bc8c33e059dba076c1af1503f9378
- PHP version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1 (cli)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB

### Issue
I updated my development install, including MediaWiki core and extensions to latest master branch, and SMW from 3.0.0 to 3.0.1. After that I only see white page when visiting the wiki. Command line access seems to work.

After some digging, I found out that in smwfAbort, no code is executed after doPostOutputShutdown. It is trying to show the upgrade error page.
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/a5a4a0d1b05eb622749fe59a1d2be4be699aaed4/src/GlobalFunctions.php#L106 

I assume this is again MediaWiki core doing some assumptions breaking change, but I didn't investigate core changes yet.

**Comment by mwjames** [comment]
> After some digging, I found out that in smwfAbort, no code is executed after doPostOutputShutdown. It is trying to show the upgrade error page.
>$mediaWiki->doPostOutputShutdown( 'fast' ); 

I'm starting to get annoyed on those changes, I've tested this with MW 1.32 and earlier MW to avoid "PHP Notice: Uncommitted DB writes (transaction from ..." messages in case we abort.

It was either to rely on the `LB::shutdown` or to have MW do to a simple `doPostOutputShutdown` [0, 1] as standard routine.

```
  $factory = wfGetLBFactory();
  $factory->commitMasterChanges();
  $factory->shutdown();
```

What happens if you remove the call to?

PS: I thought to be nice and let MW abort in a orderly fashion but if it causes more headaches as necessary, I'll remove it and no longer care.

[0] https://github.com/wikimedia/mediawiki/search?utf8=%E2%9C%93&q=doPostOutputShutdown&type=
[1] https://github.com/wikimedia/mediawiki/blob/50af36e359d170cc20eb30e97027e862c3d96c15/includes/MediaWiki.php#L697-L707

**Comment by Nikerabbit** [comment]
> What happens if you remove the call to?

Call to what exactly?

**Comment by mwjames** [comment]
> Call to what exactly?

As you assumed that `$mediaWiki->doPostOutputShutdown( 'fast' ); ` might be at fault, I was proposing the remove those steps and see whether that mitigates the issue or not.

**Comment by Nikerabbit** [comment]
Yes, if I remove that line then the text is displayed.

**Comment by mwjames** [comment]
Hi,

> Yes, if I remove that line then the text is displayed.

Thanks for the feedback.

I have been running 1.31 and 1.32 with `doPostOutputShutdown` being
called and the issue wasn't observed (not once).

So, I would appreciate to know whether doing a `doPostOutputShutdown`
[0] isn't something a third-party isn't suppose to do (the
documentation isn't clear on that) because using that function in my
understanding was a way to shutdown all open transactions that may be
running up to this point after which we can safely `die`.

Of course, if we don't have a satisfactory answer then we just remove
that part and we `die` and that's it.

[0] https://github.com/wikimedia/mediawiki/search?q=doPostOutputShutdown&unscoped_q=doPostOutputShutdown

Cheers
