### ISSUE TITLE
ERROR: Semantic MediaWiki must be installed for Semantic Dummy Editor to run!

### ISSUE THREAD

**Issue by dfhdfhdf** [SemanticMediaWiki/SemanticMediaWiki#3716]
### Setup and configuration

- SMW version: 2.5.8
- MW version: 1.28
- PHP version: 7.0
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB

I upgrading SMW from 2.5.8 to 3.0.0 bu composer. After i have error in site: ERROR: Semantic MediaWiki must be installed for Semantic Dummy Editor to run!. And same error in console after attemp run update.php.
Semantic Dummy Editor extension I not install early.

**Comment by mwjames** [comment]
> Semantic Dummy Editor extension I not install early.

?? Semantic Dummy Editor ??

What is this? This has nothing to do with SMW or is required by SMW itself.

**Comment by mwjames** [comment]
The only two reference I found was:

- https://github.com/wikimedia/mediawiki-extensions-SemanticDummyEditor
- https://github.com/ArchiXL/SemanticDummyEditor

none of which is maintained by the SMW project!

**Comment by dfhdfhdf** [comment]
So I do not understand where this error could come from.
I found an extension (https://www.mediawiki.org/wiki/Extension:SemanticDummyEditor) in the code that just has the text of this error.
However, I have never installed this extension.
This error occurred after attempting to update the data after installing the SMW 3.0.1.

**Comment by mwjames** [comment]
> This error occurred after attempting to update the data after installing the SMW 3.0.1.

No.

In your installation (or wiki) you have somewhere a reference to `SemanticDummyEditor` (`LocalSettings.php` or so) and again SMW has no bearing on that software.

Also, it should be clear that `LocalSettings.php` contains something like `enableSemantics( ... );` (as the documentation outlines) so that other software that checks against `SMW_VERSION` is correctly initialized.

**Comment by dfhdfhdf** [comment]
I tried again to go through all the steps.
Here is the listing from the console:
`root@s052d7b60:/var/www/anthecologyorg/data/www/anthecology.org# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 6 updates, 0 removals
  - Installing nicmart/tree (v0.2.7): Loading from cache
  - Installing react/promise (v2.7.1): Loading from cache
  - Installing guzzlehttp/streams (3.0.0): Loading from cache
  - Installing guzzlehttp/ringphp (1.1.1): Loading from cache
  - Installing elasticsearch/elasticsearch (v6.1.0): Loading from cache
  - Updating mediawiki/semantic-media-wiki (2.5.8 => 3.0.1): Loading from cache
  - Updating data-values/geo (1.2.2 => 2.0.0): Downloading (100%)
  - Updating mediawiki/semantic-result-formats (2.4.1 => 3.0.0): Loading from cache
  - Updating mediawiki/maps (4.0.4 => 5.0.0): Downloading (100%)
  - Updating mediawiki/semantic-meta-tags (1.3.0 => 2.0.0): Loading from cache
  - Updating mediawiki/semantic-compound-queries (1.0.1 => 2.0.0): Loading from cache
Package mediawiki/at-ease is abandoned, you should avoid using it. Use wikimedia/at-ease instead.
Writing lock file
Generating optimized autoload files
root@s052d7b60:/var/www/anthecologyorg/data/www/anthecology.org# cd /var/www/anthecologyorg/data/www/anthecology.org/maintenance
root@s052d7b60:/var/www/anthecologyorg/data/www/anthecology.org/maintenance# php update.php
ERROR: Semantic MediaWiki must be installed for Semantic Dummy Editor to run!root@s052d7b60:/var/www/anthecologyorg/data/www/anthecology.org/maintenance#
`

I repeat, that this extension has never been installed. It is missing in the extensions directory and not mentioned in LocalSettings.php.

**Comment by mwjames** [comment]
> I repeat, that this extension has never been installed. It is missing in the extensions directory and not mentioned in LocalSettings.php.

I doubt that because the message you get is from this line [0] which means that on your system this extension is installed somewhere and emits "ERROR: Semantic MediaWiki must be installed for Semantic Dummy Editor..." !

[0] https://github.com/ArchiXL/SemanticDummyEditor/blob/bd3e1304024616d320c6851143ae1a5efb193f56/SemanticDummyEditor.php#L39

**Comment by dfhdfhdf** [comment]
I searched all the files on the server with this error. And found it in the file extension Semantic Dependency Updater. I deleted this extension and the error disappeared.

Now update.php stay in:  ... changing type of field smw_id from 'INT(8) UNSIGNED NOT NULL KEY AUTO_INCREMENT' to 'INT(11) UNSIGNED NOT NULL KEY AUTO_INCREMENT' . This is normal? (site contain many semantic properties and values).

**Comment by mwjames** [comment]
> Now update.php stay in: ... changing type of field smw_id from 'INT(8) UNSIGNED NOT NULL KEY AUTO_INCREMENT' to 'INT(11) UNSIGNED NOT NULL KEY AUTO_INCREMENT' . This is normal? (site contain many semantic properties and values).

Yes (see the release  notes under 3360)

**Comment by dfhdfhdf** [comment]
Thank. I think the issue can be closed.

**Comment by mwjames** [comment]
> [0] https://github.com/ArchiXL/SemanticDummyEditor/blob/bd3e1304024616d320c6851143ae1a5efb193f56/SemanticDummyEditor.php#L39

For any folks that maintain extensions in connection with SMW.

We have been telling people for years that when checking `SMW_VERSION` it should be part of the `$wgExtensionFunctions` [0, 1] because only at this point all functions are setup correctly. It is even more important now that SMW is loaded via `extension.json` where any premature access (as in the case above) to one of the variables or constants (i.e. `SMW_VERSION` is a constant only to be defined after the extension has been registered and loaded) will fail as the initialization hasn't been finished.

[0] https://www.mediawiki.org/wiki/Manual:$wgExtensionFunctions
[1] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/SemanticExtraSpecialProperties.php#L66-L74

**Comment by mwjames** [comment]
> I upgrading SMW from 2.5.8 to 3.0.0 bu composer.

Make sure you update to 3.0.1!
