### ISSUE TITLE
Introduce Property:Implies namespace

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3743]
### Setup and configuration

- SMW version: 3.0.1

### Issue
It is not uncommon to have a property of datatype Page that is only meant for one namespace (for example `Has user` or `Has file`). There are currently two issues with such properties: redundant syntax and the possibility of improper values.

`[[Has user::User:Name]]` is redundant. While templates can help with this, there is no way to prevent redundancy when using the `+sep` parameter to allow something like `{{Foo|users=Bar, Baz}}` (at least not without an additional extension providing something like a `#arraymaptemplate` parser function).
Because the namespace is not implied it can be set to something improper. While this can be remedied with `Allows pattern`, it would be nicer if improper values were impossible.

I therefore propose the introduction of a `Implies namespace` special property for properties of the `Page` datatype. The implication mechanism would simply prefix the implied namespace when it is missing. Ideally both implied and explicit syntax would work for both annotating and querying.

**Comment by ankostis** [comment]
Wouldn't be better to be more generic, and have a validation template or rule(like #2273) that either returns nothing(ok), or something(invalid-message)?

**Comment by kghbln** [comment]
Thanks for suggesting an enhancement.

**Comment by mwjames** [comment]
>Wouldn't be better to be more generic, and specify with that new special property a validation template or rule(like #2273) that either returns nothing(ok), or something(invalid-message)?

I concur that introducing a more generic constraint check model is the way forward instead of introducing different special properties to cater for various use cases (unless they support a very broad scenario). So, while I understand the redundancy argument, we should avoid manipulating data by some hidden magic (unit and unit conversion is different in that respect) and instead make sure a user is informed about inconsistency of his/her data and can taken appropriate action to remove those obstacles that hinders the data storage.

#3746 contains an example and approach most likely to be available.

**Comment by mwjames** [comment]
> I therefore propose the introduction of a Implies namespace special property for properties of the Page datatype. 

Thanks for the general proposal and your engagement with the project.

As outline above, it is fairly unlikely that we will support "Implies namespace special property" in SMW-core (for reasons stated). Of course any custom datatype can implement such a support in an extension if the implementer requires additional restriction or supplement functionality.
