### ISSUE TITLE
Special:SemanticMediaWiki&action=duplookup refers to documentation that doesn't exist

### ISSUE THREAD

**Issue by kuality** [SemanticMediaWiki/SemanticMediaWiki#3744]
### Setup and configuration

MediaWiki | 1.32.0
PHP | 7.1.22 (cgi-fcgi)
MySQL | 5.6.34-log
Semantic MediaWiki | 3.0.1

### Issue
Special page Special:SemanticMediaWiki&action=duplookup (ie "duplicate entity link" from "supplemental functions") has two problems: 
* plural fails (this might have been corrected through another recent ticket already)
* contains a link to https://www.semantic-mediawiki.org/wiki/Help:Entity_table, a page that does not exist
I suppose in general the explanation on that page could be more helpful; I have things listed there but don't know what if anything I should do about it, from that page.

**Comment by kghbln** [comment]
Thanks for the report. Indeed the docu is not up to speed. A problem I am very well aware of.

> plural fails (this might have been corrected through another recent ticket already)

Yes, this is issue #3736 for which you should have received notifications and status updates.

> contains a link to https://www.semantic-mediawiki.org/wiki/Help:Entity_table, a page that does not exist

Not any longer since #3718 however I created a redirect to the [Table:smw_object_ids page](https://www.semantic-mediawiki.org/wiki/Table:smw_object_ids)

> I suppose in general the explanation on that page could be more helpful; I have things listed there but don't know what if anything I should do about it, from that page.

There is a link to the [duplicate entities][https://www.semantic-mediawiki.or/wiki/Help:Duplicate_entities) help page since #3718 which informs about circumstances and solutions.
