### ISSUE TITLE
`PageContentLanguage` should only return language objects not strings

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3767]
### Setup and configuration

- MediaWiki | 1.31.1 (cc69954)10:50, 6 March 2019
- PHP | 7.0.33-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.25-0ubuntu0.16.04.2
- Semantic MediaWiki | 3.0.1 (37c9525) 00:30, 25 January 2019

### Issue
The `PageContentLanguage` hook should only return language objects not strings since the latter may cause PHP fatals.

Refs: [T214358](https://phabricator.wikimedia.org/T214358) / In the light of current issues the respective documentation of the hook [was improved.](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/494748/)

Apparently SMW is only using the hook in it's test environment:
- [PageCreator.php#L39](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Utils/PageCreator.php#L39)
- [JsonTestCaseContentHandler.php#L116](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/JsonTestCaseContentHandler.php#L116)

I guess a fix could or should be back-ported to 3.0.x

See also https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/69

**Comment by mwjames** [comment]
> Refs: [T214358](https://phabricator.wikimedia.org/T214358) / In the light of
>

I think this is going in the wrong direction but first let me see if I
get the facts straight:

- The hook documentation explicitly says "Language|string &$pageLang" [0].
- Skimming the referenced issue, it was caused because someone
introduced a type hint in `TranslateHooks` (`TranslateHooks` should
account for a possible string or Language object)
- Now, all other extensions relying on the `PageContentLanguage` hook
are expected to be changed, right?

I haven't looked at the specific code but I'm questioning the
motivation to such change where a implicitly altered (well you can
append arguments but not alter existing types) hook definition is now
making others that depend on it inoperative.

In general, we (extension developers) rely on public APIs (hooks are
part of the public API) to be stable (and the documentation that
describe them) to cause less interruptions for us and our users.

Clearly from my point of view the correct course of action would have
been to "Fix the current code to say Language|string and remove the
explicit type hints." and NOT to "Fix MediaWiki core to always pass
objects. Two different types only causes troubles like this."

If you wanted to change the hook you could have introduced a new one
with a stricter API but now you created a precedence that other core
developers may find convenient to follow just to avoid going through
the deprecation policy and push work down to dependent parties.

PS: I understand the points raised in T214358 about "... Two different
types only causes troubles ..." but changing the API to mitigate an
issue isn't the answer.

[0] https://www.mediawiki.org/w/index.php?title=Manual:Hooks/PageContentLanguage&diff=prev&oldid=1066730,
mentions `Language|string &$pageLang` and this is from 2014

Cheers

**Comment by Nikerabbit** [comment]
Returning strings will still work fine. I only updated the documentation (and a few extensions) to prefer objects. This is not a breaking change. Consider it a soft deprecation if you wish. I suppose that could have been made clearer.

**Comment by mwjames** [comment]
Thanks for the clarification. Just let me add a final comment.

> Returning strings will still work fine.

In this case, we don't have to change anything since I'm a bit
reluctant to further spread `Language::factory(...)` in places unless
it is absolutely necessary.

The reason is that every time we have to rely on a foreign object
instance (that we can't fix ourselves) we run into the potential issue
that someone breaks it (in MW master) and we are forced to make an
emergency release (which may collide with the release version
boundaries) to mitigate the issue. I want less dependency on MW
objects and not more, if we need them then only in places that are
confined and limited.

Also, this avoids making a SIL release for something that was working
for the last three years.

> Consider it a soft deprecation if you wish. I suppose that could have been
> made clearer.

I suppose, the two choices you listed sounded more like either/or.

Cheers

**Comment by kghbln** [comment]
I think from what I read here that this may be closed until it is clear which exact changes in MediaWiki will be done to deal with this situation.
