### ISSUE TITLE
Special:SearchByProperty does not support records

### ISSUE THREAD

**Issue by Larivact** [SemanticMediaWiki/SemanticMediaWiki#3786]
### Setup and configuration

- SMW version: 3.0.1

### Issue

`Special:SearchByProperty` apparently does not give any results when you specify a value for a property of type record.

Steps to reproduce:

1. Go to https://www.semantic-mediawiki.org/wiki/Special:Browse/:Borussia-5FM%C3%B6nchengladbach
2. Click on a magnifier next to a soccer result.
3. No results.

**Comment by kghbln** [comment]
Thanks for reporting!

**Comment by mwjames** [comment]
Hi,

> `Special:SearchByProperty` apparently does not give any results when you
> specify a value for a property of type record.

This was never supported in the `Special:SearchByProperty` interface
since a record itself is a container and you cannot just compare a
simple value (string value) against such representation.

What you can try is to add `_rec` to the `smwgSearchByPropertyFuzzy`
setting (as it will switch on using the `QueryEngine`) to resolve the
value input.

Cheers

**Comment by kghbln** [comment]
> What you can try is to add `_rec` to the `smwgSearchByPropertyFuzzy` setting (as it will switch on using the `QueryEngine`) to resolve the value input.

@Larivact It will be great if you could report back after your test.

**Comment by kghbln** [comment]
Obviously the suggestion does not work. We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
