### ISSUE TITLE
Sorting by random returns variable number of results

### ISSUE THREAD

**Issue by Abijeet** [SemanticMediaWiki/SemanticMediaWiki#3788]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.29.1
- PHP version: 7.0.33-0+deb9u3 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.37-MariaDB-0+deb9u1

### Issue

On the semantic search page (WikiApiary), sorting by random returns different number of results each time.

- [Search with `asc` sort](https://wikiapiary.com/w/index.php?title=Special:Ask&q=%5B%5BHas+extension%3A%3AExtension%3ATranslate%5D%5D&p=format%3Dtable%2Flink%3Dall%2Fheaders%3Dshow%2Fmainlabel%3D-2D%2Fintro%3D-3Cb-3EThis-20extension-20is-20in-20use-20on-20the-20following-20websites%3A-3C-2Fb-3E-3Cbr-20-2F-3E%2Fsearchlabel%3D%E2%80%A6-20further-20results%2Fdefault%3DThis-20extension-20is-20no-20longer-20in-20use-20on-20any-20website.%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FHas+website%3DWiki+name%0A%3FHas+MediaWiki+version%3DMediaWiki+version%0A%3FHas+extension+version%3DExtension+version%0A&sort=Has+website&order=ascending&limit=250&eq=yes) - Returns 207 results every time.
- [Search with `random` sort](https://wikiapiary.com/w/index.php?title=Special%3AAsk&q=%5B%5BHas+extension%3A%3AExtension%3ATranslate%5D%5D&po=%3FHas+website%3DWiki+name%0D%0A%3FHas+MediaWiki+version%3DMediaWiki+version%0D%0A%3FHas+extension+version%3DExtension+version%0D%0A&eq=yes&p%5Bformat%5D=table&sort%5B0%5D=Has+website&order%5B0%5D=ASC&sort_num=&order_num=ASC&p%5Blimit%5D=250&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=Has+website&p%5Border%5D%5Brandom%5D=1&p%5Bheaders%5D=show&p%5Bmainlabel%5D=-&p%5Bintro%5D=%3Cb%3EThis+extension+is+in+use+on+the+following+websites%3A%3C%2Fb%3E%3Cbr+%2F%3E&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+further+results&p%5Bdefault%5D=This+extension+is+no+longer+in+use+on+any+website.&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&eq=yes) - Variable number of results

I've reviewed the release notes from the releases starting from 2.5.6, but did not notice this issue being addressed.

### Steps to reproduce

See links above.

**Comment by kghbln** [comment]
Thanks a lot for reporting. However I believe that this issue has been fixed in the meantime.

While listening to music on YouTube I have build up a data-set on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Songs_and_Tracks) to fiddle with:

Results:

- [Search with `asc` sort](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=YzpFkEFqwzAQRQ8UzBgHbwyzaNqEdtdFN12OnHEsLFllRsV0l9MEeo7epCfJqCYNDOLzvvQ_oyFJpIxOEh0zucAQfPQZm7Y2NU9IIcDIdGRR1DEtoEzSj4EcB_w9X6qmXthnFja1lxO72asy9IHUXiT5Sy23_ORvWuOylhUfn0mNfVkuJLEiJO0hDYNyxhqqdmfzSPnn-5TEc_cm1E9V-1SmqVf7HtF1m9WDanu4Y3wv8YZeCqHgPiM-lPOffbAM9hlW_3pTEMnP66ZX) - always 76 results

- [Search with `rand` sort](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&cl=YzpFkE1qwzAQhQ9UzBgXbwyzSP9od11k0-XIHsfCklVmFEx3PU0h58hNcpKOatLAIB7fk96TNCaJlNFJoiGTCwzBR5-xaWtTy4wUAkxMA4uiTmkFZZJ-CuQ44OX7p2rqlX1mYVPPcmC3eFWGPpDaiSR_qWWXn_1Va1y3suLjK6mxL8uFJFaEQsuQIqRxVM5YQ9U-2DxSPp8OSTx3e6F-rtqnMk292beUrrvbPKjuX24YP0qDobdCKLhjxF1Z_9kny2j_YTd4vyqI5Jftsb8) - always 76 results

Try for yourself but I believe this can be closed as resolved.

**Comment by Abijeet** [comment]
Hey @kghbln - Thanks for the quick response. I should have checked the sandbox and tried to repro it there. 

I'll report a ticket on the Wikiapiary phab about this.

**Comment by kghbln** [comment]
No worries. In the heat of the action. Yeah, Wikiapiary should be updated I believe.
