### ISSUE TITLE
MW 1.33+, master/tests are broken due to "Cannot override final method Job::getTitle"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3914]
### Setup and configuration

- SMW version: all
- MW version: 1.33+

### Issue

```
PHP Fatal error:  Cannot override final method Job::getTitle() in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Job.php on line 20
Fatal error: Cannot override final method Job::getTitle() in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Job.php on line 20
```

refs https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/519589131

### Caused by

https://github.com/wikimedia/mediawiki/commit/fc5d51f12936edb4c7d067e298b5ec3a7c09a8fa

**Comment by Seb35** [comment]
The method `SMW\MediaWiki\Job::getTitle()` was introduced in 0060dce seemingly because it was not present in MW 1.19. The function `Job::getTitle()` was introduced in MW in 1.21, hence it is present in all MW versions supported by SMW 3.0+ and this method can be removed from SMW.

I tested and it works correctly with SMW 3.0.2 + MW 1.34.

**Comment by mwjames** [comment]
> I tested and it works correctly with SMW 3.0.2 + MW 1.34.

Thanks.

We accept PRs and once the CI passes it is going to be merged.
