### ISSUE TITLE
beginSectionTransaction with retry instead of exception

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#3974]
beginSectionTransaction() throws an exception, when a sectionTransaction already exists. I have the case, where caused by Semantic Dependency Updater Extension a transaction is already active.

This causes "RuntimeException from line 862 of [...]/src/MediaWiki/Connection/Database.php: Trying to begin a new section transaction while SMWSQLStore3Writers::doDataUpdate is still active!"

Would it be possible / make sense to retry beginning a new sectionTransaction with increasing time offset and "wait" for the other transaction to be finished instead of throwing the exception?

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/fca1ba5caa9dee816a73cd70846fb71aa35946c3/src/MediaWiki/Connection/Database.php#L866

**Comment by mwjames** [comment]
Hi,

> beginSectionTransaction()

For details, see #3780.

> beginSectionTransaction() throws an exception, when a sectionTransaction
> already exists. I have the case, where caused by Semantic Dependency Updater
> Extension a transaction is already active.

This is the correct behaviour because it means someone (or something)
tries the run an update while there is still a transaction ongoing and
that should normally not occur to avoid race conditions or competing
updates.

The following advice is unrelated to Semantic MediaWiki, if you run
updates (those that modify the DB which `WikiPage::doPurge` is one of
them) on a the DB during a hook invocation then you should encapsulate
your process with a `Database::onTransactionIdle`, `DeferrableUpdate`,
or the JobQueue to isolate transactions from each other.

> Would it be possible / make sense to retry beginning a new
> sectionTransaction with increasing time offset and "wait" for the other
> transaction to be finished instead of throwing the exception?

On what basis would you use a time offset/wait counter, I'd say this
approach would be unreliable and uncontrollable since there is no
controlling entity that could decide what the time offset factor has
to be. You cannot just set `sleep(10)` in an active storage session
that depends on a SQL master/slave to store the requested changes as
soon as possible within a transaction round and within the capacity of
the backend.

By "controlling entity" I mean something like the `LBFactory` (and for
example `waitForReplication`) which relies on feedback from replicas
to throttle queued transactions.

So, the suggested approach of yours is unsuitable and instead use one
of those cited methods from above to encapsulate your hook to ensure
that "your work" doesn't interfere with others and their hooks.

PS: Semantic MediaWiki itself relies on the
`SMW::SQLStore::AfterDataUpdateComplete` hook to make updates after
the standard update as been completed, so making sure the transaction
round isn't disturbed is important.

Cheers

**Comment by gesinn-it** [comment]
Many thanks @mwjames for explaining the technical constraints. SDU has a switch to use the JobQueue. I'll retest with JobQueue enabled.

I tried to find an example, where DeferredUpdate is used in combination with doPurge and found https://github.com/wikimedia/mediawiki/blob/76fa847ef1279a875bb2b5e1248a502032b0be3d/includes/page/WikiFilePage.php#L171. If I find time, I'll try to incorporate this into SDU
