### ISSUE TITLE
PHP Fatal error: Cannot declare class SemanticMediaWiki

### ISSUE THREAD

**Issue by Seb35** [SemanticMediaWiki/SemanticMediaWiki#3984]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.32 and 1.34
- PHP version: 7.2
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7
- Composer version: 1.8.5

### Issue

I experienced the fatal error `PHP Fatal error:  Cannot declare class SemanticMediaWiki, because the name is already in use in /opt/mediawiki/extensions/SemanticMediaWiki/SemanticMediaWiki.php on line 31` first on a production wiki during upgrade and I was be able to re-create it on a fresh install.

It is the same issue than #1699, but I open this new one because the loading process changed quite a lot since.

### Steps to reproduce

On a fresh install with MediaWiki 1.34:
1. install MediaWiki, execute the standard setup creating LocalSettings.php
2. install SemanticMediaWiki with Composer, add `enableSemantics('localhost');` in LocalSettings.php
3. go to extensions/SemanticMediaWiki and execute `composer install --no-dev`
4. run `php maintenance/update.php --quick`
5. it returns the fatal error from #3914, which can be quickly fixed by removing the method `getTitle()` in `extensions/SemanticMediaWiki/src/MediaWiki/Job.php`
6. it returns the fatal error `PHP Fatal error:  Cannot declare class SemanticMediaWiki, because the name is already in use in /opt/mediawiki/extensions/SemanticMediaWiki/SemanticMediaWiki.php on line 31`

### Cause

In the previous steps, it must be removed the step 3 to solve the issue.

Because internally:
1. the global Composer autoloader loads the file `extensions/SemanticMediaWiki/SemanticMediaWiki.php` (specifically Composer, through autoload_real.php, `require` the file `/opt/mediawiki/vendor/composer/../../extensions/SemanticMediaWiki/SemanticMediaWiki.php`)
2. which executes [`SemanticMediaWiki::load()`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/7998790a7477475449d07bd38e7e637cf901612a/SemanticMediaWiki.php#L16)
3. which executes the [`include_once __DIR__ . '/vendor/autoload.php';`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/7998790a7477475449d07bd38e7e637cf901612a/SemanticMediaWiki.php#L42)
4. which loads the same file `extensions/SemanticMediaWiki/SemanticMediaWiki.php` (specifically Composer, through autoload_real.php, `require` the file `/opt/mediawiki/extensions/SemanticMediaWiki/vendor/composer/../../SemanticMediaWiki.php`, which is a different file from Composer’s point of view because this string representing the path is different)
5. which returns the fatal error.

### Solutions

1. It can be documented to never execute Composer inside the directory SemanticMediaWiki itself, at least for SMW ≥ 3.0.
2. It can be removed the Composer autoloader in `SemanticMediaWiki::load()`.
3. The class `SemanticMediaWiki` could be moved to a dedicated file. I saw it was the case in the #1700 and was removed in ff930da.

**Comment by mwjames** [comment]
> It can be removed the Composer autoloader in SemanticMediaWiki::load().

The reason why the call is necessary is explained in the file due to how `extension.json` is queuing extension definitions. We need certain constants and global functions before `LocalSettings.php` is invoked.

If users follow [0] then you will not encounter any of the issue as cited above.

PS: I spend a great deal of time (unfortunately) making sure `extension.json` and SMW work out of the box [1] and I'm not planning to revisit the approach anytime soon. So, if something can be removed without jeopardizing the existing infra and installation, I'm all for it but we should avoid any disruption.

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pulls?q=is%3Apr+extension.json+is%3Aclosed

**Comment by mwjames** [comment]
> go to extensions/SemanticMediaWiki and execute composer install --no-dev

Nowhere (to my knowledge) in the documentation is this step required, and in case it is, it should be removed because all necessary classes and libraries are installed during the first step.

**Comment by kghbln** [comment]
I have added this to the [troubleshooting issues](https://www.semantic-mediawiki.org/wiki/Help:Installation/Troubleshooting/PHP_Fatal_error:_Cannot_redeclare_class_SemanticMediaWiki)  however I would not like to add this to the general installation page to not even give people the idea that this could be done. Items 2 and 3 could be moved to separate tasks but given the very low changes that this will happend ...

**Comment by gesinn-it** [comment]
Today I came across the same issue following [1] which is mentioned in [2] ("Some notes about "How to use git and Composer" (for developers)").

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3346
[2] https://www.semantic-mediawiki.org/wiki/Help:Installation#Instructions

**Comment by mwjames** [comment]
> Today I came across the same issue following [1] which is mentioned in [2] ("Some notes about "How to use git and Composer" (for developers)").

Well, I just tried #3346 again and it just works as described without any "Cannot declare class SemanticMediaWiki" therefore I'm not sure what you did.

**Comment by mwjames** [comment]
> SemanticMediaWiki" therefore I'm not sure what you did.

If for some reason you run `composer update` from within the SemanticMediaWiki extension directory then yes, you would receive the error but #3346 didn't mentioned that step (you run Composer from the base directory of your MW installation).

It all comes down to Composer using `require` instead `require_once` but since that ship has sailed nothing much we can do aside from introducing a hack such as #3988 to hide the `SemanticMediaWiki.php` from the autoloader.

**Comment by gesinn-it** [comment]
@mwjames indeed I ran composer from SMW directory accidentally instead of MW root. I deleted my original comment in the meanwhile, but you were too fast having a look into it. Sorry for the unnecessary effort you had.

**Comment by gesinn-it** [comment]
When running `composer require --update-no-dev mediawiki/semantic-result-formats 3.0.0` after successful installation of SMW from git, I now get:

```
  Problem 1
    - Installation request for mediawiki/core No version set (parsed as 1.0.0) -> satisfiable by mediawiki/core[No version set (parsed as 1.0.0)].
    - mediawiki/semantic-result-formats 3.0.0 requires mediawiki/semantic-media-wiki ~3.0 -> satisfiable by mediawiki/semantic-media-wiki[3.0.0, 3.0.1, 3.0.2].
    - don't install mediawiki/semantic-media-wiki 3.0.0|remove mediawiki/core No version set (parsed as 1.0.0)
    - don't install mediawiki/semantic-media-wiki 3.0.1|remove mediawiki/core No version set (parsed as 1.0.0)
    - don't install mediawiki/semantic-media-wiki 3.0.2|remove mediawiki/core No version set (parsed as 1.0.0)
    - Installation request for mediawiki/semantic-result-formats 3.0.0 -> satisfiable by mediawiki/semantic-result-formats[3.0.0].
```

**Comment by mwjames** [comment]
> When running composer require --update-no-dev mediawiki/semantic-result-formats 3.0.0 after successful installation of SMW from git, I now get:

Of course, you cannot mix installation methods. Installation from git is as noted for developers (implicitly meaning the know those tools) and for expert users. You should stick with one method otherwise you end up with vendor mix due to how MW's own composer merge plugin is working.

A normal user is expected to use [0] not #3346 which I only added to demonstrate similarities between how SMW can be installed in comparison to Wikibase.

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide
