### ISSUE TITLE
Make service links usable outside of Special:Browse

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4020]
### Feature request
I tried to demonstrate the difference between Service links and the property External identifier [here](https://www.semantic-mediawiki.org/wiki/Help:Service_links#Difference_between_Service_links_and_External_identifier)

The downside of the service links feature is that it is only visible in Special:Browse, as you can see [here](https://www.semantic-mediawiki.org/wiki/Special:Browse/:Vienna)

The Vienna example shows that the service links questionmark shows up in Special:Browse while the property value is clickable directly when using the property type "External identifier". 

### Shortcomings
Both approaches have their shortcomings: Service links are great and flexible, as there can be many service links for every kind of property type, e. g. for geographic coordinates. But it is currenly only usable in Special.Browse.

External identifiers are great, but there can by definition be only one URI assigned to it via the property External formatter uri. If you set this property twice, the second value is valid.

### UseCase
Users should have the possibility of using service links without having to navigate to a special page.  

### Possible solution
The best option would probably be to offer this similar to the reference datatype:
![grafik](https://user-images.githubusercontent.com/4318745/57940050-f542ca00-78cb-11e9-9869-5d6f71b10491.png)

Similial to the reference datatype, service links should be displayed every time the property value shows up. Insted of the reference information, the assigned service links should be shown:
![grafik](https://user-images.githubusercontent.com/4318745/57940620-2374d980-78cd-11e9-9350-fc77678dbc11.png)

**Comment by mwjames** [comment]
> Users should have the possibility of using service links without having to navigate to a special page.

The community can provide a PR that enhance those "service links" [0] to be shown as in-page display.

## Note

I should note that the "service links" content should be converted away from the `MediaWiki` as it not owned by SMW and the behaviour of that NS could change with any MW release therefore relying on its availability for third-party users is not guaranteed. So, whoever touches the "service links" part should create a new schema type (`SERVICE_LINKS_SCHEMA`) in the `smw/schema` NS and provide a declarative property (`Service link schema`) to attach an individual schema to the property instead of linking to `MediaWiki:smw_service_...`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/DataValues/InfoLinksProvider.php

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
