### ISSUE TITLE
Minus prepended to queried negative values stored with datatype Number

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4071]
### Setup and configuration

- MediaWiki | 1.32.1 (b020b40)21:22, 4. Jun. 2019
- PHP | 7.2.17-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.2
- Semantic MediaWiki | 3.1.0-alpha (3b4b385) 00:08, 5. Jun. 2019

### Issue
A minus is being prepended to negative values stored with datatype Number. This happens for all ways to store the data, i.e. in-text, `#set` and `#subobject`. This is a 3.0.0 regression.

### Examples 
- [in text](https://sandbox.semantic-mediawiki.org/wiki/Issue/4071/in-text)
- [`#set`](https://sandbox.semantic-mediawiki.org/wiki/Issue/4071/set)
- [`#subobject`](https://sandbox.semantic-mediawiki.org/wiki/Issue/4071/subobject)

**Comment by mwjames** [comment]
> A minus is being prepended to negative values stored with datatype Number.
> This happens for all was to store the data, i.e. in-text, set and
> subobject.

To clarify, it is not a storage issue (you can check the RDF output or
the DB and you'll see it is stored correctly) but rather a formatting
issue [0, 1].

There was a PHP change [2] and [1] was suppose to counter this, yet
[1] is not strict enough but changing the following lines should fix
it and retain the known behaviour from before the PHP change..

Since we didn't detect a change in behaviour caused by [0] we have to
add a couple of tests to verify the output.

[0] #3374
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/DataValues/Number/IntlNumberFormatter.php#L327-L330
[2] https://bugs.php.net/bug.php?id=76824

**Comment by kghbln** [comment]
> To clarify, it is not a storage issue (you can check the RDF output or the DB and you'll see it is stored correctly) but rather a formatting issue [0, 1].

Indeed, the issues only arises when querying. The display of the  [in text](https://sandbox.semantic-mediawiki.org/wiki/Issue/4071/in-text) annotation already shows this. 

> There was a PHP change [2] and [1] was suppose to counter this, yet [1] is not strict enough but changing the following lines should fix

PHP making things better. ;) The lines did not make it to this issue.
