### ISSUE TITLE
Chinese users cannot install online, can you provide installation package download?

### ISSUE THREAD

**Issue by gy199108** [SemanticMediaWiki/SemanticMediaWiki#4087]
![QQ截图20190609200725](https://user-images.githubusercontent.com/23260568/59158897-dbc02700-8af3-11e9-9a2e-d5c7f95d43a0.png)
Hello, I am a Chinese user, because the network problem can not be installed online, can you provide the installation package to download?

**Comment by kghbln** [comment]
We deliberately decided not to do so. If online access is an issue you will have to find a person that can do an [individual file release](https://www.semantic-mediawiki.org/wiki/Help:Using_Composer#Individual_file_release) and provide the result to you. I guess this is the best approach in such a situation.

**Comment by mwjames** [comment]
> We deliberately decided not to do so. If online access is an issue you will
> have to find a person that can do an [individual file

Yes, and I sympathize with users who have issues with our
infrastructure partners such as packagist.org.

We choose [0, 1] no longer to provide tarballs as it bounds valuable
volunteer time of core project members that is spent better towards
improving the software instead of bundling software components for
each release. We rely on partners such as GitHub, Travis-CI,
packagist.org to provide the necessary user experience and help
project members to focus on core tasks.

Of course, community members (e.g. @krabina @gesinn-it @jaideraf) are
encouraged to provide tarballs [2] if necessary or ask for, but it
should not be expected that the project will provide such service.

If someone is to provide a site where bundled files can be downloaded,
we sure can link to it (given it uses https, and sha1 check sums) but
it would be an independent service and outside of the responsibility
of the project.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3346#issuecomment-415960117
[1] #3347
[2] https://github.com/SemanticMediaWiki/IndividualFileRelease

Cheers

**Comment by kghbln** [comment]
> Yes, and I sympathize with users who have issues with our infrastructure partners such as packagist.org.

This was not really clear from my ascetic response, but I do so too. Issue with connectivity can be really tough, not doubt about it.

**Comment by gesinn-it** [comment]
You can take a look at our free semantic::core go! distribution: https://sourceforge.net/projects/semantic-core-go/

This is not always the latest software versions but might help you getting started.
