### ISSUE TITLE
Using property OR in "conditions" parameter of askargs action

### ISSUE THREAD

**Issue by andrebgomes** [SemanticMediaWiki/SemanticMediaWiki#4090]
Sorry if this is the wrong place to ask this.

I'm trying to fetch results via API using the module askargs. I have no problems getting results when I have just one condition or more conditions aggregated with the operator AND where I make use of the pipe character to separate them.

E.g. [[Category:+]] AND [[Jurisdiction::A]] AND [[Type::B]]
Category:+ | Jurisdiction::A | Type::B

But the pipe character doesn't work with OR. Am I missing something?

**Comment by andrebgomes** [comment]
Hi,

I asked this same question on stackoverflow and I got a response with a possible solution for using both `AND` and `OR` conditions.

The idea is to change [this](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/cb928a5b475e0fe7943ddb7789eb3f6947ed8f0e/src/MediaWiki/Api/ApiRequestParameterFormatter.php#L132) function into something like this:

```
protected function formatConditions( $condition ) {
    if($condition!="OR")
    return "[[$condition]]";
    return $condition;
}
```

I really think this is something very useful to exist within the API, if not mandatory.

**Comment by mwjames** [comment]
> ```
> protected function formatConditions( $condition ) {
>     if($condition!="OR")
>     return "[[$condition]]";
>     return $condition;
> }
> ```

As for the `askargs` API, if someone sends a PR together with some
integration tests and updates the documentation then we might be able
to squeeze this in with next release otherwise I'm fairly busy to
review this myself and write appropriate tests to ensure we don't
break other consumers.

@kghbln Maybe ping interested parties that want to help here since
this issue is fairly isolated and doesn't require a lot of internal
SMW understanding.

**Comment by kghbln** [comment]
We need a developer for implementation. Thus I added this enhancement to the "Enhancements and features" project as "open". Closing here.
