### ISSUE TITLE
MW 1.33+: Migrate `$lang->viewPrevNext` to `$this->buildPrevNextNavigation`

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4092]
### Setup and configuration

- SMW version: 3.1+
- MW version: 1.33+

### Issue
`$lang->viewPrevNext` was deprecated in favour of `$this->buildPrevNextNavigation` and needs to be migrated.

Refs: [T207977](https://phabricator.wikimedia.org/T207977)

**Comment by kghbln** [comment]
@mwjames We will be getting [volunteer assistance](https://phabricator.wikimedia.org/T207977#5259038) for doing the migration. Cool. :)

**Comment by mwjames** [comment]
In response to Refs: T207977

> I'm a bit confused. SMW doesn't claim to be compatible with MW master. It's of course still useful to see in which ways it is incompatible, but to me it looks like that now a single patch would need to fix all incompatibilities to turn CI green, so other things can then be merged again. Is this the case? That seems awkward

Please don't make it sound as if this is an issue caused by SMW, the flow of changes to mw-master and issues like #4108 caused by __MediaWiki__ not by SMW making it maintenance intensive while trying to keep a project in line with those changes.

We test changes against mw-master but of course in a non-voting manner otherwise the CI would turn each week [0] red just because of some interfaces, classes, or services have been altered in a manner that makes the integration to break hereby calling for additional maintenance work.

Unless someone watches the mw-master queue each week and reviews the changes to it, it is predictable (using past experience as prediction model) that the mw-master queue will be broken within a month time.

I appreciated the support of @clarakosi but before reviewing the PR someone has to make sure that the CI works again (broken due to #4108) to ensure posted PRs can actually pass the CI including the mw-master queue.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues?q=label%3Amediawiki+is%3Aclosed
