### ISSUE TITLE
Documentation example for property "Has text" is throwing an error

### ISSUE THREAD

**Issue by jups23** [SemanticMediaWiki/SemanticMediaWiki#4094]
### Setup and configuration

- SMW version: 3.0.2
- MW version: 1.32.2
- PHP version: 7.2.3 (cgi-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 5.6.19-67.0-log

### Issue
When I paste the source text from https://sandbox.semantic-mediawiki.org/wiki/Issue/1481_(Fulltext)/Long_text_example_(The_Republic) in my installation fo the latest released version of Semantic MediaWiki I get the following error:

### Error message

```
"Property Has text with the following input value "<here comes the text>” contains invalid characters or is incomplete."
```

### Steps to reproduce
Duplicate the page https://sandbox.semantic-mediawiki.org/wiki/Issue/1481_(Fulltext)/Long_text_example_(The_Republic) in the installation of the current stable version.

**Comment by kghbln** [comment]
Probably caused by the same missing setting as mentioned here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4095#issuecomment-502402099

**Comment by kghbln** [comment]
I am afraid we cannot help you here since we are unable to determine the difference between your non-functional wiki and the functional sandbox. There is apparently something in the water but we do not know what it is. Please reopen as new information about what this may cause this come to light. I am sorry for this inconclusive closure.
