### ISSUE TITLE
When you don't have enableSemantics() an ugly exception appears

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4150]
### Setup and configuration

- SMW version: master
- MW version: 1.27
- PHP version: 7.3
- DB system (MySQL, Blazegraph, etc.) and version: sqlite

### Issue
Forgot enableSemantics() in my LocalSettings when working on a PF issue and got the following when PF invoked SMW. Adding enableSemantics results in the better error about a missing upgrade key.
```
Exception encountered, of type "RuntimeException"
[c5aa3545844ee55634e401c4] /core/index.php/Special:RunQuery/Hydro_lesson_query RuntimeException from line 70 of /home/mah/work/code/mediawiki/core/extensions/SemanticMediaWiki/src/Connection/ConnectionManager.php: mw.db is missing a registered connection provider
```
### Backtrace
```
#0 /../core/extensions/SemanticMediaWiki/src/Connection/ConnectionManager.php(32): SMW\Connection\ConnectionManager->findConnectionProvider(string)
#1 /../core/extensions/SemanticMediaWiki/src/Store.php(598): SMW\Connection\ConnectionManager->getConnection(string)
#2 /../core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(627): SMW\Store->getConnection(string)
#3 /../core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(285): SMWSQLStore3->getConnection(string)
#4 /../core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(854): SMWSql3SmwIds->getDatabaseIdAndSort(string, string, string, string, string, boolean, boolean)
#5 /../core/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(301): SMWSql3SmwIds->getSMWPropertyID(SMW\DIProperty)
#6 /../core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(190): SMW\SQLStore\EntityStore\EntityLookup->getPropertyValues(NULL, SMW\DIProperty, SMW\RequestOptions)
#7 /../core/extensions/PageForms/includes/PF_ValuesUtils.php(32): SMWSQLStore3->getPropertyValues(NULL, SMW\DIProperty, SMW\RequestOptions)
#8 /../core/extensions/PageForms/includes/PF_ValuesUtils.php(123): PFValuesUtils::getSMWPropertyValues(SMWSQLStore3, NULL, string, SMW\RequestOptions)
#9 /../core/extensions/PageForms/includes/PF_FormField.php(273): PFValuesUtils::getAllValuesForProperty(string)
#10 /../core/extensions/PageForms/includes/PF_FormPrinter.php(1010): PFFormField::newFromFormFieldTag(array, PFTemplate, PFTemplateInForm, boolean)
#11 /../core/includes/StubObject.php(105): PFFormPrinter->formHTML(string, boolean, boolean, integer, NULL, NULL, NULL, boolean, boolean)
#12 /../core/includes/StubObject.php(129): StubObject->_call(string, array)
#13 /../core/extensions/PageForms/specials/PF_RunQuery.php(79): StubObject->__call(string, array)
#14 /../core/extensions/PageForms/specials/PF_RunQuery.php(26): PFRunQuery->printPage(string, boolean)
#15 /../core/includes/specialpage/SpecialPage.php(479): PFRunQuery->execute(string)
#16 /../core/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(string)
#17 /../core/includes/MediaWiki.php(282): SpecialPageFactory::executePath(Title, RequestContext)
#18 /../core/includes/MediaWiki.php(735): MediaWiki->performRequest()
#19 /../core/includes/MediaWiki.php(509): MediaWiki->main()
#20 /../core/index.php(43): MediaWiki->run()
#21 {main}
```

**Comment by kghbln** [comment]
Thanks for reporting. SMW could probably fail more gracefully here.

**Comment by mwjames** [comment]
> Forgot enableSemantics() in my LocalSettings when working on a PF issue and got the following when PF invoked SMW. Adding enableSemantics results in the better error about a missing upgrade key.
> #7 /home/mah/work/code/mediawiki/core/extensions/PageForms/includes/PF_ValuesUtils.php(32): SMWSQLStore3->getPropertyValues(NULL, SMW\DIProperty, SMW\RequestOptions)
#8 /home/mah/work/code/mediawiki/core/extensions/PageForms/includes/PF_ValuesUtils.php(123): PFValuesUtils::getSMWPropertyValues(SMWSQLStore3, NULL, string, SMW\RequestOptions)
#9 /home/mah/work/code/mediawiki/core/extensions/PageForms/includes/PF_FormField.php(273): PFValuesUtils::getAllValuesForProperty(string)
#10 /home/mah/work/code/mediawiki/core/extensions/PageForms/includes/PF_FormPrinter.php(1010): PFFormField::newFromFormFieldTag(array, PFTemplate, PFTemplateInForm, boolean)
#

So yes, because the developer tries to access SMW [0] without checking it actually can by only relying on checking for this existence of a class. I have telling people for years, if they want to be sure they a have access to fully initialized SMW instance they are required to check for : 

```
	// Is SMW loaded and accessible?
	if ( !defined( 'SMW_VERSION' ) ) {
		return;
	}
```

We cannot provide any better message because PF tries to access an instance that isn't setup correctly and fails since the setup wasn't finalized with "ConnectionManager.php: mw.db is missing a registered connection provider".

> SMW could probably fail more gracefully here.

No we cannot since someone tries to access an instance outside of SMW core where we have no control over the error display.

[0] https://github.com/wikimedia/mediawiki-extensions-PageForms/blob/master/includes/PF_Utils.php#L103-L112

**Comment by kghbln** [comment]
> No we cannot since someone tries to access an instance outside of SMW core where we have no control over the error display.

Fair enough. Assuming what we will get the expected informatory error screen as soon as SMW is accessed correctly I am closing this.

**Comment by mwjames** [comment]
> Assuming what we will get the expected informatory error screen as soon as SMW is accessed correctly I am closing this.

If PF tries access SMW (given it checks for `SMW_VERSION`) and it cannot then it is the job of PF to inform users that it is unable to do so because of an incorrect setup.

We could do something in `ConnectionManager->getConnection(string)` and checking for `if ( !defined( 'SMW_VERSION' ) )` and fail hard and call the error screen.

If someone wants to tackle this, feel free with something like:

```
 namespace SMW\Connection;
 
 use RuntimeException;
+use SMW\SetupCheck;
 
 /**
  * @license GNU GPL v2+
  * @since 2.1
  *
@@ -65,9 +66,18 @@ class ConnectionManager {
 
 		if ( isset( self::$connectionProviders[$id] ) ) {
 			return self::$connectionProviders[$id];
 		}
 
+		// #4150
+		if ( !defined( 'SMW_VERSION' ) ) {
+			$setupCheck = new SetupCheck();
+
+			if ( $setupCheck->hasError() ) {
+				$setupCheck->showErrorAndAbort( $setupCheck->isCli() );
+			}
+		}
```

**Comment by mwjames** [comment]
@kghbln @hexmode I'll leave this to both you how to proceed with this issue.

PS: I haven't tested above suggestion. It is based on a conjecture that if someone tries to call a connection, yet SMW isn't fully initialized then we assume that the setup wasn't done correctly.

**Comment by kghbln** [comment]
Which file are we talking about here. Cannot find the code.

**Comment by mwjames** [comment]
> Which file are we talking about here. Cannot find the code.

`SMW\Connection\ConnectionManager.php`
