### ISSUE TITLE
Offset greater as `smwgQUpperbound`, the default 0 is used instead

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4263]
### Setup and configuration

- SMW version: all
- MW version: all

### Issue

This is more of a documentation issue, or something to mull over since I've been caught by surprise. When creating a query with a large offset where the offset exceeds the `smwgQUpperbound` setting then `ProcessedParam` will return with the default value (which in case of `offset` is 0) for that parameter.

**Comment by kghbln** [comment]
This is now documented on page [`$smwgQUpperbound`](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgQUpperbound&type=revision&diff=71581&oldid=64763) and on page [inline queries.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AInline_queries&type=revision&diff=71582&oldid=63680) I think this is a bug which needs to be fixed some time. This is not top priority since configuration changes can help here but ...
