### ISSUE TITLE
#show cannot longer query subobjects 

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4317]
### Setup and configuration

- SMW version: 3.1.0 (updated from 3.0.1)
- MW version: 1.33.0
- PHP version: 7.2.19
- MariaDB version: 10.1.41

### Issue
When upgrading from SMW 3.0.1 to 3.1.0 I noted some of my `#show` queries stoped working. Then I discover they were `#show` queries related to subobjects.

### Steps to reproduce
Compare the following pages (the content is the same) and note the last result.

SMW 3.0.1: http://wiki.fabricioassumpcao.com/wiki/User:Jaider
SMW 3.1.0: https://sandbox.semantic-mediawiki.org/wiki/Issue/4317

**Comment by mwjames** [comment]
> stoped working. Then I discover they were `#show` queries related to
> subobjects.

It relates to #4078, the fix would be simple but since tests are
missing for this use case, no one has discovered this before the
release so this has to wait (see the 4078 for how to retain the old
behaviour) since I'm not available before December.

The same goes for redirects in combination with #show, here as well
did we miss a test. Again, the fix in itself is small and easy but
without proper test coverage adding such a fix only brings you halfway
through and doesn't prevent any regressions in future.

**Comment by jaideraf** [comment]
Thanks a lot @mwjames! No pressure at all, in fact I have already substituted all my `#show` queries by `#ask` queries and everything is working as expected. I just wanted you to know about it. :+1:

**Comment by jaideraf** [comment]
Confirmed, fixed. :1st_place_medal: 
Thanks again!
