### ISSUE TITLE
MW 1.34+ Return value of Parser::getTitle() must be an instance of Title, null returned

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4330]
### Setup and configuration

- MediaWiki | 1.34.0-rc.0 (366bf66)22:03, 15 October 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (c0b7a8f) 17:35, 14 October 2019

### Issue
Running "update.php" causes the following error:

Importing from smw.groups.json ...
   ... replacing smw/schema:Group:Schema properties
       importer was last editor ...
```
TypeError from line 930 of /../w/includes/parser/Parser.php: Return value of Parser::getTitle() must be an instance of Title, null returned
```

### Stack trace

```
#0 /../w/includes/StubObject.php(112): Parser->getTitle()
#1 /../w/includes/StubObject.php(138): StubObject->_call(string, array)
#2 /../w/extensions/Lingo/src/LingoParser.php(417): StubObject->__call(string, array)
#3 /../w/extensions/Lingo/src/LingoParser.php(81): Lingo\LingoParser->shouldParse(StubObject)
#4 /../w/extensions/Lingo/src/Lingo.php(53): Lingo\LingoParser->parse(StubObject)
#5 /../w/includes/Hooks.php(174): Lingo\Lingo::Lingo\{closure}(SMW\MediaWiki\Content\SchemaContent, Title, ParserOutput)
#6 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#7 /../w/includes/content/AbstractContent.php(559): Hooks::run(string, array)
#8 /../w/includes/Revision/RenderedRevision.php(267): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#9 /../w/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(SMW\MediaWiki\Content\SchemaContent, boolean)
#10 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#11 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#13 /../w/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#14 /../w/includes/Storage/DerivedPageDataUpdater.php(1290): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /../w/includes/Storage/PageUpdater.php(725): MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#16 /../w/includes/page/WikiPage.php(1931): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#17 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(124): WikiPage->doEditContent(SMW\MediaWiki\Content\SchemaContent, CommentStoreComment, integer)
#18 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(110): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent(WikiPage, Title, SMW\Importer\ImportContents)
#19 [internal function]: SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}(integer, Wikimedia\Rdbms\DatabaseMysqli)
#20 /../w/includes/libs/rdbms/database/Database.php(3617): call_user_func(Closure, integer, Wikimedia\Rdbms\DatabaseMysqli)
#21 /../w/includes/libs/rdbms/database/Database.php(3417): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks(integer)
#22 /../w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle(Closure)
#23 /../w/includes/libs/rdbms/database/DBConnRef.php(594): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#24 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(764): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle(Closure)
#25 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(111): SMW\MediaWiki\Connection\Database->onTransactionIdle(Closure)
#26 /../w/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create(SMW\Importer\ImportContents)
#27 /../w/extensions/SemanticMediaWiki/src/Importer/Importer.php(133): SMW\Importer\ContentCreators\DispatchingContentCreator->create(SMW\Importer\ImportContents)
#28 /../w/extensions/SemanticMediaWiki/src/Importer/Importer.php(109): SMW\Importer\Importer->doImportContents(SMW\Importer\ImportContents)
#29 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1352): SMW\Importer\Importer->doImport()
#30 /../w/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete(SMW\SQLStore\TableBuilder\MySQLTableBuilder, Onoi\MessageReporter\ObservableMessageReporter, SMW\Options)
#31 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#32 /../w/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(191): Hooks::run(string, array)
#33 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(437): SMW\SQLStore\Installer->install(SMW\Options)
#34 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(326): SMW\SQLStore\SQLStore->setup(SMW\Options)
#35 /../w/extensions/SemanticMediaWiki/src/Store.php(506): SMW\Elastic\ElasticStore->setup(SMW\Options)
#36 /../w/includes/installer/DatabaseUpdater.php(490): SMW\Store::setupStore(boolean, SMW\Options)
#37 /../w/includes/installer/DatabaseUpdater.php(458): DatabaseUpdater->runUpdates(array, boolean)
#38 /../w/maintenance/update.php(205): DatabaseUpdater->doUpdates(array)
#39 /../w/maintenance/doMaintenance.php(99): UpdateMediaWiki->execute()
#40 /../w/maintenance/update.php(277): require_once(string)
#41 {main}

```

**Comment by kghbln** [comment]
Lately we are getting this instance of Title error all over the place. 

@s7eph4n I see Lingo in here. Thus pinging in case it is a Lingo issue preventing fluff.

**Comment by s7eph4n** [comment]
On the other hand see https://phabricator.wikimedia.org/T235392

**Comment by kghbln** [comment]
Looks like there is a lot of fun ahead of us...

**Comment by mwjames** [comment]
> On the other hand see https://phabricator.wikimedia.org/T235392

I'm going to have a field day with this but first let me explain the
core issue here as it seems those developers on T235392 are somewhat
are unable to respond to the issue itself.

## TypeError

As for "TypeError from line 930 of /../w/includes/parser/Parser.php:
Return value of Parser::getTitle() must be an instance of Title, null
returned":

As for `Parser::getTitle`, whether documented or not was allowed (or
could) return NULL as value making it necessary for extensions to
check in their application whether the instance returned from this
method is actually a `Title` instance or not.

Now, some eager developer thought (see T235392 for reference) "cool" I
can use PHP type hints so let's make `Parser::getTitle` to be defined
as `:Title` meaning that only `Title` is allowed to be returned hereby
introducing a breaking change with its semantics resulting in
extensions that call `Parser::getTitle` to be broken because the
assumption that the developer made about `mTitle` (internally the
property holding the value) to be never NULL is not true (as evident
by this very issue).

So, the strict type cast of `:Title` forces PHP to emit a `TypeError`
because `mTitle` holds a NULL value.

## T235392

Back to T235392, I cannot really believe what I'm reading here, the
first WMF developer suggesting to make all methods `@internal` in the
`Parser` has nothing do to whatsoever with breaking the semantics of
`Parser::getTitle` and the PHP `TypeError`.

Furthermore, using the loophole of `@internal` to retrospectively
indicate that extension developers would be to blame that there are
using internal methods hence they cannot make any claims in regards to
the deprecation policy is outright ridiculous.

Seriously, why not mark all methods in MediaWiki as `@internal` so any
external developer (meaning not WMF) has no claimable right of any
wrongdoing because "we (as in "the WMF", maintainer of MediaWiki) are
to change signatures of methods any time as it suits us" and since
there are `@internal` shifting responsibility towards extension
developers to be at fault by relying on those methods. Well, thanks
for that, extension developers have nothing else to do as to keep
track on changes to interfaces and method signatures.

Introducing `Parser::hasTitle` as a substitute does nothing more as
shifting work towards extension developers to update their extension
while extensions remain broken that rely on `Parser::getTitle`.

The next WMF developer talks about "mental cycles" and PHP/Parsoid
where the WMF (implicitly as pointing fingers towards resource
shortage) apparently has no interest in working with non-WMF
developers when the times comes of replacing PHP/Parser with
PHP/Parsoid.

I wonder what sort of  "mental cycles" are required here since the
initial report is solely about the `TypeError` without mentioning of
PHP/Parsoid once.

Those people and how they respond makes you want to quit the whole
extension development support.

**Comment by reedy** [comment]
You're more than welcome to contribute upstream, and participate in the Code Review process.

**Comment by cscott** [comment]
Without getting into the ad hominems, core code never allows the `mTitle` property to be `null`.  We've deprecated use of Parser without initializing `mTitle` to give a transition.  I'd recommend ensuring that the title of all Parser objects is set to something; perhaps you want to create a unique 'bogus title' object and set `mTitle` to that in order to get the same sort of behavior you previously had when `mTitle` was left uninitialized.  That will be backwards compatible with versions of mediawiki <= 1.34, and will continue to work in MW 1.35 when core code will enforce the initialization of `mTitle`.

**Comment by kghbln** [comment]
I am not sure if there is an actionable task for SMW. Moreover have not had this since. Closing for now. In case it comes back the issue may be re-opened.

**Comment by justinclloyd** [comment]
I'm hitting this as well in testing rebuildData.php on MW 1.36 with SMW 3.2.3 and Page Forms 5.2.1. Also, --ignore-exceptions does not skip over it.
