### ISSUE TITLE
illegibly dark leaflet display

### ISSUE THREAD

**Issue by 500cents700** [SemanticMediaWiki/SemanticMediaWiki#4352]
### Setup and configuration

- SMW version:3.1.0
- MW version:1.33.1
- PHP version:7.2.24 (litespeed)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB -10.1.40-MariaDB-cll-lve

### Issue
Leaflet maps using the basic parser function have defaulted to a rather illegible, black and grey skin. The change seems to have been recent and I am unclear whether it was intentional or coinciding with climate strike week(?). 

### Steps to reproduce
The issue seems to be true across smw mediawiki installations, including, e.g.:
https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_with_a_static_map

**Comment by JeroenDeDauw** [comment]
Can you post a screenshot? The linked maps are showing fine for me:

![image](https://user-images.githubusercontent.com/146040/68984048-80b2fe80-080e-11ea-9d46-a9670f75dc2d.png)

**Comment by JeroenDeDauw** [comment]
The map is showing dark for you because of some browser settings you have. I have actually never seen the dark mode maps. This is a new [feature added by @vedmaka in Maps 7.10](https://github.com/JeroenDeDauw/Maps/commit/3e2af9bbeab68be0d0dcb73fb8913375d81f387f) 

@vedmaka would be cool if you could resolve this

@500cents700 this would have been a better place to post the issue: https://github.com/JeroenDeDauw/Maps/issues

**Comment by kghbln** [comment]
Transferred to https://github.com/JeroenDeDauw/Maps/issues/588
