### ISSUE TITLE
Formatting display of a year-only date as ISO also displays month and day

### ISSUE THREAD

**Issue by Dinoguy1000** [SemanticMediaWiki/SemanticMediaWiki#4373]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.2.13-1+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.1.31-MariaDB-1~xenial

### Issue
If you store a date to a date-type property, where the stored date consists only of a year, and then display that date on some page with the `#ISO` syntax to display it as an ISO date, it displays a month and day as well (e.g. storing `2005` and then displaying with `#ISO` results in `2005-01-01` being displayed). This is counter to [Help:Type Date#ISO](https://www.semantic-mediawiki.org/wiki/Help:Type_Date#ISO), which states:
> Display takes into account if parts of a date were omitted. So a date specified as "2008" will also be printed as "2008" everywhere, even though it might be interpreted as "Jan 1 2008 00:00:00" when comparing it to other dates.

For example, [Special:Browse/:Summoned-5FSkull-5F(CM)](https://yugipedia.com/wiki/Special:Browse/:Summoned-5FSkull-5F(CM)) shows `2005` for "Debut date", but [Summoned Skull#In other media](https://yugipedia.com/wiki/Summoned_Skull#In_other_media) (which has as part of the query `?Debut date#ISO`) produces `2005-01-01` for the "Summoned Skull (CM)" row.

Note that while this is being reported in the context of an MW 1.31.1 installation with SMW 3.0.0, it has also been confirmed on MW 1.19.24 running SMW 2.4.6; see [example](https://yugioh.fandom.com/wiki/Special:Ask?q=%5B%5BKonami+official+tournament+2004+participation+card%5D%5D&p=format%3Dbroadtable%2Flink%3Dall%2Fheaders%3Dshow%2Fsearchlabel%3D...-20further-20results%2Fclass%3Dsortable-20wikitable-20smwtable&po=%3FJapanese+release+date%0A%3FJapanese+release+date%23ISO%3DJapanese+release+date+ISO%0A&sort=Japanese+release+date&limit=500&eq=no) (and [Special:Version](https://yugioh.fandom.com/wiki/Special:Version)).

It is entirely possible that this behavior is intentional, in which case the documentation should be updated to reflect it (and should have been years ago, given SMW 2.4.6 was released in February 2017). The wording on [this archive page](https://www.semantic-mediawiki.org/wiki/Archive:Type_Date_1.7.1#Display_format) supports the idea that the paragraph didn't originally refer to the ISO display format, but was forgotten in the process of some past restructuring of the page. Either way, there's a documentation-implementation inconsistency here which needs to be resolved.

**Comment by kghbln** [comment]
@Dinoguy1000 Thank you for your elaborate issue description. I believe that this is a documentation issue as the output of the `#ISO` printout formatter is consistent for displaying partial date information [(example).](https://sandbox.semantic-mediawiki.org/wiki/Issue/4373)

We will definitively need to extend [existing test cases](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0423.json) to include the `#ISO` printout formatter to assure that there is no change in the future.

**Comment by mwjames** [comment]
> @Dinoguy1000 Thank you for your elaborate issue description. I believe that
> this is a documentation issue as the output of the `#ISO` printout formatter
> is consistent for displaying partial date information
> [(example).](https://sandbox.semantic-mediawiki.org/wiki/Issue/4373)

As noted in both [0] (SMW 3.1+) and [1] (SMW 1.8) "The date includes
year, month, and day regardless of the input precision, but will only
include time when specified." which means independent of the precision
specified or whether only a year is available (or annotated) the
output will at least consist of YYYY-MM-DD so that something like
[[Has date::1999]] will be formatted in the ISO format as 1999-01-01.

One could desire a change to the output characteristics of the ISO
format (in [0]) but it would require a significant reasoning to
convince me that such a change provides some benefits especially given
that the current behaviour has been in place since at least SMW 1.8
and changing an establish format seems unlikely to happen for "just" a
presentation adjustment.

> For example, Special:Browse/:Summoned-5FSkull-5F(CM) shows 2005 for "Debut date", but Summoned Skull#In other media (which has as part of the query ?Debut date#ISO) produces 2005-01-01 for the "Summoned Skull (CM)" row.

`Special:Browse` doesn't show (or better uses) the ISO formatter which
is the reason why the output is different.

> We will definitively need to extend existing test cases to include the #ISO printout formatter to assure that there is no change in the future.

Yes (There are a couple of more tests [2] that have a reference to `#ISO`).

Instead of extending the mentioned test above maybe create a new file
and add a couple of year (yyyy), year-month (yyyy-mm), year-month-day
(yyyy-mm-dd), year-month-day-time (yyyy-mm-dd hh:mm:ss) annotations
together with their output verification.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/DataValues/ValueFormatters/TimeValueFormatter.php#L59-L105
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8/includes/datavalues/SMW_DV_Time.php#L705-L735
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?l=JSON&q=ISO

**Comment by kghbln** [comment]
The confusing information [was added](https://www.semantic-mediawiki.org/w/index.php?title=Help:Type_Date&diff=next&oldid=1352) as a general remark for displaying in-text annotations and was unrelated to the formatting done by result formatters. Somehow it ended up as a section of the `ISO` result formatter which is apparently misleading. Thus I [amended the docu](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AType_Date&type=revision&diff=73579&oldid=69272).

> Instead of extending the mentioned test above maybe create a new file
and add a couple of year (yyyy), year-month (yyyy-mm), year-month-day
(yyyy-mm-dd), year-month-day-time (yyyy-mm-dd hh:mm:ss) annotations
together with their output verification.

Will provide a json test today after tea.

**Comment by mwjames** [comment]
> Instead of extending the mentioned test above maybe create a new file
and add a couple of year (yyyy), year-month (yyyy-mm), year-month-day
(yyyy-mm-dd), year-month-day-time (yyyy-mm-dd hh:mm:ss) annotations
together with their output verification.

#4389 provides various test cases in regards to the ISO output including a case that covers the mentioned "... storing 2005 and then displaying with #ISO results in 2005-01-01 being displayed) ..." such as `[[Has date::2020]]` to produce the expected output of `2020-01-01`.

```
		{
			"type": "parser",
			"about": "#1 query with `#show` for year in 'ISO' format",
			"subject": "Example/4373/1/query",
			"assert-output": {
				"to-contain": [
					"2020-01-01"
				]
			}
		},
```
