### ISSUE TITLE
SMW Documentation for $mswgQMaxInLineLimit

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#4384]
### Issue
* https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxInlineLimit
* https://www.semantic-mediawiki.org/wiki/Help:$smwgQMaxLimit

have confusing and contradicting example text e.g.

```
$smwgQMaxLimit = 250;

This means that embedded queries or special page "Ask" will use "100" as a value for the limit parameter if no other value was specified for it explicitly. 

```
I'd fix it myself if i'd know what the intended meaning is which i can't figure out giving the confusion created ...

A hint to format=count would also be helpful because count is not restricted and will be helpful in finding out what a useful limit is.

**Comment by WolfgangFahl** [comment]
```
# WF 2020-01-02
$smwgQMaxInlineLimit = 10000;
# default limit for queries
$smwgQMaxLimit = 10000;
```
has not the desired effect for me in a SMW 1.27.3 using Semantic Mediawiki 2.5.8. 
I have an ask query with format count that shows 3569.
I then use a similar query with limit=4000 and it still shows "further results ..." at the end. Which is the configuration parameter I need to set and how?

**Comment by kghbln** [comment]
Thanks for reporting. I will have a look.

**Comment by kghbln** [comment]
> This means that embedded queries or special page "Ask" will use "100" as a value for the limit parameter if no other value was specified for it explicitly. 

Indeed, this was a typo which Jeroen [fixed](https://www.semantic-mediawiki.org/w/index.php?title=Help:$smwgQMaxLimit&diff=73524&oldid=71576).

I now [tested you settings on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/4384) and it works as expected. Since I changed the configuration back to lower limits I provide a screenshot of the result:

![Bildschirmfoto vom 2020-01-11 11-16-41](https://user-images.githubusercontent.com/1104078/72202850-7145df80-3464-11ea-8348-934649e070db.png)

**Comment by kghbln** [comment]
Oops `$smwgQMaxLimit` was indeed documented incorrectly, so I [amended it.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgQMaxLimit&type=revision&diff=73567&oldid=73524)

**Comment by kghbln** [comment]
Apparently `$smwgQMaxInlineLimit` was messed too and needed to be [rectified](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgQMaxInlineLimit&type=revision&diff=73574&oldid=71577).
