### ISSUE TITLE
SMW\MediaWiki\PageInfoProvider::getCreationDate() can be called when there is no first revision

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4486]
### Setup and configuration

- SMW version:  2.5.7 (d528e24)
- MW version:  1.27.3 (73756b7)
- PHP version: 5.6.27
- DB system (MySQL, Blazegraph, etc.) and version: Percona 5.7.23-23-57-log

### Issue
Whether due to my particular config or some other problem in SMW, `SMW\MediaWiki\PageInfoProvider::getCreationDate()`  was called without an initial revision being created for a page.

### Stack trace
Instrumenting the function and adding `debug_print_backtrace()` gave the following:
```
#0 .../extensions/SemanticMediaWiki/src/PropertyAnnotators/PredefinedPropertyAnnotator.php(92): SMW\MediaWiki\PageInfoProvider->getCreationDate()
#1 .../extensions/SemanticMediaWiki/src/PropertyAnnotators/PredefinedPropertyAnnotator.php(69): SMW\PropertyAnnotators\PredefinedPropertyAnnotator->createDataItemByPropertyId(string)
#2 .../extensions/SemanticMediaWiki/src/PropertyAnnotators/PropertyAnnotatorDecorator.php(61): SMW\PropertyAnnotators\PredefinedPropertyAnnotator->addPropertyValues()
#3 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(135): SMW\PropertyAnnotators\PropertyAnnotatorDecorator->addAnnotation()
#4 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(77): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->doExtendParserOutput(ParserOutput)
#5 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(264): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->process()
#6 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(WikiPage, Revision, boolean, User)
#7 .../includes/Hooks.php(195): call_user_func_array(Closure, array)
#8 .../includes/page/WikiPage.php(1903): Hooks::run(string, array)
#9 .../includes/page/WikiPage.php(1657): WikiPage->doCreate(WikitextContent, integer, User, string, array)
#10 .../includes/EditPage.php(2044): WikiPage->doEditContent(WikitextContent, string, integer, boolean, User, string, array)
#11 .../includes/EditPage.php(1395): EditPage->internalAttemptSave(array, boolean)
#12 .../includes/EditPage.php(578): EditPage->attemptSave(array)
#13 .../includes/actions/EditAction.php(59): EditPage->edit()
#14 .../includes/actions/SubmitAction.php(38): EditAction->show()
#15 .../includes/MediaWiki.php(493): SubmitAction->show()
#16 .../includes/MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#17 .../includes/MediaWiki.php(735): MediaWiki->performRequest()
#18 .../includes/MediaWiki.php(509): MediaWiki->main()
#19 .../index.php(43): MediaWiki->run()
#20 {main}
```

**Comment by kghbln** [comment]
Thanks for reporting.

**Comment by mwjames** [comment]
> #3 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(135): SMW\PropertyAnnotators\PropertyAnnotatorDecorator->addAnnotation()
#4 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(77): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->doExtendParserOutput(ParserOutput)
#5 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(264): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->process()
#6 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(WikiPage, Revision, boolean, User)
#7 .../includes/Hooks.php(195): call_user_func_array(Closure, array)

The hook is run on `NewRevisionFromEditComplete` and as the name suggests the revision insert is expected to be completed either for the first or any other revision.

If you look closely on what `Title::getFirstRevision` does you'll see that it fetches the data from `wfGetDB( $index )` which is the REPLICA when no flag is given. 

> DB system (MySQL, Blazegraph, etc.) and version: Percona 5.7.23-23-57-log

I assume you use a master/slave environment and my hypotheses is that when creating a page and the `Title::getFirstRevision` is called some slave lag exists which is the reason why there is no apparent revision because the data haven't been replicated.

I suggest you play around with these flags (such as `GAID_FOR_UPDATE` or `READ_LATEST`; please read the code comments on these flags, see also #4470 for some insights) to see whether you can deterministically create the issue or not and when you can set those flags hereby hopefully avoids the observed issue.

> 		if ( $this->wikiPage->getTitle()->getFirstRevision() === null ) {
>			return wfTimestamp( TS_MW, 0 );
>		}
> This looks good as a local fix though I'm wondering if it is treating a symptom rather than the root cause. I do not know the code well enough to tell. One for @mwjames

This can be added as counter measurement to avoid any user error but I suspect that setting the mentioned flags to read from master is the solution here given that we run on `NewRevisionFromEditComplete` for a page with a revision which means there must be a `FirstRevision` otherwise this hook shouldn't be called in the first place.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/Title.php#L3901-L3931

**Comment by mwjames** [comment]
> I assume you use a master/slave environment and my hypotheses is that when creating a page and the Title::getFirstRevision is called some slave lag exists which is the reason why there is no apparent revision because the data haven't been replicated.

??

**Comment by hexmode** [comment]
Your assumption about a master/slave (well, a cluster, but I'm using one of the cluster as primary because that is how MW is built) is correct.

I haven't had a chance to test your hypothesis yet.
