### ISSUE TITLE
Type mismatches

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#4545]
PHP 7.4.2, MW 1.34.0, SMW 3.1.3.

Sometimes, `maintamance/runJobs.php` and `maintenance/fixDoubleRedirects.php` issue warnings like this:
```
2020-02-12 20:40:02 refreshLinksPrioritized Шаблон:Tnavbar isOpportunistic=1 rootJobTimestamp=20200212202618 namespace=10 title=Tnavbar requestId=c8b843c55ee62b88a4d07cd2 causeAction=unknown causeAgent=unknown (id=12874279,timestamp=20200212202618) STARTING
PHP Notice:  Trying to access array offset on value of type int in /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 469
PHP Notice:  Trying to access array offset on value of type bool in /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

```

**Comment by mwjames** [comment]
> PHP 7.4.2, 

See https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4541#issuecomment-586554248.

**Comment by alex-mashin** [comment]
> > PHP 7.4.2,
> 
> See [#4541 (comment)](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4541#issuecomment-586554248).
Honestly, I don't understand.

Do you mean that PHP 7.2 or PHP 7.3 will be the maximum PHP version supported by SMW for ever? Or that, under any version of PHP, applying `[]` on integers an booleans is meaningful?

Although these two bugs seem to be duplicates.

**Comment by mwjames** [comment]
> Do you mean that PHP 7.2 or PHP 7.3 will be the maximum PHP version supported by SMW for ever? 

No, but currently I don't have time to add another PHP system (7.4) to my dev environment to figure out what has changed and how it affects SMW and what are the steps to remedy those issues. There is a reason why we keep a compatibility document otherwise its is just becomes a やりたい放題 (everything goes) which would mean nothing is tested, no one cares, and finally the software stops working.

It is similar to the discussion about supported MediaWiki releases just because MW added and extra release doesn't automatically mean it becomes compatible with SMW. In fact, everyone complaining about SMW not being compatible with the latest MW should invest some hours instead of blaming me (or others) or the lack of effort.

**Comment by kghbln** [comment]
> Honestly, I don't understand.

I am pretty sure you understood.

**Comment by kghbln** [comment]
Refs: #4547
