### ISSUE TITLE
sequence_map does not work with redirects

### ISSUE THREAD

**Issue by Gittenburg** [SemanticMediaWiki/SemanticMediaWiki#4669]
### Setup and configuration

- SMW version: 3.1.0
- MW version: 1.33.0
- PHP version: 7.3.14-1~deb10u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.44-MariaDB-0+deb9u1

### Issue
The [sequence map feature](https://www.semantic-mediawiki.org/wiki/Help:Sequence_map) introduced in #4227 does not preserve the value order if there are redirects (the value of a property with datatype page redirects to another page).

### Steps to reproduce

1. Create `SMW/Schema:Seqmap` with:

     ```
	{
	    "type": "PROPERTY_PROFILE_SCHEMA",
	    "profile": {
	        "sequence_map": true
	    },
	    "tags": [
	        "property profile"
	    ]
	}
    ```

2. Create `Property:name` with `[[profile schema::seqmap]]`.
3. Run `rebuildData.php`.
4. Create `Foo` with `#redirect [[baz]]`.
5. Create `Test` with `[[name::foo]], [[name::bar]]`.
6. `{{#show: Test |?name}}` yields `Bar, Baz` instead of `Baz, Bar`

**Comment by mwjames** [comment]
> Create Foo with #redirect [[baz]].

So, yes this use case isn't covered (meaning hasn't been tested and therefore isn't supported).

It would demand some extra work to ensure we avoid needless DB queries when building the `QueryResult` for page typed values to decide whether a specific value is a redirect or not and if, so then would require to use the redirect source (the #ask/#show use the target as value reference) as hashed value for comparison since the `sequence_map` is a simple map of hashed values from the source input.

**Comment by Gittenburg** [comment]
Thank you very much for the quick fix!

**Comment by mwjames** [comment]
> Thank you very much for the quick fix!

Well, it won't be available for a minor release which means it is going to be deployed with SMW 3.2.
