### ISSUE TITLE
"Auto-enable by composer ... agreed by all but SMW"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4773]
With reference to the following thread [0] and the statement "Auto-enable by composer probably isn't a good idea, this is agreed by all but SMW."

> (Cindy) Couple of different aspects. Extensions dependent on MW Core version, i.e. Chameleon → Bootstrap → SCSS.
(Markus) Auto-enable by composer probably isn't a good idea, this is agreed by all but SMW.

@kghbln @hexmode I don't know what above comment entails or is trying to highlight but indicating that SMW has not agreed to it without clarifying that with the project or at least invite @kghbln to comment on such issues seems premature.

Does SMW in the above context refers to the extension or the community? In any event, while most SMW extensions are available and installed via Composer those are not auto-enabled, so any statement indicating otherwise is incorrect.

[0] https://mwstake.org/mwstake/wiki/Event:104

**Comment by kghbln** [comment]
I suspect that the autoloading of the Validator and the ParserHooks extension are meant here.

Apart from that there are still semantic extensions which autoload though none of them was yet released officially. Probably a good occasion to actually convert them to extension registration and release them.

**Comment by hexmode** [comment]
@mwjames sorry I missed this earlier.

This was part of a discussion that led to the [Hybrid extension management RFC](https://phabricator.wikimedia.org/T250406) where I would really like to get your input. (In fact, I was coming here to file an issue on it and found this discussion.)

That RFC (and the #mwstake discussion) was the result of (some of) our frustration with the WMF stance which, up till now, has been "Don't use composer for extensions because of [T467](https://phabricator.wikimedia.org/T467)" where composer usage for extensions was previously discussed and dismissed.

As you know, many MW extension authors (including myself) have since embraced composer/packagist for installing extensions.  To get past the [stop energy](http://radio-weblogs.com/0107584/stories/2002/05/05/stopEnergyByDaveWiner.html) of T467, we are working to create a new RFC and hope to have it [discussed](https://www.mediawiki.org/wiki/Wikimedia_Technical_Committee/Minutes/2020-05-20) and eventually accepted by [TechCom](https://www.mediawiki.org/wiki/Wikimedia_Technical_Committee) in the coming weeks. This is where your input would really be valuable.

Hopefully, this will help us foster relationships that lead to a more amicable co-existence between the core MW team and MW extension developers who create extensions that are not used by the WMF.

**Comment by krabina** [comment]
This issue should probably be renamed. 

Daniel Kinzler summariesed the problem here that will hit us in MW 1.38:
[Breaking Change: Extensions Initialization via Composer Autoloading](https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/thread/L44M3KCWN7CJLG3QPHEUJKXZDEZ65ESL/)

Here is a reference to a phabircator task: https://phabricator.wikimedia.org/T295883

@Nikerabbit and others are aware of this, I just want to make sure to have a place at github where this is discussed/monitoried.

**Comment by jaideraf** [comment]
It seems to me that the problem was solved for translatewiki.net in 2021, although they not use SMW anymore (2024). So I am closing the issue by now. If anyone is intested in this discussion feel free to reopen it.
