### ISSUE TITLE
The "Refresh" option in the page menu no longer selectable

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4833]
### Setup and configuration

- MediaWiki | 1.35.0-rc.2 (0f1a2a2)18:43, 21 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.6 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (1c1c4a2) 19:23, 17 August 2020

### Issue
The "Refresh" option in the page menu allowing to clear the cache of a page is no longer selectable for Vector and Monobook probably others, too.

### Steps to reproduce
[Main Page of s-mw.o](https://sandbox.semantic-mediawiki.org/wiki/Main_Page)

**Comment by jaideraf** [comment]
It coud be related to https://phabricator.wikimedia.org/T262092

**Comment by H21lab** [comment]
Affecting also to Timeless skin. Workaround is to use `?action=purge` parameter in URL

**Comment by Seb35** [comment]
Digging in SMW history, the 'Refresh' option was added [https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2502 on 10 Jun 2017] followed by [https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2631/files a second PR on 19 Aug 2017] to disable this option when JS is not enabled.

For an unknown reason, the JS to un-disable the link is no more loaded in MW 1.35 and/or SMW 3.2 (not sure which part is responsible of this).

**Comment by kghbln** [comment]
> For an unknown reason, the JS to un-disable the link is no more loaded in MW 1.35 and/or SMW 3.2 (not sure which part is responsible of this).

Well, it worked for SMW 3.2 on MW 1.34 so it is safe to say that MW 1.35 causes the code in SMW to no longer be loaded

**Comment by Seb35** [comment]
It appears that the resource 'mediawiki.notify' was deleted because always available (loaded in resource 'mediawiki.base'), see https://phabricator.wikimedia.org/T233676.

For MW 1.35, the patch is simply to remove dependency to 'mediawiki.notify' in `smw/util/ext.smw.util.purge.js` and `res/smw/util/ext.smw.util.postproc.js`

Similarly to most patches linked on Phabricator, a conditional loading of 'mediawiki.notify' should used to for older MW versions. (If I’m not mistaken, it was deprecated [on 2020-03-27](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/583754/) and removed [on 2020-05-28](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/593088/), which are all MW 1.35.0-alpha.)
