### ISSUE TITLE
Recent translatewiki updates broke CI

### ISSUE THREAD

**Issue by gesinn-it** [SemanticMediaWiki/SemanticMediaWiki#4979]
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/86dd820e087527032a887e41ed924a51ad58be13

**Comment by Nikerabbit** [comment]
translatewiki is not a person, do not assign issues to it.

In https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/767145407 I see:
```
Fatal error: Declaration of SMW\Tests\Utils\Mock\MockSuperUser::getId() must be compatible with User::getId($wikiId = self::LOCAL): int in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Mock/MockSuperUser.php on line 28
```

Not caused by translation changes.

In https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/767145406 I see many deprecation warnings, one failure due to core parser change. Not caused by translation changes.

In https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/767145405 I see:
```
1) SMW\Tests\MediaWiki\MessageBuilderTest::testPrevNextToText
Failed asserting that '(前の20件 | <a title="次の20件" class="mw-nextlink">次の20件</a>) (<a title="ページあたり20件の結果を表示" class="mw-numlink">20</a> | <a title="ページあたり50件の結果を表示" class="mw-numlink">50</a> | <a title="ページあたり100件の結果を表示" class="mw-numlink">100</a> | <a title="ページあたり250件の結果を表示" class="mw-numlink">250</a> | <a title="ページあたり500件の結果を表示" class="mw-numlink">500</a> 件) を表示' starts with "View (previous 20".
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/MediaWiki/MessageBuilderTest.php:87
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:99
2) SMW\Tests\Integration\JSONScript\JSONScriptTestCaseRunnerTest::testCaseFile with data set "s-0010.json" ('/home/travis/build/SemanticMe...0.json')
Failed "#0 infolinks on value are content lang. formatted"
```

Neither can be caused by the linked patch, as those message keys were not modified. The MessageBuilder tests are broken because they mock the language, but do not implement the getCode(), which then returns `null`. That is interpretet to mean a content language somewhere, and I guess some other test overrides $wgContentLanguage which over here. It's not a pure unit test.

**Comment by gesinn-it** [comment]
@Nikerabbit uh, sorry, no idea what I have read before. I'll close this issue, it's invalid. And thanks for your feedback on the other failing test you mentioned for the coverage run.
