### ISSUE TITLE
Move Content::preSaveTransform method that don't belong in Content to ContentHandler

### ISSUE THREAD

**Issue by roman-stolar** [SemanticMediaWiki/SemanticMediaWiki#5037]
Since starting with version 1.37 we move Content::preSaveTransform to ContentHandler we should also move it in SemanticMediaWiki (SchemaContent -> SchemaContentHandler). But as SemanticMediaWiki used in older version, we should leave the old SchemaContent::preSaveTransform and reuse it for the new one SchemaContentHandler::preSaveTransform.

More details in ticket description: https://phabricator.wikimedia.org/T287156

**Comment by roman-stolar** [comment]
@JeroenDeDauw Hi! I just faced with issue that I can't push by branch to create Pull Request then for current issue.
Looks like a didn't have access rights.
**Error:** 
```Pushing to https://github.com/SemanticMediaWiki/SemanticMediaWiki.git
remote: Permission to SemanticMediaWiki/SemanticMediaWiki.git denied to roman-stolar.
fatal: unable to access 'https://github.com/SemanticMediaWiki/SemanticMediaWiki.git/': The requested URL returned error: 403```

**Comment by JeroenDeDauw** [comment]
Well yeah, that is how GitHub works. You create a fork and push to a branch there, and then create a pull request to this repo.

**Comment by jaideraf** [comment]
Related PR: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5038

**Comment by Nikerabbit** [comment]
The fix is not working (missing return type declaration):

`PHP Fatal error:  Declaration of SMW\MediaWiki\Content\SchemaContentHandler::preSaveTransform(Content $content, MediaWiki\Content\Transform\PreSaveTransformParams $pstParams) must be compatible with JsonContentHandler::preSaveTransform(Content $content, MediaWiki\Content\Transform\PreSaveTransformParams $pstParams): Content
`
