### ISSUE TITLE
ParserCache fails to serialize due to smwdata on MW 1.36

### ISSUE THREAD

**Issue by Ostrzyciel** [SemanticMediaWiki/SemanticMediaWiki#5055]
### Setup

- SMW version: [master](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/e20217049bfe5f7119920fdb6e372b3a2bd24c70)
- MW version: 1.36.1 (I know it's unsupported yet)
- PHP version: 7.4.22
- DB system and version: MariaDB 10.6.3, Apache Jena

### Issue

Found this in the error log when saving a page :
![image](https://user-images.githubusercontent.com/56843159/131168385-d1675f2e-9edb-4109-be13-fe72e3828a34.png)
(I am deeply sorry for the awkward formatting, I am still figuring out Logstash, I hope it's readable.)

The reason for this is that MW in 1.36 by default serializes parser cache as JSON, not PHP, which is something that the additional `smwdata` prop apparently does not support. It can be temporarily mitigated by setting [$wgParserCacheUseJson](https://www.mediawiki.org/wiki/Manual:$wgParserCacheUseJson) to false, but that setting is deprecated. I think making `SMW\SemanticData` JSON-serializable will fix that, though I have no idea how hard that might be.

**Comment by Seb35** [comment]
It might be not that hard although it could be some work: the [algorithm to detect serializable objects](https://github.com/wikimedia/mediawiki/blob/04820b38cd9503ab2f6e2eee2750db89d11e948e/includes/json/JsonCodec.php#L164) wants the object implements [MediaWiki\Json\JsonUnserializable](https://github.com/wikimedia/mediawiki/blob/04820b38cd9503ab2f6e2eee2750db89d11e948e/includes/json/JsonUnserializable.php) (the other serializable objects are stdClass, scalars, or arrays of these things).

**Comment by Seb35** [comment]
Well, the interface [MediaWiki\Json\JsonUnserializable](https://github.com/wikimedia/mediawiki/blob/04820b38cd9503ab2f6e2eee2750db89d11e948e/includes/json/JsonUnserializable.php) does not exist in MW 1.35 and is mandatory in 1.36 to avoid this warning, so it introduces a hard break between 1.35 and 1.36: either `SMW\SemanticData` does not implement this interface (compatibility ≤ 1.35 and we have this warning in ≥ 1.36), either it does implement this interface and it breaks in MW ≤ 1.35 because the interface does not exist.

As stated, perhaps a way is to conditionally define this interface if it does not exist, like
```php
if( interface_exists( 'MediaWiki\Json\JsonUnserializable' ) ) {
	interface MediaWiki\Json\Unserialializable extends \JsonSerializable { … }
}
```

**Comment by JeroenDeDauw** [comment]
Don't forget the negation in the if statement
