### ISSUE TITLE
Use of WSSemanticParsedText and fuzzy searches

### ISSUE THREAD

**Issue by bertrandgorge** [SemanticMediaWiki/SemanticMediaWiki#5349]
Hello, this is a question for those using `WSSemanticParsedText` with `SMWElasticStore`: it seems that the "fuzzy" search capability of Elastic search is not used at all - when I compare the results with typos, the regular search (Special:Search) returns much more results than WikiSearch...

Is there something that I missed in the configuration or setup ?

Thanks for any help....!

By the way, I've setup WikiSearchFront on our wiki, it is just spectacular ! https://wiki.tripleperformance.fr/index.php?title=Search&term=azote

**Comment by bertrandgorge** [comment]
Also: sorry if I've asked this here, I'm not sure there is a better place for those kind of questions... If there is just tell me! Maybe we could have some kind of discourse setup somewhere to help the community with Semantic Mediawiki setups !

**Comment by marijnvanwezel** [comment]
Hi @bertrandgorge, WikiSearch currently does not support fuzzy search, but it seems like a useful and easy-to-implement feature. I will discuss this with my colleagues coming Friday.

Also note that since WikiSearch 6.3.0, WSSemanticParsedText is no longer necessary, since a `Parsed text` property is added for every page.

**Comment by bertrandgorge** [comment]
Excellent, thanks @marijnvanwezel ...! I'll be happy to help if I can!
