### ISSUE TITLE
Result column duplicaton on "further results ..."

### ISSUE THREAD

**Issue by roland2025** [SemanticMediaWiki/SemanticMediaWiki#541]
Problem looks like one from a few years ago.

https://bugzilla.wikimedia.org/show_bug.cgi?id=33473

{{#ask: [[SOME QUERY]]|?Property|mainlabel=some text|limit=0}}

when mainlabel is defined, query page will show duplicate columns.

**Comment by Contrafibularity** [comment]
Is this perhaps in any way related to #481 and #249? It's similar at least in the sense that syntax is added to the original query after "further results" has been clicked.

**Comment by JeroenDeDauw** [comment]
@kghbln so this is a usability issue and not a bug? (then the label should be enhancement)

If it's a UX issue, I'm also gonna guess it's still present in 2.1?

**Comment by kghbln** [comment]
Yeah, this on is still present. This started with SMW 1.6 and is present ever since. At that time four years ago I labelled this as a bug since it appeared to be not very intuitive to suppress the main result column and than adding it again at the same time. However, this may indeed better be called an enhancement now.

**Comment by mwjames** [comment]
Expected to be solved by #1407.

**Comment by kghbln** [comment]
@mwjames Wow, great, this was a personal long time wish. Works perfect as the [field test](http://sandbox.semantic-mediawiki.org/wiki/Issue/541) proves. Things are now much more intuitive! Thanks a ton!

**Comment by kghbln** [comment]
:+1:  This fix is eligible for the kudo of the year award. :)
