### ISSUE TITLE
Sandbox usability issues

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#5499]
### Wiki

- https://sandbox.semantic-mediawiki.net
- viewed in Firefox

### Issues
I recently had occasion to use the Sandbox wiki for SMW again and found that it still had some usability issues that it was having before: 

- Dropdowns of the editor tools: they work but one needs to click twice after the page has loaded.
- Visual Editor: the text in the editor looks like one is suffering from diplopia and selecting text becomes a bit of a challenge. 

Screenshot:
<img width="576" alt="Screenshot 2023-06-24 at 11 01 00" src="https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/10888726/b97bd5f1-02d3-4df0-bb1e-1a2d4b21bbee">

**Comment by kghbln** [comment]
This was because Chameleon and Medik do not play when active on the same instance. Now after getting rid of Chameleon ...

I tested Vector and Medik. Not sure which skin you chose. 

![grafik](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/1104078/b8e37de9-5361-4246-80d7-9f92a667693e)

![grafik](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/1104078/15cc35a1-9a4a-49ac-917c-a688bdd13d10)
