### ISSUE TITLE
[MW 1.41] Parser::$mOutput must not be accessed before initialization

### ISSUE THREAD

**Issue by ellsclytn** [SemanticMediaWiki/SemanticMediaWiki#5579]
### Setup

- SMW version: `dev-master` ([`6b297f3`](https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6b297f3bdc3ae6ae17abe51e8cf1e097da7f6a47))
- MW version: `1.41.0`
- PHP version: `8.1.26 (litespeed)`
- DB system (MySQL, Blazegraph, etc.) and version: `10.6.16-MariaDB`

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

Whenever I attempt to run a query via the `Special:Ask` page I encounter an error:

```
[08ec1c09f46c4fe1c192d41f] /index.php?title=Special:Ask& Error: Typed property Parser::$mOutput must not be accessed before initialization

Backtrace:

from /home/app/site/includes/parser/Parser.php(1052)
#0 /home/app/site/extensions/SemanticMediaWiki/src/Parser/RecursiveTextProcessor.php(130): Parser->getOutput()
#1 /home/app/site/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(375): SMW\Parser\RecursiveTextProcessor->transcludeAnnotation()
#2 /home/app/site/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(342): SMW\Query\ResultPrinters\ResultPrinter->handleNonFileResult()
#3 /home/app/site/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(304): SMW\Query\ResultPrinters\ResultPrinter->buildResult()
#4 /home/app/site/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(500): SMW\Query\ResultPrinters\ResultPrinter->getResult()
#5 /home/app/site/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(314): SMW\MediaWiki\Specials\SpecialAsk->fetchResults()
#6 /home/app/site/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(168): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#7 /home/app/site/includes/specialpage/SpecialPage.php(727): SMW\MediaWiki\Specials\SpecialAsk->execute()
#8 /home/app/site/includes/specialpage/SpecialPageFactory.php(1621): MediaWiki\SpecialPage\SpecialPage->run()
#9 /home/app/site/includes/MediaWiki.php(357): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#10 /home/app/site/includes/MediaWiki.php(960): MediaWiki->performRequest()
#11 /home/app/site/includes/MediaWiki.php(613): MediaWiki->main()
#12 /home/app/site/index.php(50): MediaWiki->run()
#13 /home/app/site/index.php(46): wfIndexMain()
#14 {main}
```

The error only appears for queries where I know there would be results. Queries where I would expect 0 results do not return any error.

Attempting to include equivalent queries in any page via the `ask` syntax fails silently (the page still loads, but the query is completely ignored with no results or error rendered).

### Steps to reproduce the observation:

I was unable to recreate this on the Sandbox wiki. I'm guessing it's to do with the specific PHP version in use.

The steps I took were:

1. Enable debugging output in `LocalSettings.php`

    ```php
    error_reporting( -1 );
	ini_set( 'display_errors', 1 );
	
	$wgShowExceptionDetails = true;
	$wgShowDBErrorBacktrace = true;
    ```
3. Create a page referencing a property. E.g. [[Has color::Red]]
4. Go to the Wiki's `Special:Ask` page and enter the query `[[Has color::Red]]`
5. Submit the query

**Comment by Nikerabbit** [comment]
As you can see from https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md SMW is not yet compatible with MediaWiki 1.41. Thanks for reporting.

**Comment by ellsclytn** [comment]
Oops! Thanks.

**Comment by Nikerabbit** [comment]
We do still want to fix the issue.

**Comment by andrecastro0o** [comment]
Hei, facing same issue.
However queries seem to work fine if written on a page.

* [MediaWiki](https://www.mediawiki.org/)	1.41.0
* [PHP](https://php.net/)	7.4.33 (fpm-fcgi)
* [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.3
* OS: Ubuntu 22.04.4 LTS


And only saw now the [COMPATIBILITY.md](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md) matrix.

I think it would be a good idea to warn users/admins in https://www.semantic-mediawiki.org that SMW is not yet compatible with MediaWiki 1.41. I think that having it clearly stated in [Help:Installation](https://www.semantic-mediawiki.org/wiki/Help:Installation) 

What could be simplest solution to this? Downgrade MW to 1.39.6 ?

**Comment by Nikerabbit** [comment]
MediaWiki doesn't support downgrading (unless you can restore an old version from backups).

This patch is supposed to fix this issue: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/985035

**Comment by ernstki** [comment]
> This patch is supposed to fix this issue: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/985035

I was seeing this with VisualEditor, and a web search led me here. I don't even have SMW installed on this wiki, but for some reason VE was triggering this behavior as well.

If you find yourself in a similar situation, you can apply this patch to MediaWiki 1.41.0 and make the error go away:

```bash
curl -sLOJ https://gerrit.wikimedia.org/r/changes/mediawiki%2Fcore~985035/revisions/9/patch?zip
unzip f03bdcb.zip
patch -p1 <f03bdcb.diff
```

I'm not that familiar with Gerrit patchsets, but I suspect the `revision/9` part as well as the name of the `.zip` and `.diff` will change as time goes on. You can get a link to the _current_ patchset by visiting the link at the top and clicking the "DOWNLOAD" link or pressing <kbd>d</kbd>.

If I later figure out that this bug was already reported (and/or patched) for MediaWiki core, I'll update this comment, but for now, this issue had the best search engine juice for that error message.

_Possibly related: https://phabricator.wikimedia.org/T360090 (pertaining to Page Forms)_

**Comment by planetrobbie** [comment]
Thanks so much [ernstki](https://github.com/ernstki), spent hours to try to figure that out. You saved my day with this patch which works really great for

MW: 1.41.1
SMW: 4.1

I didn't realized soon enough that SMW wasn't supported on the latest MW release ! so thanks 1000's time. Because downgrading to 1.39 from 1.41.1 isn't an option it seems, tried and miserably failed.

**Comment by cscott** [comment]
@ernstki Please file a bug against VisualEditor in https://phabricator.wikimedia.org/ so that the bug you're seeing can be fixed in Visual Editor.  I can't fix it if I can't reproduce it, and I can't reproduce it if the only thing I know about it is "well I saw a problem and applied a fix for a totally different extension that I didn't even have installed and it went away".

For SMW, I investigated a little bit, and the issue seems to be that `src/Parser/RecursiveTextProcessor` is trying to look at the ParserOutput before `$this->parser` has done any parse.  It looks like the latest SMW already has a "workaround" for this:
```
	private function getParserOutputSafe(): ?ParserOutput {
		try {
			return $this->parser->getOutput();
		} catch ( Error $e ) {
			return null;
		}
	}
```
which will work, but it's not ideal.  The issue is that the ParserOutput will be overwritten/replaced every time you do a parse with `$this->parser` and that doesn't seem to be handled well by RecursiveTextProcessor.

**Comment by ernstki** [comment]
@cscott I get that. Sorry to create anxiety. For my part, I consider the issue resolved, and my local setup is far behind the recommended/current versions of just about anything out there.

Just documenting my workaround for this brief moment in time, in case it helped others. In a few months' time this won't matter anymore, as SMW's support for newer MediaWiki releases is improving seemingly by the day.
