### ISSUE TITLE
SemantikMediawiki 4.1.2 error during installation  

### ISSUE THREAD

**Issue by zampaleu** [SemanticMediaWiki/SemanticMediaWiki#5583]
Tring to installin Semantic mediaiwiki but i got errors 

MY ENV

[MediaWiki](https://www.mediawiki.org/)	[1.41.0](https://www.mediawiki.org/wiki/MediaWiki_1.41) [(343416f)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/343416f526fb56f5c6d2b9e6c4f0785a4337b4ef)
[PHP](https://php.net/)	7.4.33 (apache2handler)
[PostgreSQL](http://www.postgresql.org/)	15.5 (Ubuntu 15.5-0ubuntu0.23.10.1)

ERROR 
running php ./maintenance/update.php

  ... done.
Checking smw_hash field consistency ...
PHP Notice:  Array to string conversion in 
..extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php on line 269
PHP Notice:  Array to string conversion in 
..extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php on line 270
UnexpectedValueException from line 266 of 
..extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php: Expected a ResultWrapper for 
smw_object_ids
Array
Array
#0 /var/www/solab/extensions/SemanticMediaWiki/maintenance/populateHashField.php(216): SMW\MediaWiki\Connection\Database->select()

**Comment by Nikerabbit** [comment]
4.1.2 is not compatible with MW 1.41: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by Seb35** [comment]
The error above is because in `$results instanceof ResultWrapper`, `$results` is an object of class `Wikimedia\Rdbms\MysqliResultWrapper`, which is a subclass of `Wikimedia\Rdbms\ResultWrapper` but `ResultWrapper` is no more an alias of `Wikimedia\Rdbms\ResultWrapper`, breaking the equivalence and consequently the condition.

This is due to [this commit](https://github.com/wikimedia/mediawiki/commit/447400b4233a705476e579ee2a939bfaa74c0d00) removing old class aliases, and SMW uses (some of) these aliases.

**Comment by Nikerabbit** [comment]
Fix included in 4.1.3.
