### ISSUE TITLE
Datatables version  security issue 

### ISSUE THREAD

**Issue by willyedoo** [SemanticMediaWiki/SemanticMediaWiki#5628]
### Setup

- SMW version:4.1.3
- MW version:1.39.4
- PHP version:8
- DB system (MySQL, Blazegraph, etc.) and version:Postgresql
- Datatables:1.10.13 to 1.10.21

### Issue
Hello @JeroenDeDauw , 
Am geting a security issue with Datatables version on upgrade from SMW 4.1.2 According to the security team, Semantic should be bundled with datatable 1.10.23, or 2.0.3, published on  22 Mar, 2024  see [discussion on version safe](https://datatables.net/forums/discussion/75727/cve-2020-28458)
<img width="336" alt="image007" src="https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/3040582/b260a541-a110-4328-a1c4-728e8a45edba">

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:
When installation is launched, the SMW is sent to quarantaine by security system
https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/res/onoi/jquery.dataTables
```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Upgrade with composer 
Regards!

**Comment by krabina** [comment]
see also [#766](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/766) and https://github.com/onoi/shared-resources/tree/master/res/jquery.dataTables

**Comment by kghbln** [comment]
Since it is SMW core it is about the "datatable" class to the [table format.](https://www.semantic-mediawiki.org/wiki/Help:Table_format)

"onoi/shared-resources" was already merged into SMW last year. The dataTables stuff is sitting in this [spot.](
https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/b1e29dd5880c2d93bb32b2840ed505b2b29aca2e/res/onoi/jquery.dataTables)

**Comment by krabina** [comment]
I guess we have three options

1. kick out the "datatable" class for the table format, since now we have a feature-rich and maintained datatables format in SRF (not my preffered option either, since it will break things, but better to throw unmaintained code if nobody fixes it)
2. make the "datatable" class of the table format in SMW dependent on SRF. This way we could avoid having two places where to maintain external resources that are being used. But AFAIK it is not only the datatables sources, but there is some custom code as well to make the datatables class work with table format, so I don't know if it can so easily point to the source we use in SRF
3. update the existing solution in SMW

**Comment by gesinn-it-gea** [comment]
@krabina if SRF datatables could be a drop in replacement for the datatables class, I suggest to maintain only one and drop the other.

**Comment by LiquidFenrir** [comment]
Hello there, hitting the same problem, that's quite blocking for us with security checks trying to upgrade wikis 😄
any update/inside decision on this? I'd love to contribute the fix if no one is available for it, but no conclusion seems to have been reached in terms of which option to take.
Hopefully this can be resolved before 4.2.1

**Comment by thomas-topway-it** [comment]
I was also checking the issue, I could try to upgrade the library

**Comment by thomas-topway-it** [comment]
@willyedoo  I have proposed a patch here https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5720. Regarding sponsorship as far as I know contributions are welcome here: https://opencollective.com/smw   (the maintenance of the code-base cannot solely rely on free labor by volunteers, since there are bugs or enhancements that require a significant effort)

**Comment by jaideraf** [comment]
Datatables updated in master/main. This issue can be closed.
