### ISSUE TITLE
tests (unit): Call to undefined method BacklinkCache::clear()

### ISSUE THREAD

**Issue by gesinn-it-ilm** [SemanticMediaWiki/SemanticMediaWiki#5695]
Running the unit tests for MW 1.40+ fails with:

Error: Call to undefined method BacklinkCache::clear()

See commit from @Krinkle: [BacklinkCache: Remove unused internal clear() method](https://github.com/wikimedia/mediawiki/commit/2249870a0f3725c70a8cba3b9eb0f16350b68245#diff-9f2668e3e3ce05624e6d6165f532aca730c6c70fb9c81f973e6f661259b88d72)

@JeroenDeDauw according to @Krinkle, we should remove test call, because it is not a static cache, and services already reset between tests.

**Comment by gesinn-it-gea** [comment]
From original commit message:

_"Remove test call, which hasn't been needed in a little while because it's not a static cache, and services are already reset between tests."_

@Krinkle should we simply remove calls to clear() as done here: https://github.com/wikimedia/mediawiki/commit/2249870a0f3725c70a8cba3b9eb0f16350b68245#diff-9f2668e3e3ce05624e6d6165f532aca730c6c70fb9c81f973e6f661259b88d72L38

**Comment by gesinn-it-gea** [comment]
Example of a failing test: https://github.com/SemanticMediaWiki/SemanticMediaWiki/actions/runs/10160443838/job/28096833805#step:4:1861

**Comment by gesinn-it-ilm** [comment]
Inside class _DatabaseTestCase_ **BacklinkCache** is defined. That class is used to extend mostly all of the tests. If we remove call of **BacklinkCache** there, all tests for MW 1.40 will pass and work fine.

Lines to remove are:
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3b803875a2399f064288cda5fa08b50405379758/tests/phpunit/DatabaseTestCase.php#L109C3-L118C4

**Comment by gesinn-it-ilm** [comment]
Unit tests for MW **1.40** fixed and running fine. 
Excluding BacklinkCache method call for MW 1.40+ fixed the issue. 
Tests for MW 1.41+ still have some errors, and another issue will be opened for that topic.
