### ISSUE TITLE
Page titles with a hash character followed by tags produce invalid RDF during export

### ISSUE THREAD

**Issue by gladwig** [SemanticMediaWiki/SemanticMediaWiki#708]
This is a bit weird. 

To reproduce, create a page with the following content:

```
[[testproperty1::test #ask <code>]]

[[testproperty2::test ask <code>]]
```
Note that both properties should have the default datatype "Page". The only difference between the values of testproperty1 and testproperty2 is the hash character.

This is the RDF that is produced via dumpRDF.php:
```
	<swivt:Subject rdf:about="http://172.28.128.8/index.php/Spezial:URI-Aufl%C3%B6ser/EncodingTest">
		<rdfs:label>EncodingTest</rdfs:label>
		<swivt:page rdf:resource="http://172.28.128.8/index.php/EncodingTest"/>
		<rdfs:isDefinedBy rdf:resource="http://172.28.128.8/index.php/Spezial:RDF_exportieren/EncodingTest"/>
		<swivt:wikiNamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</swivt:wikiNamespace>
		<property:Testproperty1 rdf:resource="&wiki;Test-23ask_<code>"/>
		<property:Hat_unpassenden_Wert_f-C3-BCr-23aux rdf:resource="http://172.28.128.8/index.php/Spezial:URI-Aufl%C3%B6ser/Attribut-3ATestproperty2"/>
		<swivt:wikiPageModificationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2015-01-12T15:41:06Z</swivt:wikiPageModificationDate>
		<property:Zuletzt_ge-C3-A4ndert-23aux rdf:datatype="http://www.w3.org/2001/XMLSchema#double">2457035.1535417</property:Zuletzt_ge-C3-A4ndert-23aux>
		<swivt:wikiPageSortKey rdf:datatype="http://www.w3.org/2001/XMLSchema#string">EncodingTest</swivt:wikiPageSortKey>
	</swivt:Subject>
```

The value for testproperty1 is invalid:
```
<property:Testproperty1 rdf:resource="&wiki;Test-23ask_<code>"/>
```
Any XML parser will reject this because of the unencoded < > characters.

However, testproperty2 seems to work correctly, i.e. the invalid value is not included in the RDF. It seems the hash character causes the export code to not encode the remaining characters in the value.

Cheers,
Günter

**Comment by mwjames** [comment]
> `[[testproperty1::test #ask <code>]]`
> `<property:Testproperty1 rdf:resource="&wiki;Test-23ask_<code>"/>`

This is odd, for the given example (using the current master, MW 1.23, and `enableSemantics( 'http://example.org/id/', true );`) I can't confirm your observation because as you can see:

![708-wiki](https://cloud.githubusercontent.com/assets/1245473/5715709/68b86158-9b21-11e4-8499-fe751c9034fb.png)

![708-browse](https://cloud.githubusercontent.com/assets/1245473/5715751/25b7dfe0-9b22-11e4-9e2a-256b60bdfcf7.png)

![708-rdf](https://cloud.githubusercontent.com/assets/1245473/5715717/8d1d70ba-9b21-11e4-9a82-e0c6bc7640c8.png)

![708-rdf-2](https://cloud.githubusercontent.com/assets/1245473/5715851/0ab0410e-9b24-11e4-8328-6f8997b645d6.png)

Another issue (yet unrelated to the RDF export issue) is the usage of the `<code>` tag that can't be correctly interpret by the parser as part of the in-text annotation.

**Comment by mwjames** [comment]
Any update on this issue?

**Comment by gladwig** [comment]
Sorry for the delay, I was only now able to check the version of MW/SMW where this happened. It was an older installation and I can confirm that it is fixed now. Issue can be closed.
