### ISSUE TITLE
Lack of leading zero leads to incorrect storage of number values

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#753]
Properties of type number set with a value between zero and one without a leading zero do not get recorded properly. For example, if a property called "My number" is set on a page called "My page" as follows:

```
[[My number::0.5]]
```

Then querying for the value of "My number" (e.g. {{#show: My page |? My number }}) will result in the correct value of 0.5. However, if it is set without a leading zero, like:

```
[[My number::.5]]
```

Then the result of the same query will be 5. Setting of the property seems to be ignoring the decimal point.

Environtment details:
* SMW 2.0
* MW 1.23.2
* PHP 5.4.16
* MySQL 5.6.20
* Windows Server 2008 R2 with IIS 7.5

**Comment by mwjames** [comment]
Yes, this bug is as old as the `SMWNumberValue`  class. The code that is responsible for improper parsing the `.5` value:

```
		$parts = preg_split( '/([-+]?\s*\d+(?:\\' . $kiloseparator . '\d\d\d)*' .
		                      '(?:\\' . $decseparator . '\d+)?\s*(?:[eE][-+]?\d+)?)/u',
		                      trim( str_replace( array( '&nbsp;', '&#160;', '&thinsp;', ' ' ), '', $value ) ),
		                      2, PREG_SPLIT_DELIM_CAPTURE );

		if ( count( $parts ) >= 2 ) {
			$numstring = str_replace( $kiloseparator, '', preg_replace( '/\s*/u', '', $parts[1] ) );
			...
		}
```

`$parts[1]` contains a `5`  which when applied to `$numstring = str_replace( $kiloseparator, '', preg_replace( '/\s*/u', '', $parts[1] ) );` will just return a `5` and has forgotten all about being a `.5`. (just to note, this class has no tests therefore it should come to no surprise that above issue is only uncovered now) 

If someone wants to try to crack this issue, please go ahead otherwise it will be a while before I will attend this. Well, a quick fix (haven't tested it extensively) is to:

```
// Look ahead before accessing [1]
$numberPart = $parts[0] === $decseparator ? $parts[0] . $parts[1] : $parts[1];
$numstring = str_replace( $kiloseparator, '', preg_replace( '/\s*/u', '', $numberPart ) ); // simplify
```

**Comment by JeroenDeDauw** [comment]
> Yes, this bug is as old as the SMWNumberValue class.

Wait... so this ticket is about killing a 9-year-old? o_O

**Comment by thiemowmde** [comment]
Code like this, especially if regular expressions are involved, not only needs tests. For gods sake, tests are an absolute must here. Collect as many different use cases as you can before even thinking of touching a regex.

First problem I see is that `$decseparator` and `$kiloseparator` should use `preg_quote` instead of assuming that the added `\\` is enough.

Next problem is that the stripping of HTML entities misses a `strtolowercase`.

Next problem is that there are two calls to strip spaces, one before the split and one after. Why is that? Doesn't make much sense to me.

Next one is an optimization issue. The outer brackets in the regex (they become `$parts[1]`) are pointless. Just check if `$parts` is not empty and use `$parts[0]`.

Next question is why this is using `preg_split` in the first place? What this code does is clearly a `preg_match`.

Next question is why this ignores everything before and after the number it found? This is why ".5" is recognized as "5". Is this an intended feature? Why should somebody be able to enter stuff like "foo5bar6" and expect it to be parsed as "5"?

Now the regex itself:
* It matches an optional sign (plus or minus),
* followed by optional spaces,
* followed by at least one digit (which already answers the question raised here),
* followed by any number of a grouping character plus three digits (note that the assumption that there are always three digits per group is not true in certain languages),
* followed an optional decimal separator plus at least one digit,
* followed by optional spaces,
* followed by an optional `E` supplement with or without a sign.

There is more this does not match, e.g. `5.e10`. And as already said, the worst thing is that these matches don't fail but are parsed as wrong numbers.

Start with adding tests, positive and negative ones, as many as you can find. You will find a good regex afterwards.

**Comment by JeroenDeDauw** [comment]
![fgfds](https://cloud.githubusercontent.com/assets/146040/5989388/c31d1602-a986-11e4-8b51-fe7ea6c87b0c.jpg)

**Comment by thiemowmde** [comment]
If you want to fix the bug quick without much refactoring, you can use this:
```php
'/([-+]?\s*(?:'
// Either numbers like 10,000.99 that start with a digit
. '\d+(?:\\' . $kiloseparator . '\d\d\d)*(?:\\' . $decseparator . '\d+)?'
// or numbers like .001 that start with the decimal separator
. '|\\' . $decseparator . '\d+'
. ')\s*(?:[eE][-+]?\d+)?)/u'
```

**Comment by mwjames** [comment]
@thiemowmde Thanks for regex it took a while to get this fixed but "slow and steady wins the race".
@jamesmontalvo3 Fixed with 2.4.

**Comment by jamesmontalvo3** [comment]
Great! Thanks!

**Comment by kghbln** [comment]
:+1:
