### ISSUE TITLE
#set to be usable with a template parameter

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#756]
If a user wants to make a `QuickQuery` for an annotated value normally s(he) has to go for some length and employ another extension (SF) to be used in combination for creating something like`
{{#ifeq:{{{Keyword|keyword}}}||{{!}} {{#arraymap:{{{keyword|{{{Keyword|}}} }}}|;|x|[[Has keyword::{{ucfirst:x}}| ]]{{#ask: [[Has keyword::{{ucfirst:x}}]]|?has description|limit=0|searchlabel={{ucfirst:x}} }}|&#32;·&#32; }} }}
` which is somewhat impractical and performance extensive (using arraymap).

Extending `#set` with `|template=` allows to:
- `{{#set: Has keyword=one;two;three|+sep=;|template=SetQuickQueryTemplate}}` with a template parameter `|template=SetQuickQueryTemplate` that can include
- `<includeonly>{{#ask: [[{{{property}}}::{{{value}}}]]|limit=0|searchlabel={{{value}}} }}&#32;</includeonly>` where `{{{property}}}` and `{{{value}}}` are fixed named arguments.

This eliminates the need for SF `arraymap` as dependency, `|+sep=;` is already part of `#set` to divide an annotation string, and `|template=` allows for customized links or queries.

**Comment by mwjames** [comment]
Changes to `SetParserFunction` are rather simple: 

```
		$parametersToArray = $parameters->toArray();

		if ( $this->parser !== null && isset( $parametersToArray[ 'template'] ) ) {
			$template = $parametersToArray[ 'template'][0];
			unset( $parametersToArray[ 'template'] );
		}

		foreach ( $parametersToArray as $property => $values ){

			foreach ( $values as $value ) {

				if ( $template !== '' ) {
					$html .= $this->createTemplateOutput( $template, $property, $value );
				}
```
```
		if ( $html !== '' ) {
			$html = $this->parser->recursiveTagParse( $html );
		}

		$html .= $this->messageFormatter
			->addFromArray( $this->parserData->getErrors() )
			->addFromArray( $parameters->getErrors() )
			->getHtml();

		return array( $html, 'isHTML' => true );
	}

	private function createTemplateOutput( $template, $property, $value ) {
		return '{{' . $template . '|property=' . $property . '|value=' . $value . '}}';
	}
```

**Comment by mwjames** [comment]
https://semantic-mediawiki.org/wiki/Examples/Parser/Set_using_a_template_parameter

**Comment by Contrafibularity** [comment]
Thanks for this. If I understand this correctly (though I'm not really sure I do), it would then allow you to apply formatting or further processing to each individual value rather than to the entire array at once. To give a less convoluted example:

  {{#set:
  |property=value 1; value 2; value 3|sep=;|template=Italicise
   }}
where Template:Italicise italicises each individual case, e.g. with <noinclude>''{{{value}}}''</noinclude>,
would be the equivalent of
  [[property::''value 1'']], [[property::''value 2'']], etc. 

If so, could you please do the same for subobjects? It would be most welcome especially given the fact that the approach currently available might be a little intensive on resources and again, relies on a third-party dependency, e.g.:

   {{#subobject:
   |property={{#arraymap:value 1; value 2; value 3|;|@@@|{{Italicise|@@@}}|; }}|+sep=;
   }}

**Comment by Contrafibularity** [comment]
Ah, having looked at the SMW.org page, I realise I did misunderstand the purpose of this parameter. Something for a separate enhancement request maybe, but otherwise please ignore the message above.
