### ISSUE TITLE
$page->doQuickEditContent doesn't update semantic properties

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticMediaWiki#760]
This may be a minor problem, but since I've noticed it:

If I use the MediaWiki $page object with the method $doQuickEditContent, SMW doesn't update the semantic properties. I do have to make a full content edit instead:

So this doesn't work with SMW, but works fine with MW:
```php
$page->doQuickEditContent($content,
      $context->getUser(),
      "Automatic string substitution",
      true // minor modification
    );
```

This does work for both:
```php
$page->doEditContent($content,
      $context->getUser(),
      "Automatic string substitution",
      true // minor modification
    );
```

**Comment by mwjames** [comment]
This can well be, SMW requires that certain hooks are executed and if for some reason there are not, not much SMW can do about it.

>If I use the MediaWiki $page object with the method $doQuickEditContent, SMW doesn't update the semantic properties. I do have to make a full content edit instead:

I never used `$doQuickEditContent` but looking at the docu it says "Edit an article without doing all that other stuff The article must already exist; link tables etc are not updated, caches are not flushed." [0] because annotations are recognized by [1] and ultimately saved through execution of [1].

[0] https://github.com/wikimedia/mediawiki/blob/5ad132533be45f999cec3ea52d959f3504fda83c/includes/page/WikiPage.php#L2264

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/InternalParseBeforeLinks.php

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/LinksUpdateConstructed.php

**Comment by Fannon** [comment]
Ah, thanks to the info! 
I guess I was using the wrong method then anyway ;)
