### ISSUE TITLE
PHP Fatal error:  Base lambda function for closure not found

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#765]
All of the sites I recently upgraded to SMW 2.1 just crashed simultaneously with the following fatal showing up in the servers error log:

`PHP Fatal error:  Base lambda function for closure not found in /.../extensions/SemanticMediaWiki/SemanticMediaWiki.php on line 136`

To what I have just googled in the web this may be related to me using APC cache, so restarting the web server helped out of the situation. I am not sure if this can be addressed from the SMW side or if it is just APC messing up which itself will be a story of history past with PHP 5.5+ if I am not mistaken.

My environment: PHP 5.4.36, APC 3.1.13, MW 1.23.8, SMW 2.1.0

**Comment by mwjames** [comment]
>  SMW side or if it is just APC messing up which itself will be a story of history past with PHP 5.5+ if I am not mistaken.

.php.net [Bug #52144	Error: Base lambda function for closure not found](https://bugs.php.net/bug.php?id=52144)

Yea, that's an PHP/APC issue (see above). If I remember correctly the Composer developers run into similar issues with APC [0] which can't be solved from the SMW side and I'm not sure how to address this because `function() {)` is something naturally supported by PHP.

```php
$GLOBALS['wgExtensionFunctions'][] = function() {

	$applicationFactory = ApplicationFactory::getInstance();

	$namespace = new NamespaceManager( $GLOBALS, __DIR__ );
	$namespace->run();

	$setup = new Setup( $applicationFactory, $GLOBALS, __DIR__ );
	$setup->run();
};
```

[0] http://robertlemke.com/en/blog/composer-and-apc.html

**Comment by kghbln** [comment]
Yeah, APC is the transgressor. :( What may at least come out of this is that we probably should warn about SWM and APC not playing well. I guess I will be switching to Memcached though I am not sure if this a smart thing to do in connection with SMW.

**Comment by mwjames** [comment]
> What may at least come out of this is that we probably should warn about SWM and APC not playing well.

It is not really an issue of SMW because it is something between PHP and APC. 

>  Memcached though I am not sure if this a smart thing to do in connection with SMW.

Shouldn't be any trouble as far as I know because the cache layer used is referencing to a MW `BagOStuff` object. For SMW the type of cache itself ( APC, Memcached , Redis etc.) is irrelevant as it doesn't directly interact with it.

**Comment by kghbln** [comment]
> It is not really an issue of SMW because it is something between PHP and APC. 

Fair enough. Probably this bug is enough as information in case somebody else runs into this issue.

In [0] Composer was the cause which in my case was not touched at the time so the solution there does not help to avoid my "issue".

> Shouldn't be any trouble as far as I know because the cache layer used is referencing to a MW BagOStuff object.

Thanks for the info. Perhaps I will give Redis a try.

**Comment by mwjames** [comment]
Maybe you could report back if you found a more appropriate solution.

**Comment by kghbln** [comment]
Sure since not using any cache does not appeal to me. :)

**Comment by mwjames** [comment]
For reference (all with the same issue):

- https://github.com/symfony/symfony/issues/1541
- http://tiki.org/forumthread47452
- http://help.slimframework.com/discussions/problems/5796-lambda-function-apc-not-playing-nice

**Comment by jongfeli** [comment]
**kghbln** I offered **mwjames** to write something down about PHP caching and how to use it in combination with SMW but I am not quite finished yet. I am trying to built a case to switch from Windows to a Linux (Ubuntu) server for our company wiki so we can switch to HHVM. One of the reasons I am not finished yet is that I ran into some problems with the SytaxHighlight extension. It seems to have some issues for witch I filed a bug (https://phabricator.wikimedia.org/T87544). But what i have until now is in my sandbox (https://semantic-mediawiki.org/wiki/User:Jongfeli/sandbox). It will give you a good idea on what to expect. 

We have been using XCache and now Zend OPCache whitout any problems in combination with SMW on our company wiki. HHVM is the "faster" option on Ubuntu when SyntaxHighlight is working correctly. It runs on my own wiki with SMW but I am not doing anything special on that one. If you are using Ubuntu as your OS it is relatively easy to switch between them. My offer to setup a SMW sandbox still stands :)

**Comment by kghbln** [comment]
Oh, that's indeed a cool page in the making. Great! However I will probably still go for Redis since I can use this for CirrusSearch as well as for job queues. This SyntaxHighlight issue is pretty nasty.

**Comment by mwjames** [comment]
> have until now is in my sandbox (https://semantic-mediawiki.org/wiki/User:Jongfeli/sandbox). It will give you a good idea on what to expect.

I'd like to comment on some of the figures published:
- `Special:Version` does not execute any SMW specific code (SMW bails out on all pages that are not registered to be processed including all Specials* except `Special:Ask` or some from SF), the difference in measurements may be explained by the amount of loaded registration information for enabled/disabled extensions
- ~ `0.15` sec as an average lag is fairly acceptable but the method of measuring is rather arbitrary and in order to have other users to compare something like "Edit page" I propose you import this [smw-content-annotation.xml](https://gist.github.com/mwjames/8ac162bfd5b064715989) (using `Special:Import`) and compare those pages (or pick one) with enabled disabled extensions which makes the test results a bit more stable in terms of the measured execution time
- Cache vs. no cache, the influence is equally for an enabled/disabled SMW extension or other extensions (I guess the median would be not much different in both cases)
- HHVM will certainly show significant improvements on tasks such as `rebuildData`, `import`, or `jobqueue`
- Details on how to run SMW specific benchmarks can be found at [Benchmark tests](https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Benchmark), [how to video](https://vimeo.com/108833255), [travis-hhvm](https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/48757641)
- #513 contains a comparison between PHP 5.6 and HHVM (3.3) using SMW

**Comment by jongfeli** [comment]
Ok, thanks for your comments, learned something new again. I will use the xml to compare the different caching solutions in combination with SMW. The idea was to have a more hands on approach on performance and yes 0.10 of a second does not make much difference when you are viewing and editing via your browser. We "refresh" our wiki every morning with something like **php SMW_refreshData.php -s 1 -e 999** in 2 scheduled jobs "treads" one does the odd id's and the other the even id's in batches of 1000. This to update external data not maintained on the wiki but used to show or used as a **[[Allows value::...]]**. With about 10000 pages 0.10 of a second can make a lot of difference.

**Comment by jongfeli** [comment]
@mwjames, do you have any problems when I use the link (https://gist.github.com/mwjames/8ac162bfd5b064715989) you provided for reference in documentation on the SMW wiki? I noticed that it was flagged as being "SECRET". I am using the xml to test performance on different php caching solutions. It is not done yet but the plot thickens (https://semantic-mediawiki.org/wiki/User:Jongfeli/sandbox).

**Comment by mwjames** [comment]
> do you have any problems when I use the link (https://gist.github.com/mwjames/8ac162bfd5b064715989) you provided for reference in documentation on the SMW wiki?

No, sort of habit to mark them as secret but once you know the link you can use the content freely. 

> https://semantic-mediawiki.org/wiki/User:Jongfeli/sandbox).

This yet the best I have seen in detailing performance comparison between difference modes of installation. :+1: 

One thing I would be cautiousness about is a sentence like "... makes your wiki ~30% slower" without a context which can easily misconstrued because having ~30% of 0.5 sec is different to ~30% 5 sec therefore indicating the baseline will help to set the conditions it is compared to.

**Comment by jongfeli** [comment]
Yes you are right, I was struggling with the text. Your wiki will get slower when you make it sematic but that's the whole point. I deleted the line and provided the time added compared to "default"  MediaWiki. The A8 in VB was also not making sense. It turned out it was set to use 4 cores but was initially tested with only one because it was faster that way, no idea why that is. I ran those tests again on one core and now they make sense. 

I also did some initial testing yesterday on <b>rebuidData.php</b> and i noticed that it does not matter if there is any caching enabled or not. It seems heavily bound to your storage performance but even on the K8 with the SSD there is no difference. It seems that there is no caching at all when you run scripts from the command line like a scheduled job would do. This is all completely of topic, is it wise to open another "thread" to discus this?

**Comment by kghbln** [comment]
Just as a follow-up on the originating problem. I does not help at all switching wikis to use a different cache like e.g. memcached. As long as APC is installed on the server the problem of the PHP fatals continues to exist. I guess that just loading MediaWiki already triggers the issue. So killing APC entirely is the way to resolve the issue.
