### ISSUE TITLE
Allow for multiple sources of data

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#838]
Contact people: @ganqqwerty && @JeroenDeDauw

Allow multiple sources of primary data in the SMW store rather then just wiki pages. This would allow extensions to add information to the store so it can be used as any in wiki defined information, while not having the problem that the data would be removed once the page to which it is attached is re-parsed or the store rebuild script is ran.

See also: [User:Yury Katkov/s13n stands for semantification](https://semantic-mediawiki.org/wiki/User:Yury_Katkov/s13n_stands_for_semantification)

Status (2013): Many interested parties. No development work in SMW started yet. Jeroen De Dauw and Markus are looking into how to implement the same support in the Wikibase store which is currently being designed and written.

**Comment by JeroenDeDauw** [comment]
Status: no work in this direction has been done, even though the topic has come up again on some SMWCons. No such support was added to the Wikibase query store either (and I can actually not remember discussing this with @mkroetzsch).

@mwjames are you aware of this? I suspect it's of interest to you.

**Comment by mwjames** [comment]
> are you aware of this? I suspect it's of interest to you.

Maybe having a specific use case would help to define on what is expected by " ... allow extensions to add information to the store so it can be used as any in wiki defined information".

**Comment by JeroenDeDauw** [comment]
Imagine that you have a rating extension, which rates products (described by wiki pages). If you want the rating to be stored in SMW, so they can be queried against, you need to first create a primary storage for your extension disjoint from SMW, and then on each page parse, get the data from this primary storage and put it into the semantic data, so SMW does not lose it. That's more code, bad for performance, and also forces you to have your own storage to begin with.

**Comment by mwjames** [comment]
Oppose to some other data storage extensions, we want to follow the subject-predicate-object storage paradigm which means the interface that allows to interact with an __auxiliary store__  needs to make that connection (instead of just pushing some CSV data as DB columns into storage engine).

**Comment by JeroenDeDauw** [comment]
I'm not sure you understood. The change this is about is for the SMW store to know which data is coming from a wiki page page which does not. This way, when the refresh of a subject happens, the data that does not come from its associated wiki page does not get deleted (since it's not on the page itself).

**Comment by mwjames** [comment]
> I'm not sure you understood. The change this is about is for the SMW store to know which data is coming from a wiki page page which does not. This way, when the refresh of a subject happens, the data that does not come from its associated wiki page does not get deleted (since it's not on the page itself).

It seems I haven't understood what is being proposed here. Data not coming from a wikipage but still being recognized as data related to a subject?

**Comment by JeroenDeDauw** [comment]
Yeah. Back to the rating example: each user can rate a product page / subject once, giving it 1-5 out of 5 stars. The rating extension then keeps track of things such as the total number of ratings and the average rating of a subject. Now rather than writing their own special page where you browse by highest or by most ratings, the extension author sensibly realizes it makes more sense to stuff the data into SMW, and end up with a much more powerful tool for less work.

How do you do this currently? You can put #set calls into the wikitext to store the info. Though this sucks, since it clutters thereinsert it for ever wikitext and users can edit the data, which in this case they really should not.

You can write the stuff directly to the store, though then you need to intercept the page parse data update step and stuff in your data each time, so SMW does not end up losing it. (It loses it since you'd be using the SMW store as primary storage, while right now it is exclusively secondary storage for info that is in wiki pages, or generated on parse of them).

**Comment by mwjames** [comment]
> sucks, since it clutters thereinsert it for ever wikitext and users can edit the data, which in this case they really should not.

A workaround would be to use a pseudo page (`Special:DataContainer`) that no user can edit and attach subobjects (which are virtual subjects with all the traits of a normal page).

You could have a `Special:DataContainerImporter` which would allow to upload data in a CSV/JSON format and automatically transform its content into an individual `SemanticData` container represented by `Special:DataContainer#FileName#<ContentHash>` with a column describing the property and a row an individual subobject.

Storing it as `Special:DataContainer#FileName#<sha1-ContentHash>` allows to address each single row/column via the normal `#ask` ?property notation.

An extension looking for access to such a storage would just need to use `Special:DataContainer#MyExtenions#<ContentHash>` as identifier (`Special:DataContainer` could be omitted from the interface and added internally so that access is granted via `MyExtenions#<sha1-ContentHash>` id ).

```php
// Fixed subject
$subject = new DIWikiPage( 'DataContainer', NS_SPECIAL );

// Individual data
$dataSubobject = new DataSubobject( $subject );
$dataSubobject->setEmptyContainerForId( 'MyExtension' . sha1( 'IdentifyMyContent' ) );
$dataSubobject->add( ... );

...

// Create the container
$semanticData = new SemanticData( $subject );
$semanticData->addSubobject( $dataSubobject );

// Store the data
$store->updateData( $semanticData );
```

**Comment by mwjames** [comment]
To aid the discussion (and using the outlined approach from https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/838#issuecomment-75485500), a quick hack can be seen in #857.

**Comment by JeroenDeDauw** [comment]
I'm still not sure if you get it. This is not about importing of data at all.

**Comment by mwjames** [comment]
> I'm still not sure if you get it. This is not about importing of data at all.

I was under the impression that we would provide an interface with which an extension can write to the Store without the need for a page-related subject (as in above example) but since it seems not the case, I'd say do whatever you want with this task.

**Comment by mwjames** [comment]
This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.
