### ISSUE TITLE
Semantic Project Management

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#850]
The [Semantic Project Management](http://www.mediawiki.org/wiki/Extension:Semantic_Project_Management) extension needs to be fixed to work with the latest version of Semantic MediaWiki.

- A patch was provided with [bug 35882](https://bugzilla.wikimedia.org/show_bug.cgi?id=35882) that has to be reviewed and committed. --[kgh](https://semantic-mediawiki.org/wiki/User:Kghbln) 16:30, 26 April 2012 (CEST)

**Comment by JeroenDeDauw** [comment]
@kghbln any idea if the original authors are still around to do some maintenance?

**Comment by kghbln** [comment]
The original version of this extension was created by Frank Dengler (you probably know him :) for SMW 1.5 as a proof of concept. A Chinese user updated it to work with SMW 1.7 which is likely to work with SMW 1.8. I do not think it will do its job for recent versions. I doubt that it is likely to be maintained in the future. Frank will not do it and I do not have any contact with the Chinese user. It is a special interest extension since it it is/was providing a [Gantt chart](https://en.wikipedia.org/wiki/Gantt_chart) as an additional result format.

Thus closing this for the time being. The good thing about this bug is that we now have this more publicly visible with good links pointing all over the place. Somebody who wants to revive this will have a good starting point.

[Original repo SVN-WMF](https://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions/SemanticProjectManagement/)
