### ISSUE TITLE
Fix up SMWRegistry

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#851]
Contact person: @JeroenDeDauw or @mkroetzsch 

SMWRegistry is an extension written for this wiki that allows people to register their SMW wikis via Special:SMWAdmin, which then makes them displayed here on [Special:SMWRegistry](https://semantic-mediawiki.org/wiki/Special:SMWRegistry). Ths extension is rather old and could use some work:

* It does not pull user count, page count, ect, data from recent MediaWikis. This could be fixed by using the API of the wiki being registered to obtain the data rather then doing weird HTML parsing.
* The registry page here could be a lot nicer. It could use MediaWikis TablePager as a base, to end up having something like on [this page](http://education.wmflabs.org/wiki/Special:Courses).
* The code in general could be improved, including utilization of more recent MediaWiki facilities.
* It would be awesome if registration provided some hook or trigger for other scripts to do their stuff. We could have a twitter account and an IRC bot on the smw channel report newly registered wikis!

It'd be a plus to have this all work in a more generic fashion that allows the code to be used by other extensions as well. MediaWiki lacks real software distribution and installation mechanisms. Once these are created, this tool would lose some of it's usefulness, but I don't see this happening any time soon.

**Comment by JeroenDeDauw** [comment]
Looks like this is actually broken ATM, since I'm getting a blank page. @kghbln do you know anything more about the status?

@thingles I remember we talked about this at some point, and figured we probably ought to just drop this thing and have something that pings Wikiapiary instead. @mwjames did you do anything in that direction? Do we even still have the thing that pings SMWregistry in the latest releases?

I remember looking at the extension before putting this on the roadmap, after I got the code from Markus. I have it in a private repo on my GitHub and was afraid to make it public, since I was concerned about how secure this code is. Which is another incentive to just remove it from SMW wiki.

> The code in general could be improved, including utilization of more recent MediaWiki facilities

Oh. I first read this as "... of more recent MediaWiki _fallacies_" :D

**Comment by mwjames** [comment]
> did you do anything in that direction?

No

> Do we even still have the thing that pings SMWregistry in the latest releases?

I don't know.

> Which is another incentive to just remove it from SMW wiki

#219

**Comment by JeroenDeDauw** [comment]
Right. Using Wikiapiary instead is tracked by #83

**Comment by kghbln** [comment]
> do you know anything more about the status?

No, I just know that it is completely broken (white page) after the upgrade to SMW 2.1. That's why I removed the link from the sidebar on swm.o. The last fully functional version was SMW 1.5.6.

We still have to remember that we are "advertising" this on "Special:SMWAdmin" so this issue will likely become a recurring one.

**Comment by JeroenDeDauw** [comment]
> We still have to remember that we are "advertising" this on "Special:SMWAdmin" so this issue will likely become a recurring one.

We probably should stop doing that then :)

**Comment by kghbln** [comment]
> We probably should stop doing that then :)

... and instead point to WikiApiary? Even if it is just for an transitional period of time until issue #83 is done by just saying something like: Log in over there and add your wiki.

**Comment by mkroetzsch** [comment]
+1 to pointing to Wikiapiary. It is much better suited for collecting SMW statistics. Our registry has had its time but it is long dead.

**Comment by JeroenDeDauw** [comment]
I had not thought of adding a simple link. Guess it's still better than an automated yet broken announce system. +1

**Comment by thingles** [comment]
A link out would be great and of course if there is a desire to link to a special landing page that is highlighting Semantic MediaWiki websites that would be easy to create.

**Comment by kghbln** [comment]
To get this moving a bit I created an [info page on WikiApiary](https://wikiapiary.com/wiki/WikiApiary:Semantic_MediaWiki_Registry) which is basically an slightly adapted version of the [original "Registry" page](https://semantic-mediawiki.org/wiki/Registry). Feel free to fluff it up it there is the need to.

On special "SMW:Admin" we should point to this page and the button should point to [that page](https://wikiapiary.com/wiki/Form:Website). Since regular users should not end up on this page I think my adaptation to it are ok.

**Comment by kghbln** [comment]
This should be a SMW 2.2 thing I believe.

**Comment by mwjames** [comment]
> To get this moving a bit I created an info page on WikiApiary which is basically an slightly adapted version of the original "Registry" page. Feel free to fluff it up it there is the need to.

Do you think it is possible to track (in other words it is querable as a simple list) the registration on wikiapiary to see whether someone was creating an entry via the form (and to evaluate whether it is actually is used or not) and distinguish it from any other form of added input (bot etc.)?

**Comment by kghbln** [comment]
I know from the past that about 5 registrations a month rolled in via this service. Dunno if there are stats or logs about it on the OSDA server. Perhaps adding a little field to the "website" form to tick whether this service is used or not may be an easy option.

**Comment by JeroenDeDauw** [comment]
I changed the stuff to point to WikiApiary in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/958

Might want to fluff up the messages a bit more.

> To get this moving a bit I created an info page on WikiApiary which is basically an slightly adapted version of the original "Registry" page. Feel free to fluff it up it there is the need to.

Right now the users will click the "Register my wiki" button on Special:SMWAdmin and end up on this page with a pile of text. For those that don't care to read it, it's not obvious how to proceed. One needs to scroll down to see the "Register my wiki" button there. So I suggest to have a more prominent one at the top.

Of course more dedicated handling would be nice. We can send along information, and already have stuff in the registration form be filled out to some extend. Also, we need to keep in mind we cannot just change the URL later. People with 2.2 installed will go the the place 2.2 knows about, even if we change it in 2.3. If someone wants to tackle these concerns, that'd be great. Perhaps we should create a dedicated issue?

**Comment by thingles** [comment]
I will also put together a custom conversion goal/funnel in Google Analytics so we can see how this is getting used and where drop off occurs.

**Comment by kghbln** [comment]
> Right now the users will click the "Register my wiki" button on Special:SMWAdmin and end up on this page with a pile of text. For those that don't care to read it ...

[Semantic MediaWiki Registry](https://wikiapiary.com/wiki/WikiApiary:Semantic_MediaWiki_Registry). I made some changes to this page.

> Also, we need to keep in mind we cannot just change the URL later. 

I think https://wikiapiary.com/wiki/WikiApiary:Semantic_MediaWiki_Registry is a good spot. I just protected the page to prevent "movers" or "shakers" messing things up.

**Comment by JeroenDeDauw** [comment]
Hurray, the page is even more fluffy now!
