### ISSUE TITLE
#info tooltip support for MobileFrontend

### ISSUE THREAD

**Issue by ckoerner** [SemanticMediaWiki/SemanticMediaWiki#868]
I run a SMW wiki with MobileFontend enabled. 

When viewing a wiki page with Semantic MediaWiki and using MobileFrontend the parser function is stripped and the text within is displayed.

Switching to desktop view and viewing the page shows the tooltip as intended.

![desktop](https://cloud.githubusercontent.com/assets/232862/6471967/cdc4d81a-c1b4-11e4-9b74-af4ec017788b.png)
![mobilefrontend](https://cloud.githubusercontent.com/assets/232862/6471968/cdccfa40-c1b4-11e4-9957-eed3f032b338.png)

I organically submitted this over here: https://phabricator.wikimedia.org/T63225

**Comment by mwjames** [comment]
Running "#info tooltips Semantic MediaWiki parser function" works as expected, if for some reason `MobileFrontend` requires special attention then this needs to be handled on a case-by-case basis but I'm certainly opposed for introducing any spaghetti code or hidden dependency on behalf of the `MobileFrontend` by doing something like:

```php
	if ( class_exists( "MobileFrontendClass" ) ) {
		ExtraWork::doSomethingNastyBecauseOfMobileFrontend();
	}
```

The info itself is displayed with the help of http://qtip2.com/.

Feel free to post a PR that would add `MobileFrontend` support.

**Comment by ckoerner** [comment]
@mwjames Am I correct to understand that this means SMW needs to add a [ResourceLoader module for MobileFrontend](https://www.mediawiki.org/wiki/ResourceLoader/Writing_a_MobileFrontend_friendly_ResourceLoader_module) to support these tooltips?

**Comment by mwjames** [comment]
> Am I correct to understand that this means SMW needs to add a ResourceLoader module for MobileFrontend to support these tooltips?

I'don't really know MobileFrontend nor what it does but my first guess is that it requires some extra  modules. Another reason I could imagine is that (due to of the text being displayed without formatting) somehow the qtip element is not created appropriately and therefore the raw text is displayed instead.

Normally you have a qtip anchor on a  page where #info is used (see example reference `qtip-1`).

![qtip-2](https://cloud.githubusercontent.com/assets/1245473/6488299/f43205ba-c2d9-11e4-8c36-2c9461e85850.png)

![qtip-3](https://cloud.githubusercontent.com/assets/1245473/6488341/36113ae6-c2da-11e4-9d4c-8544f5afc1d6.png)

**Comment by mwjames** [comment]
See #1049 / 2.3.x
