### ISSUE TITLE
Semantic Data remains when moving a page to a non SMW NS.

### ISSUE THREAD

**Issue by rglasnap** [SemanticMediaWiki/SemanticMediaWiki#869]
This may be related to #566 Basically whenever I move a page from the Main Namespace to a different NS it still shows up in queries. The destination NS is deliberately not enabled via $smwgNamespacesWithSemanticLinks 

1. Create a Page in the Main NS with Semantic Data
2. Create a query that captures that page.
3. Move the page to a NS that doesn't have Semantic Links
4. Check query

Relevant versions:
MW: 1.23.8
SMW: 2.1 (same problem on 2.0, I upgraded to 2.1 thinking it might be fixed, but nope, not fixed).

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue!

**Comment by mwjames** [comment]
> This may be related to #566

Kind of, never thought the `SQLStore` could be infected as well. The code path [0] is as old as the Store itself (it does not check on whether the target NS is enabled for annotations or not).

```php
		// Easy case: target not used anywhere yet, just hijack its title for our current id
		if ( ( $tid == 0 ) && ( $smwgQEqualitySupport != SMW_EQ_NONE ) ) {
			// This condition may not hold even if $newtitle is
			// currently unused/non-existing since we keep old IDs.
			// If equality support is off, then this simple move
			// does too much; fall back to general case below.

		...

		} else { // General move method: should always be correct
			// (equality support respected when updating redirects)

			// Delete any existing data (including redirects) from new title
			// ($newtitle should not have data, but let's be sure)
			$emptyNewSemanticData = new SMWSemanticData( SMWDIWikiPage::newFromTitle( $newtitle ) );
```

## Solution 

In order to avoid to add even more conditions to an already crowded `SMWSQLStore3Writers::changeTitle`, the `TitleMoveComplete` should be extended with something like (works on both `SQLStore` and `SPARQLStore`):

```php
		// Delete all data for a non-enabled NS
		if ( !ApplicationFactory::getInstance()->getNamespaceExaminer()->isSemanticEnabled( $this->newTitle->getNamespace() ) ) {

			$cache->setCacheEnabled( $this->oldId > 0 )
				->setKey( FactboxCache::newCacheId( $this->oldId ) )
				->delete();

			ApplicationFactory::getInstance()->getStore()->deleteSubject( $this->oldTitle );
		} else{
			ApplicationFactory::getInstance()->getStore()->changeTitle(
				$this->oldTitle,
				$this->newTitle,
				$this->oldId,
				$this->newId
			);
		}
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3_Writers.php#L751

**Comment by mwjames** [comment]
Feel free to test 2.2-master to verify that your observed issue no-longer occurs.
