### ISSUE TITLE
Unable to edit a popular property page

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#948]
An issue was reported to me that adding a new allowed value to http://tieteentermipankki.fi/wiki/Ominaisuus:Kieli did not work. After investigating I found out that null edit to that page does not complete because it runs out of memory.

I proceeded to do a null edit via command line with unrestricted memory use. First I thought it just gets stuck at something, but once I enabled a debug log I saw what is the issue. The full debug log is 58M, half of it caused by #947. I can provide the full log on request.

Here is what I ran on eval.php:

``` php
$wgShowExceptionDetails = true;
$wgShowSQLErrors        = true;
$wgShowDBErrorBacktrace = true;
$wgDebugComments        = true;
$wgLogQueries           = true;
$wgDebugDumpSql         = true;
$wgDevelopmentWarnings  = true;
$wgDebugTimestamps = true;
$wgShowDebug = true;
$wgDebugLogFile = 'php://stdout';

$title = Title::newFromText( 'Ominaisuus:Kieli' );
$revid = $title->getLatestRevID();
$target = Revision::newFromId( $revid );
$page = new WikiPage( $title );
$page->doEditContent( $target->getContent(), '', EDIT_UPDATE, $target->getId(), User::newFromId( 1 ) );
```

What happened, is that it used about 1.5G of memory, creating around 270k jobs (many of them duplicates and dropped on insert time). That is about twice the amount of pages we have in the wiki. 

Obviously, this does not scale. The new allowed value did appear though, when the script was finished.

**Comment by mwjames** [comment]
> What happened, is that it used about 1.5G of memory, creating around 270k jobs (many of them duplicates and dropped on insert time). That is about twice the amount of pages we have in the wiki.

What is the issue here exactly? What are the steps to replicate this on a different wiki (or be able to write a regression test)?

- Step create page with ... ?
- Step two ...and so forth 

What version of SMW is used (I'm guessing 2.0 due to the #947 reference but that's not obvious). If it is 2.0 can it be observed with 2.1* as well?

**Comment by mwjames** [comment]
@kghbln Any insights on what the issue is here?

**Comment by Nikerabbit** [comment]
The issue is that editing a property page takes too much memory (and too long) if (my assumption) that property is used on many pages. You can try if you see similar behavior on your wiki by replacing the page name in the script with some other popular property.

Observed on 2.0, we haven't yet set a date when to update SMW on this wiki.

There are no stack traces in the log.

**Comment by kghbln** [comment]
If I interpret this correctly the property is used on so many different wiki pages that the mechanics triggered by adding a new allowed value to this property are so expensive memorywise that it fails doing so.

One thing that will help is upgrading the sever to Debian 7 to make use of MySQL 5.5+ as well as PHP 5.4+. From personal experience I know that this will already make a difference. However they are hitting limits of SMW here.

The side note about issue #947 appears to me being irrelevant in relation to the problem as such. It just makes it harder to see the actual issue within the log.

**Comment by mwjames** [comment]
> If I interpret this correctly the property is used on so many different wiki pages that the mechanics triggered by adding a new allowed value to this property are so expensive memorywise that it fails doing so.

OK, now I start to understand the issue. So for example:

- Property:A is being specified by constraints (using `allows value`) and
- Property:A is used in xxx amount of pages as annotation 

Issue:
- Extending Property:A with a new constraint (by to adding `allows value`) will cause an exhaustion of memory

Correct?

**Comment by kghbln** [comment]
Indeed, that's what I believe the issue is.

**Comment by mwjames** [comment]
Some information about the course of action when you change a property page.

Before a new set of data is stored about a Property (its type, constraint etc.), `PropertyTypeDiffFinder` [0] tries to compare old and new values (about that property) to find related subjects in order to create a job list (which would inevitably run an update through the job queue) to ensure that type or constraint changes are applied to the existing entity descriptions.

The code from 1.8 had note about it [1] but I never saw this actually happen. The issue that we face is that we need the old data before the new data is stored otherwise we can't make a comparison of old and new.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/PropertyTypeDiffFinder.php#L112

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/SMW_ParseData.php#L334

**Comment by mwjames** [comment]
> What happened, is that it used about 1.5G of memory, creating around 270k jobs (many of them duplicates and dropped on insert time).

? Really because the `UpdateDispatcherJob` ([0] the one that creates the job list) is internally tracking `$this->jobs[$title->getPrefixedDBkey()] ...` all titles it is pushing to the queue.

I'm not sure what is the best strategy here, create the list synchronous without creating any `UpdateJob` instances but instead push the list to the `UpdateDispatcherJob` so that on the second run the `UpdateDispatcherJob` can take the list and create all jobs in the background.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Jobs/UpdateDispatcherJob.php#L147

**Comment by mwjames** [comment]
>  it used about 1.5G of memory, creating around 270k jobs

@kghbln Since this is about mass-inserts, do we have any wiki that can simulate such "outages" but with the current master? I'd like to try some ideas but only under the precondition that it can be verified.

**Comment by JeroenDeDauw** [comment]
> Observed on 2.0, we haven't yet set a date when to update SMW on this wiki.

There are multiple fixes available in the more recent releases, none of which introduce breaking changes. So upgrading is definitely something to try.

**Comment by mwjames** [comment]
> Observed on 2.0, we haven't yet set a date when to update SMW on this wiki.
There are multiple fixes available in the more recent releases, none of which introduce breaking changes. So upgrading is definitely something to try.

This isn't really a 2.0 or 2.1 thing, the issue is as old as SMW because of the way data need to be compared to each other before the replacement (SMW doesn't now any revision, so it only knows what is stored and therefore comparison can only be happen shortly before the update).

@Nikerabbit I don't know if you can test #951 (requires 2.2 master) but #951 tries to push some of the work further into the jobqueue and hopefully can release some blocking behaviour from the editing process.

**Comment by kghbln** [comment]
> @kghbln Since this is about mass-inserts, do we have any wiki that can simulate such "outages" but with the current master? I'd like to try some ideas but only under the precondition that it can be verified.

The only wiki in the vicinity which would come to my mind is Wikiapiary though I am not sure if @thingles will be happy about doing something like this. I myself currently do no control a wiki which I could use for this purpose.

**Comment by mwjames** [comment]
If this is still an issue then it should be reported in connection with a maintained SMW version.

PS: SMW 2.5 added support for lists maintained via a MediaWiki page (#2295) that should help avoid issues on properties with a large pool of value dependencies.
