### ISSUE TITLE
Info about high frequency usage on property page

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#952]
refs #948

@kghbln  Do we need something like a high frequency usage warning (as in the screen dump)? A message that is displayed for user-defined properties after a threshold is reached `smwgPropertyHighFrequencyUsageInfoThreshold = 2000` (0 means ignore the display).

In case we want to display such warning what would be the default threshold?

![prop-high-usage](https://cloud.githubusercontent.com/assets/1245473/6914874/36055618-d7ca-11e4-85ce-be160438e138.png)

**Comment by JeroenDeDauw** [comment]
Seems like a question to ask the mailing list.

**Comment by kghbln** [comment]
Well this could go to the mailing list. My personal preference will to have this extra information. This also en passant creates more awareness for the underlying mechanics in the long run. E.g. seen people frantically changing the datatype basically for no good reason. The threshold should imho be rather low since I am thinking about low traffic wikis with no other way than the MW default job run rate setting. @JeroenDeDauw What's your opinion whilst we are at it.

**Comment by JeroenDeDauw** [comment]
I can see how this might be useful, though I am not running any wikis myself, so think I cannot provide input on if this is something that is generally wanted, much less if people would not want it for some reason.

**Comment by kghbln** [comment]
Fair enough. Since this info may be disabled by setting to `0` I think we should go for it. I am currently also thinking of wikis "under" my control here too.

**Comment by mwjames** [comment]
#1313
