### ISSUE TITLE
jquery.qtip loaded in all namespaces?

### ISSUE THREAD

**Issue by connorshea** [SemanticMediaWiki/SemanticMediaWiki#976]
I've been working on a redesign of [PCGamingWiki](http://pcgamingwiki.com) and we've been trying to get the page sizes down as much as possible. We noticed that jquery.qtip and some other SMW styles/scripts were loading on pages that didn't seem to use them at all. Is there any way we can disable these files for certain namespaces? And if not, is there any chance you can add such a feature in a future release?

**Comment by JeroenDeDauw** [comment]
What version of SMW are you using?

**Comment by mwjames** [comment]
> been trying to get the page sizes down as much as possible.

What percentage of SMW relate styles (in terms of size) compared to MW styles we are talking about? RL (ResourceLoader) generally takes care of caching, compression etc. so I would guess MW developers have already thought about optimizing the transportation layer for scripts/styles.

> We noticed that jquery.qtip and some other SMW styles/scripts were loading on pages that didn't seem to use them at all. 

Maybe removing `ext.smw.tooltips` from `InTextAnnotationParser::getModules` [0] should help your cause (I haven't test it).

Styles (which includes `jquery.qtip.css`/`ext.smw.js` [1, 2] and are only styles) are generally top-loaded to ensure that no DOM flickering occur (because of RL's standard bottom lazy loading policy).

> Is there any way we can disable these files for certain namespaces?

The ResourceLoader doesn't support a feature to distinguish module loading on NS basis therefore you have to do that in PHP. 

There was a reason in the past (1.19/1.20) while certain styles/scripts are loaded on all pages to avoid DOM flickering. 

> is there any chance you can add such a feature in a future release?

This isn't on my list.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L152

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/resources/Resources.php#L33

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/BeforePageDisplay.php#L56

**Comment by mwjames** [comment]
NS check added with 3b8c24f9e61.

**Comment by connorshea** [comment]
Excellent! :smile: Thank you!
