### ISSUE TITLE
<nowiki></nowiki> in tooltips

### ISSUE THREAD

**Issue by Contrafibularity** [SemanticMediaWiki/SemanticMediaWiki#982]
I've now noticed several wikis that show tooltips saying that 'some part "&lt;nowiki>...&lt;/nowiki>" of the query was not understood'. This might convey the impression (as it did to me at first) that the use of nowiki tags was not done properly on the site. It may be case, however, that the problematic bit of syntax (if there is any - it could be a malformed query) is not meant to be rendered as wikitext. In other words, this would be a problem of tooltips not being able to handle nowiki tags.

**Comment by JeroenDeDauw** [comment]
What version of SMW? Also, for what queries does this happen?

**Comment by mwjames** [comment]
Using `<nowiki>` requires special care (see explanation #232, for use in annotations see #794) therefore making it available as either unstripped text or as part of an annotation needs work and does not come out-of the box.

**Comment by Contrafibularity** [comment]
SMW 1.24.2 and probably older versions

The error message is probably from "smw_badqueryatom": "Some part \"&lt;nowiki>[[...]]&lt;/nowiki>\" of the query was not understood.", which is then used in a tooltip and not rendered correctly for reasons above.

**Comment by mwjames** [comment]
> The error message is probably from "smw_badqueryatom": "Some part \"<nowiki>[[...]]</nowiki>\" of the query was not understood.", w

The reason is a different one a cited above, predefined message like `"smw_noclosingbrackets": "Some use of \"<nowiki>[[</nowiki>\" in your query was not closed by a matching \"]]\".",
` that contain a `<nowiki>` tag [0] and are not parsed (use of `wfMessage( ... )->inContentLanguage()->text()`) will only render text as is and not run it through the MW parser (which would be necessary if you wanted tags such as `<nowiki>` to be resolved).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/query/SMW_QueryParser.php#L520

**Comment by kghbln** [comment]
I get this sometimes too for 2.1.3 when I mess up some query. Probably replacing `<nowiki>[[</nowiki>` by `&#91;&#91;` in "smw_noclosingbrackets" will fix this. Wanted to do a quick test but currently I fail to create a query resulting in an issue which is triggering this error message. Well ...

**Comment by mwjames** [comment]
> SMW 2.1.3 and probably older versions

This issue been categorized and selected as "Enhancements and features" and since it has not seen any update within the last 90 days, it has now been closed and moved to the "Enhancements and features" board. In case the issue finds a sponsor or is actively worked on it can be reopened.

**Comment by kghbln** [comment]
I have created an [example](https://sandbox.semantic-mediawiki.org/wiki/Issue/982) for this. Since SMW 3.0.0 a completely new library is being used so I figured. Anyways we no longer get the nasty note, however the "nowiki" tags are not considered either. I think this is a substantial improvement though ... I can live with this.

**Comment by mwjames** [comment]
> Since SMW 3.0.0 a completely new library is being used so I figured... 

This has nothing to do with the JS library.

> Anyways we no longer get the nasty note, however the "nowiki" tags are not considered either.

We strip [0] tags to avoid issues during the internal parsing when MW builds the HTML output, well we are loosing the `nowiki` tag but that's just the way it is. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/Highlighter.php#L283-L287
